### ISSUE TITLE
In APIdocs, show model by default instead of example

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1001]
The model information is richter then the example (for example, explains which parameters are optional), so we should show this by default.

Swagger has a config option `defaultModelRendering=model` for this (see https://github.com/swagger-api/swagger-ui/blob/aa506930a741e154119467d32f1ab797b492444c/docs/usage/configuration.md#display).

Not sure how/where that option should be set to propagate it from flassger to swagger.

**Comment by oharsta** [comment]
Tried hardcoding it in our fork of flasgger, but the option is not picked up. Needs more investigation.
