### ISSUE TITLE
As a CO admin, I want to be able to see more user info than only a name when adding a user to a group

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1002]
![Screenshot 2023-10-10 at 17 16 17](https://github.com/SURFscz/SBS/assets/1461740/21a6fc13-6cb5-423d-a810-2433af610893)

**Comment by FlorisFokkinga** [comment]
Email addresses can be the same, IdP domain can also be the same. Only real solution is to add both of those.

**Comment by FlorisFokkinga** [comment]
Consider changing the GUI for this, similar to tables with users, not a pull down menu.

**Comment by FlorisFokkinga** [comment]
The email addresses are now visible. Is this good enough?
In case a user is a member with both their institution account and an eduID with their institution email address, they appear the same.

<img width="1080" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/eac2b908-e8b9-4061-b4ff-e7720e945e10">

**Comment by baszoetekouw** [comment]
Yes, seems good enough (at least for now).
