### ISSUE TITLE
Service ID is reused from request

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1018]
Service registration: https://sram.surf.nl/service-request/2
Service: https://sram.surf.nl/services/2/details

The service has properties from a deleted service.

**Comment by venekamp** [comment]
Mijn observatie... en twee centen:

Ik denk dat je het kunt reproduceren als je i) een dienst aanmaakt, ii) een paar dingen configureert (groep aanmaken, service linken, etc.), iii) dienst verwijdert, iv) dienst met zelfde naam weer aanmaakt. Mijn short name was: co_snellius. Die zou zomaar niet gelijk kunnen zijn aan de vorige instantie. De display naam heeft wel een hoge kans van gelijkheid.

**Comment by baszoetekouw** [comment]
Gefixed in een patchrelease in v27.  Gaat verder mee in v28.

**Comment by baszoetekouw** [comment]
tested
