### ISSUE TITLE
Add placeholder at CO with empty connected service list

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1020]
## Current situation
![Image](https://github.com/SURFscz/SBS/assets/80269262/a9221f58-83e9-4e2d-8861-60fc225b816a)

## Proposed solution
Add a placeholder image and text:
```
There are no services connected to your collaboration. Why don't you [connect one]?
Er zijn geen diensten gekoppeld aan je samenwerking. Wil je de [eerste koppelen]?

```
With a link to the 'Available services' section.

![Image](https://github.com/SURFscz/SBS/assets/80269262/9f5fe613-76cc-43f7-bb6c-254e72f850cd)

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/4ec25cd3ab4117396a69c734419caf1551339aca

**Comment by FlorisFokkinga** [comment]
![Image](https://github.com/SURFscz/SBS/assets/80269262/d8c83fe8-ae0c-411f-b36f-e216f7b845fc)
