### ISSUE TITLE
Empty expiry date field on invitation causes blank screen

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1022]
### Reproduction
- Go to CO page, admin or member tab
- Use 'Invite' button
- Empty the 'Invitation expires on' field using the cursor and backspace/delete
Expected: Expiry date is emptied, but invite cannot be sent without an expiry date
Observed: Screen turns blank

**Comment by baszoetekouw** [comment]
now works correctly

![Image](https://github.com/SURFscz/SBS/assets/1461740/ff213877-89ab-48d8-bce0-e3d75860133a)
