### ISSUE TITLE
Add short name to CO header, also show about tab to CO admins

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1029]
- Add the CO short name as first item in the iconed list
- To make room, remove the CO description from the header
- Instead, also show the about tab to CO admins

![Image](https://github.com/SURFscz/SBS/assets/80269262/54b8628e-f892-4495-9e92-5e201fb94eb2)

![Image](https://github.com/SURFscz/SBS/assets/80269262/b2f0e609-c231-40d8-a58b-e58765836cc9)

**Comment by baszoetekouw** [comment]
tested. The about tab is now default for CO admins; @FlorisFokkinga we might want to change that to, e.g., the members tab
