### ISSUE TITLE
As a service admin, I want to be able to delete my service

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1030]
If COs are connected, refuse and instruct admin to disconnect those first at the 'connected collaborations' tab.

**Comment by baszoetekouw** [comment]
Deletion now works, but I think it is now too easy for an admin to remove a Service.  Also, teh service also needs to be removed at EduTEAMS.

So, instead of actually removing the Service, please send an email to sram-beheer instead.  A platform admin can then actually remove the service.
