### ISSUE TITLE
SCIM sweep doesn't scale well

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1032]
The current SCIM sweep implementation reads in all remote SCIM objects that are presented by the remote SCIM server (https://github.com/SURFscz/SBS/blob/main/server/scim/sweep.py#L90).  However, some remote SCIM server turn out to have huge (like ~1000 pages of groups), which causes SBS to run out of memory.

So please limit the amount of data that is stored in memory at the same time, by disallowing huge download (and failing the sweep), by storing them temporarily on disk or in a db, or by finding a more memory-efficient way of doing the sweep.

**Comment by baszoetekouw** [comment]
Turns out that something else is wrong.  I assumed that that the remote system @HarryKodden was connecting to really had a large number of groups and users, but it turns out there are only 11 groups defined.  The 11th groups triggered pagination by the remote, which in turn triggered a bug in SBS so the recursion never terminates.

In the logs, I see this:
```
Oct 24 13:30:00 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=1 HTTP/1.1" 200 None
Oct 24 13:30:00 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=2 HTTP/1.1" 200 None
Oct 24 13:30:00 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=3 HTTP/1.1" 200 None
Oct 24 13:30:01 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=4 HTTP/1.1" 200 None
Oct 24 13:30:01 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=5 HTTP/1.1" 200 None
Oct 24 13:30:01 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=6 HTTP/1.1" 200 None
Oct 24 13:30:01 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=7 HTTP/1.1" 200 None
...
Oct 24 13:31:15 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=920 HTTP/1.1" 200 None
Oct 24 13:31:15 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=921 HTTP/1.1" 200 None
Oct 24 13:31:15 sbs-pf1 gunicorn[1798]: DEBUG:urllib3.connectionpool:https://viya.XXXX.yyy:443 "GET /identities/scim/v2//Groups?startIndex=922 HTTP/1.1" 200 None
```
after which the process runs out of memory.

However, according to @HarryKodden  the content of those pages is:
```json
{
	"schemas": [
		"urn:ietf:params:scim:api:messages:2.0:ListResponse"
	],
	"startIndex": 1,
	"itemsPerPage": 10,
	"totalResults": 11,
        ...
}
```
for the first page, whereas `https://viya.XXXX.yyy/identities/scim/v2/Groups?startIndex=11` returns simply:
```json
{
	"schemas": [
		"urn:ietf:params:scim:api:messages:2.0:ListResponse"
	],
	"startIndex": 11,
	"itemsPerPage": 10,
	"totalResults": 11,
        ...
}
```
with a single item of that second page.

@HarryKodden could you maybe change what the content is of the pages with larger `startindex` parameters?

Anyway, there seem to be multiple issues here:
 - the pagination is not consistent.  Why is `startindex` only increased by one on every call instead of by `itemsPerPage`?
 - Why does the recursion not terminate?
 - Why does the remote return 200 on the pages with large `startindex` instead of an error?  What is the content of those pages?
 - Should we have a failsafe in SBS to limit te recursion (and fail the sweep if the recursion becomes too deep)?
 - Can't we replace the recursion by a loop?

**Comment by HarryKodden** [comment]
This is suggestion to replace method with this non-recursive alternative.
```
def _all_remote_scim_objects(service: Service, scim_type):
    scim_resources=[]

    while True:
        url = f"{service.scim_url}/{scim_type}?startIndex={len(scim_resources)+1}"
        response = requests.get(url, headers=scim_headers(service), timeout=10)
        if not validate_response(response, service, outside_user_context=True, extra_logging=f"SCIM {scim_type} list"):
            raise BadRequest(f"Invalid response from remote SCIM server (got HTTP status {response.status_code})")
        
        scim_json = response.json()
        scim_resources += scim_json["Resources"]
        
        if scim_json["totalResults"] == len(scim_resources):
            break
            
    return scim_resources
```

**Comment by baszoetekouw** [comment]
@HarryKodden kun jij deze testen?
