### ISSUE TITLE
Tweaks for Organisation Units

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1052]
- Conceptually:
  - ~~Should a Org manager with one or more Units enabled maybe be called a Unit Manager instead?  That would make the distinction between an Org Manager with Units and an Org Manger without Units much more clear.~~ --> voor nu ok, probably solved by other UI tweaks.  Maybe adjust if pilot users find it confusing.
- In Org admin.manager overview:
  - ~~In table of admins/managers, show units the manager is responsible for (or "all"/empty/*)~~
  - ~~Unclear that you can click on a manager to adjust unit roles~~
- In Org Manager edit screen:
  - ~~"CO's to be managed" -> "Units to be managed" (??)~~ fixed
  - ~~"All CO's" -> "All units" (??) etc~~ fixed
 - ~~Authorisations:~~
    -  ~~unclear how this works: if a manager can only manage a specific unit, are they then allow to manage COs without unit?~~
       - ~~ah: seems that if a CO has no Unit, all managers can manage theat CO (regardless of Unit of Manager).  If CO has a Unit, only Unit Managers can manage it.~~
       - ~~Is this what we expect?  Shouldn't the default be that a manager can manage no Units rather than all Units?~~
          - ~~ArTe: I think unit managers should only see (and be able to manage) CO's belonging to their own unit(s). Not other units and thus also not CO's without a unit~~ bug #1060
    - ~~make clear for Org Manager which Units they can manage.~~ --> no quick fix, let's wait for questions from actual users.
    - ~~Should Unit Managers be able to see (read-only) COs of other Units?  Currently, they can't, but that's confusing, because it is unclear to those managers that they don't have a full view of the Org.~~ --> no, minimal disclosure
    - ~~An Org Manager can create COs without units (shouldn't be possible)~~ --> fixed
- CO screen:
  - ~~use – (`&ndash;`) instead of - (hyphen or hyphen-minus) in title of CO to separate Org and Unit~~ fixed in [2dc8a5c](https://github.com/SURFscz/SBS/commit/2dc8a5cc12f5afe8e0c293eba6f3fb82f3cddd85)
  - ~~In edit, move "Relevant unit" to below "Responsible Organisation"~~ fixed
  - ~~In edit, make clear that "Relevant Unit" is coupled to "Responsible Organisation"~~ --> order is changed
- API:
  - Express Units for COs and Manager in `plsc/sync` endpoint --> #1265
  - Do we want to express Units in the SAML attributes/OIDC claims? --> #1266
  - Don't expose the internal id of the units to the API.  So, use a simple array of names, rather than an array of objects `{name,id}`.  In `/api/collaborations/v1/{co_identifier}` and in `/api/organisations/v1` --> #1264

**Comment by baszoetekouw** [comment]
Mostly done, continues in #1264 #1265 #1266

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SBS/issues/1264#issuecomment-1988766506
