### ISSUE TITLE
Replace error page animations by static images

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1057]
The animated error pages currently use the lottie-player module, which is quite large and can be run with a strict CSP (see #764).

Therefore, we should replace the animated pages by a nice static images.  

The following pages should be fixed:
- `client/src/pages/DeadEnd.jsx` --> https://sram.surf.nl/dead-end
- `client/src/pages/NotFound.jsx` --> https://sram.surf.nl/anythinghere
- `client/src/pages/ServerError.jsx` --> https://sram.surf.nl/error
- `client/src/pages/ServiceDenied.jsx` --> https://sram.surf.nl/service-denied?service_name=Pippie+Langkous&error_status=4&entity_id=Kakelbont&issuer_id=hoipiepeloi&user_id=pippie%40sram.surf.nl

@FlorisFokkinga could you propose what these pages should look like?

**Comment by baszoetekouw** [comment]
Is `/dead-end` even used anymore?  What is dat supposed to do?

**Comment by oharsta** [comment]
See also https://github.com/SURFscz/SBS/commit/e0de2fda78f9b53f65f8476c3365efecc0b7f250. I have put the images in the original `lotties` folder to find them easily. Once the final images are picked, we can move them.

**Comment by FlorisFokkinga** [comment]
It is permitted to use animated SVG files for this.

**Comment by FlorisFokkinga** [comment]
I've spent 15 minutes searching for OK looking CSS animated SVGs.

**Comment by FlorisFokkinga** [comment]
Please (re)center the 404 page: https://test.sram.surf.nl/anythinghere

**Comment by oharsta** [comment]
Re-centered 404 in https://github.com/SURFscz/SBS/commit/81e742044cce451896694a08b375a6ed63b6d195
