### ISSUE TITLE
An org manager scoped on one ore more units, should only be able to see and edit COs of those units

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1060]
## Reproduction
Org manager assigned to unit 'Faculty'
![image](https://github.com/SURFscz/SBS/assets/80269262/ac1afba2-357f-4aea-b8c5-41d834f06801)

All COs (platform admin view)
![image](https://github.com/SURFscz/SBS/assets/80269262/613071d7-03fd-45d4-93af-b012b4253e99)

- Expected view for org manager: only the CO for unit 'Faculty' 'Monitoring CO numero 1'
- Observed view: only the CO without a unit label 'UUC Teachers'

![image](https://github.com/SURFscz/SBS/assets/80269262/89f492b5-47e4-4a03-90ca-6464ceac6ddb)

### Reproduction, continued
- Assigned unit 'Faculty' to the CO  'UUC Teachers'
- Expected and observed view: only the CO with the unit label: 'UUC Teachers'

![image](https://github.com/SURFscz/SBS/assets/80269262/3c85c6ca-f3a5-4cd7-98ad-6d9c7d46fd84)

## Expected behaviour
- An organisation manager for unit A can only view/edit COs that are assigned to unit A (not exclusively).
- An organisation manager for unit A and unit B can only view/edit COs that are (at least) assigned to unit A an/or unit B (not exclusively).

**Comment by baszoetekouw** [comment]
There is stil an issue here: Org Managers can still view all COs of the Org (by visiting the direct URL).  They should only be able to see the COs in their own Unit.

**Comment by baszoetekouw** [comment]
Rest of the story tested an is ok.

**Comment by baszoetekouw** [comment]
now fixed.
