### ISSUE TITLE
As a service admin without CO membership, I want the service tab to be my default

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1061]
Currently, if a user is not a member of a CO, but does have other tabs available in their home screen (Services, Orgs, Requests), still the Collaborations tab is selected by default:

![Screenshot 2023-11-14 at 10 01 02](https://github.com/SURFscz/SBS/assets/1461740/b65d6fbe-ab97-4c5b-839a-cb55c8be3b38)

Instead, the first tab with active entries should be default.

**Comment by baszoetekouw** [comment]
Curiously enough, for the user above, when I removed their Service Admin access, also the "Collaborations" tabs vanished and only the "My Requests" tab is shown.

So to reproduce:
 - create a user who 
   - can request new COs
   - is Service admin
   - has an outstanding request for a new CO
 - that should lead to the home screen as shown above
 - then remove the Service Admin role
 - That gives this home screen:
 - 
![Screenshot 2023-11-14 at 10 07 20](https://github.com/SURFscz/SBS/assets/1461740/1f67d11d-7bb0-49fd-bd19-8410fd0e787d)

**Comment by FlorisFokkinga** [comment]
These might be two problems:
1. landing page for service admin without membership and
2. user with only requests

**Comment by FlorisFokkinga** [comment]
Considering
- #1078

i'd like to suggest only changing the default tab to 'services' if the 'collaboration' tab is empty.

**Comment by mrvanes** [comment]
OK
