### ISSUE TITLE
Improve error message design when user tries to login to service which is not connected to any CO (s)he is a member of

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1076]
Too often we get support emails from users who experience this problem. The text exactly states what the problem is but apparently it's not clear (enough). Please redesign this screen keeping in mind that the user has no knowledge of SRAM or how it works.

![image](https://github.com/SURFscz/SBS/assets/80269262/5fb8f745-58ba-40a3-b136-670c5ccea2f3)

![undraw_secure_login_pdn4_1](https://github.com/SURFscz/SBS/assets/80269262/a7a552d9-0a58-4f6c-8878-3377bcb4d122)
![undraw_visionary_technology_re_jfp7_1](https://github.com/SURFscz/SBS/assets/80269262/1263b088-fcaf-461f-979a-96c2c80bd8ed)
The 'happy' is the same image as on the login page.

**Comment by oharsta** [comment]
@FlorisFokkinga Does this concern the service-denied page? And if so, is the contact link the mailto with the additional info in the mail message? See https://github.com/SURFscz/SBS/issues/1120

**Comment by FlorisFokkinga** [comment]
It does, and it is.
Or would leaving the error information off the page cause problems in case the user doesn't want to use the default email client?

**Comment by oharsta** [comment]
I think it would be confusing if we pre-fill parts of the email without displaying them on the screen. And the call-to-action (e.g. mail SBS-support) is now less clear.

**Comment by FlorisFokkinga** [comment]
Ok. Let's add a third box with the error messages and this image.

It is intentional that mailing support is not the first recommendation. We found that often there is no error, the user simply isn't member of a CO that allows access to the service. The problem is that it's not up to us to decide what CO this user should become member of. The best we can do is refer them to the collegue that invited them, their institution or the service admin.

![undraw_code](https://github.com/SURFscz/SBS/assets/80269262/d465401b-b291-4f95-b089-592aea4699bf)
