### ISSUE TITLE
/pam-weblogin/check-pin endpoint uses wrong json escapes

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1079]
Since the groupname sorting of /pam-weblogin/check-pin, SBS now responds with a `\"` escaped response, which can not be parsed by the json library we use, resulting in a segmentation fault during the verification of the pin:
```
Request to https://sram.surf.nl/pam-weblogin/check-pin, 201, "{\"result\": \"SUCCESS\", \"username\": \"mvanes\", \"groups\": {\"democollab\": \"Demo collaboration\", \"demo\": \"Demonstration Collaboration\"}, \"info\": \"User c7c7f2c1ee3a469558cd64942b86fbc4273abfa2@sram.surf.nl has authenticated successfully\"}"
```
```
# pamtester weblogin mvanes authenticate
Please sign in to: https://sram.surf.nl/weblogin/sram_demo_pam/xxxxx
Verification code: 
Segmentation fault
```

**Comment by mrvanes** [comment]
We need a ssh-demo vm that is connected to acc.

**Comment by baszoetekouw** [comment]
Just discussed this with @mrvanes .  As prod is already broken, we mioght just as well move to a new output format with has groups in a list of dicts instead of a plain dict.

**Comment by baszoetekouw** [comment]
tested; works.
