### ISSUE TITLE
Service requests should be tickets instead of beheer mails

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1091]
Send service requests to sram-support@surf.nl instead of sram-beheer@surf.nl.

**Comment by HarryKodden** [comment]
This is still send to sram-beheer@surf.nl



![Image](https://github.com/SURFscz/SBS/assets/1842889/078b636e-05ac-4e9f-90fc-8e93ef696179)

**Comment by oharsta** [comment]
The mail above is **not** a service request (send to `mail_cfg.ticket_email`, see https://github.com/SURFscz/SBS/blob/main/server/mail.py#L356), but the creation of a service (e.g. object) which is send too `mail_cfg.beheer_email`. See https://github.com/SURFscz/SBS/blob/main/server/mail.py#L363. This story specifically deals only with requests for services.

**Comment by HarryKodden** [comment]
Correct !
Then this story is complete



![Image](https://github.com/SURFscz/SBS/assets/1842889/b4d4fe60-b540-4076-890a-031ba0c3330e)
