### ISSUE TITLE
Group membership changes are not recorded in the audit log

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1124]
It seems changes to group membership are not logged in the audit logs.  Could you please add that?

**Comment by oharsta** [comment]
@baszoetekouw Which changes do you refer to? When I add or delete a member from a group then audit log entries are created.

**Comment by baszoetekouw** [comment]
Hmm, I don't see those entries?  For example, I added and remobved Jane Doe to the AI developers group (at https://test.sram.surf.nl/collaborations/3465/groups) a few times, but that doesn't show up in https://test.sram.surf.nl/audit-logs/collaborations/3465?name=AI%20computing&back=%2Fcollaborations%2F3465%2Fgroups

**Comment by oharsta** [comment]
I just deleted poor Jane again and it show in the audit logs
<img width="1301" alt="image" src="https://github.com/SURFscz/SBS/assets/530657/4795f56b-6885-4963-a2e4-42ca439dd296">

**Comment by oharsta** [comment]
Group member management does generate audit_log entries. But you'll not find them in the CO history, but in the Group history which can be found at the group detail page.

**Comment by baszoetekouw** [comment]
I'll open a new issue to tweak the UI of the group membership logs a bit (see #1203).
