### ISSUE TITLE
Unit manager cannot create a CO when they are also admin of a different organisation

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1129]
![image](https://github.com/SURFscz/SBS/assets/80269262/9314665b-be48-499d-8e78-a01d8c03531c)

**Comment by oharsta** [comment]
@FlorisFokkinga Please add the scenario to reproduce.

**Comment by oharsta** [comment]
https://test.sram.surf.nl/organisations/300/admins, 
Impersonate user 'SRAM demo' in user overview for supper admin.

**Comment by oharsta** [comment]
Duplicate of https://github.com/SURFscz/SBS/issues/1142

**Comment by FlorisFokkinga** [comment]
Reproduction scenario is fixed.
