### ISSUE TITLE
A unit manager who is also manager of an organisation without units, cannot select a unit while creating a collaboration in the first organisation

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1142]
To repoduce in test: 

Paul Doe is regular Manager of the Academia Franekerensis and Unit Manager of the University of Harderwijk. He can create CO's with units in Academia Franekerensis correctly.

Now remove the Units from Harderwijk and add a Unit to Franeker, and make Paul Doe Unit Manager in Franeker. Now Paul Doe can no longer select a Unit in the pull down in the Create CO screen when he selects Franeker as Org.

**Comment by baszoetekouw** [comment]
Probably something to do with the (database) ordering of the Orgs.

**Comment by baszoetekouw** [comment]
Doesn't work correctly yet.

To reproduce
 - In Test, from the default seed, add two units to Franeker.
 - Impersonate Paul Doe
 - Create new CO in Franeker
 - Paul cannot select anything in "Relevant units"
