### ISSUE TITLE
override_access_allowed_all_connections not always cleared correctly when selecting "only some orgs" for service 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1167]
We encountered the following issue:
- Service X was enable for Org A ("access for some orgs", "automatic connection allowed")
- However, CO's from Org A could not connect (not in list "available services" and 400 error when trying to connect via the API)
- database showed that `override_access_allowed_all_connections` was set to 1 for this service, even though in the UI, this was not visible

To reproduce (on test):
 - go to service wireless
 - set access rules to 1/Everyone 2/None
 - database shows: 
```json
{
"select entity_id, automatic_connection_allowed ,  access_allowed_for_all, non_member_users_access_allowed, override_access_allowed_all_connections from services s where s.entity_id like '%wireless'": [
	{
		"entity_id" : "https://wireless",
		"automatic_connection_allowed" : 0,
		"access_allowed_for_all" : 0,
		"non_member_users_access_allowed" : 1,
		"override_access_allowed_all_connections" : 1
	}
]}
```
  - switch access rule 1 from "Everyone" to "Connected collaborations"
  - database shows:
```json
{
"select entity_id, automatic_connection_allowed ,  access_allowed_for_all, non_member_users_access_allowed, override_access_allowed_all_connections from services s where s.entity_id like '%wireless'": [
	{
		"entity_id" : "https://wireless",
		"automatic_connection_allowed" : 0,
		"access_allowed_for_all" : 0,
		"non_member_users_access_allowed" : 0,
		"override_access_allowed_all_connections" : 1
	}
]}
```
  - Select 3/Yes, and in the table, switch Harderwijk to "Always":
  - Go to CO "AI computing" to see that COs from Harderwijk cannot connect.

So it seems that once `override_access_allowed_all_connections` is set, only a change in row 2 ("Collaborations from which organisations may connect") can clear the flag; if the setting in row 2 is changed implicitly because of a dependent change in row 1, the flag is not cleared.

**Comment by mrvanes** [comment]
Tested, looks good in interface and DB
