### ISSUE TITLE
tie invitation more closely to service user wants to reach

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1171]
feedback from Christine: users don't understand why they need to join a CO.  Include the names of the services that are used in the CO, in the invitation.

**Comment by FlorisFokkinga** [comment]
Looks like the role invite scenario.

**Comment by FlorisFokkinga** [comment]
https://gitlab.surf.nl/sram/ux/-/issues/29

**Comment by mrvanes** [comment]
Personal message is place in a different part of the mail for admin invitation, same for member invitation. Also, there is no "Personal message from [user]" introduction?

![Image](https://github.com/user-attachments/assets/ea7a17c9-310b-427e-9336-ffb5695c9fb0)

**Comment by oharsta** [comment]
The only difference between the old and new version is indeed the list of services displayed below the main call-to-action. The example was from the invite project and would require a complete overhaul of the current SRAM mails. I did not deem this as within scope (as we would have to change the other emails well for consistency). @FlorisFokkinga is this ok?

**Comment by FlorisFokkinga** [comment]
Ok for this issue.
