### ISSUE TITLE
Better translation for sram-support as TOTP escalation contact

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1181]
(followup for #991)

If no TOTP escalation contacts are available, the system falls back to sram-support.  The screen looks like this:

![Screenshot 2024-01-15 at 17 29 27](https://github.com/SURFscz/SBS/assets/1461740/a3176245-7ab6-4f05-a4f0-18560f587553)

The heading "admin" as well as the text "SRAM support" are not translatable in the client but rather are hardcoded in the API in  https://github.com/SURFscz/SBS/blob/5eb3ffdec194dfa2ebc5ff347d8f4c6f4733b67e/server/auth/mfa.py#L91

Would it be possible to add translation support here?

**Comment by baszoetekouw** [comment]
@FlorisFokkinga do you have suggestions for what the text should be (for dutch and english)?

**Comment by FlorisFokkinga** [comment]
- Admin: empty
- SRAM support: SRAM support (both NL and EN)
