### ISSUE TITLE
Remove ssid-support

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1183]
So only idp-based MFA and fallback-TOTP should remain.

**Comment by oharsta** [comment]
Once https://github.com/SURFscz/SBS/tree/feature/refactor-login-process-883 is merged into main, this will also resolve this issue.

**Comment by oharsta** [comment]
The branch https://github.com/SURFscz/SBS/tree/feature/refactor-login-process-883 is merged. All SSID-related code is removed from the codebase.
