### ISSUE TITLE
Remove the blue double 2FA info section

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1190]
2FA has been mandatory for a few months now.
![Image](https://github.com/SURFscz/SBS/assets/80269262/efa60502-91c7-43f2-9b44-8383ad104398)

**Comment by baszoetekouw** [comment]
Is gone

![Image](https://github.com/SURFscz/SBS/assets/1461740/638d6b6d-fc49-4814-9abc-2ce0595eb68c)
