### ISSUE TITLE
Improve the request/create collaboration form

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1194]
Assume the user has little experience with IT systems and doesn't understand what an SRAM collaboration is
- Collaboration purpose (project description)
	- Can be seen by members as a description (on the about tab)
- Motivation (sent to org admin, will not be shown to members)

---

Start by reordering the items in the form. Then I'll edit the labels, help text and placeholders:

1. Responsible organisation
1. Name
2. Short name
3. Platform identifier r/o
4. Collaboration purpose
5. Website URL
7. Relevant units (e.g. department or project)
8. Labels
9. Expiration date
10. Allow join requests
11. Disclose member information
12. Disclose email information
13. Invitees
14. Make me admin of this collaboration

- Only show 'make me admin of this collaboration' to org managers and up.
- Remove the 'Motivation' field.

**Comment by FlorisFokkinga** [comment]
How often is this used, and in what use cases? Doesn't the institution usually have a procedure to provide a researcher with a collaboration?

**Comment by baszoetekouw** [comment]
Replace "motivation" by "comment to admin" and make explciit who the admin is (name+email)

**Comment by FlorisFokkinga** [comment]
Reorder items in the form:
1. Name
2. Short name
3. Platform identifier r/o
4. Collaboration purpose
5. Website URL
6. Responsible organisation
7. Relevant units (e.g. department or project)
8. Labels
9. Expiration date
10. Allow join requests
11. Disclose member information
12. Disclose email information
13. Invitees
14. Make me admin of this collaboration
15. Message / Motivation

- Only show 'make me admin of this collaboration' to org managers and up.
- Make 'Motivation' an optional field.

**Comment by mrvanes** [comment]
This is fixed for the org managers/admins that request a collaboration. The for for users that can request collaborations based on organisational domain looks quite different? 8-13 are missing?
![Image](https://github.com/user-attachments/assets/f75a75ab-7c3d-443e-86a1-45ca70f26470)

**Comment by FlorisFokkinga** [comment]
It is identical to current production version, except for the greyed out 'make me admin'.

<img width="896" alt="image" src="https://github.com/user-attachments/assets/70ab5724-ff44-4e16-b630-940c4e38d2c5">

**Comment by FlorisFokkinga** [comment]
> 8-13 are missing?
That's right, thanks for asking. A normal user doesn't have permission to change these properties.
