### ISSUE TITLE
Tweaks to audit logs visibility

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1203]
Continued from #1124 

- [x] Show group membership changes in the CO history
- [x] Show group membership changes in the User Profile history
- [x] Rename group membership changes from "New/Deleted Collaboration Membership" to "New/Deteled Group Membership"
- [x] Show the name if the group in the changelog

Example of current log (under groups):
![Screenshot 2024-01-23 at 12 53 42](https://github.com/SURFscz/SBS/assets/1461740/24006882-8b0c-464f-b94f-dfcea2e8dab5)

**Comment by mrvanes** [comment]
Tested ok
