### ISSUE TITLE
Make clear in the org edit form what #1081 does, that it is only shown to users outside of the organisation.

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1228]
https://github.com/SURFscz/SBS/issues/1081 is goedgekeurd, maar Floris voegt daar aan toe:

> I think we need to make clear in the org edit form what this does, that it is only shown to users outside of the organisation.

**Comment by oharsta** [comment]
@FlorisFokkinga There is a placeholder and tooltip that you change (see https://github.com/SURFscz/SBS/issues/1228). Will that suffice?
