### ISSUE TITLE
User with only CO requests or join requests or service requests has no button to request a CO

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1257]
Instead of the single 'my requests' tab, show the landing page for a user without any memberships and requests, and add the [view requests](https://test.sram.surf.nl/collaborations-overview#) link next to the button, just as it would be at the friendly landing page (the one with the tree).
If the user cannot create/request a CO, place a primary button 'View requests'.

**Comment by mrvanes** [comment]
OK
