### ISSUE TITLE
On the 'connected collaborations' tab, a service admin should not be presented links for COs they don't have access to

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1261]
The tab: https://sram.surf.nl/services/###/collaborations

**Comment by oharsta** [comment]
@FlorisFokkinga  The name of the Co is only a link if the current user has access to the CO. Please reproduce on test.

**Comment by FlorisFokkinga** [comment]
Cannot reproduce, nor find the original bug report.
