### ISSUE TITLE
Specification of units in Org API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1264]
In the Org API, units are currently expressed as:
```json
{
  " units": [
    {
      "name": "research",
      "id": 0
    },{
      "name": "development",
      "id": 1
    }
  ]
}
```
That is too verbose and exposes internal ids where it isn't necessary.
The output is even more verbose:
```json
{
      "units": [
        {
          "id": 67,
          "name": "Support",
          "organisation_id": 324
        }
      ]
}
```
Note that also the `organisation_id` is superfluous here, as a CO can only belong to a single Org, so there can be no confusion.

Please replace this (both input and output) by a simple array of unit names, like this:
```json
{
  "units": [ "research", "development" ]
}
```

Input is used in 
- POST `/api/collaborations/v1`

Output is used in 
- POST/GET `/api/collaborations/v1`
- GET `/api/organisations/v1`

**Comment by mrvanes** [comment]
api/collaborations/v1/{co_id} does not contain the units of the parent organization:
```
 "units": [],
```
api/organisations/v1 still contains the verbose units:
```
  "units": [
    {
      "id": 3,
      "name": "unit1",
      "organisation_id": 2
    },
    {
      "id": 4,
      "name": "unit2",
      "organisation_id": 2
    }
  ],
```

api/plsc/sync correctly contains the bare units per organization:
```
      "units": [
        "Research",
        "Support"
      ]
```
Tested on SBS `fbd7de7b985b27fa6c3b0c9bbf66b57559c84942  Mon Mar 11 15:28:37 2024 +0100`

**Comment by baszoetekouw** [comment]
Is now correct:
```
╰─▶ curl  -s  --header "Authorization: Bearer ADvm-qSpXx686K_C3qovSpxSp34KSqK1mL50BcLBR8oE" --header "accept: application/json"      --request GET     "https://test.sram.surf.nl/api/collaborations/v1/da706611-0afb-4a7a-819b-b0a9c63e9b67"|jq '.tags'
[
  "voorbeeld",
  "tag_ufra"
]
```

**Comment by baszoetekouw** [comment]
Gelukkig zijn de units ook goed ;)

```
  "tags": [
    "tag_uuc",
    "tag_bla"
  ],
  "units": [
    "Support"
  ],
```
