### ISSUE TITLE
Express Org Units in OIDC/SAML attributes?

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1266]
Is it useful/necessary to expose Org Units in OIDC/SAML attributes? On the one hand, this info that is internal for Orgs, and should maybe not be exposed; on the other hands, it might be useful for Services to do authorization or accounting.

And if we want to expose the units, how should we do that?  We could express them in the CO entitltments like:
```
urn:mace:surf.nl:sram:unit:<orgname>:<coname>:<unitname1>
urn:mace:surf.nl:sram:unit:<orgname>:<coname>:<unitname2>
```
(which matches the expression of labels).

Or perhaps
```
urn:mace:surf.nl:sram:unit:<orgname>:<coname>:<unitname1>,<unitname2>
```

Or
```
urn:mace:surf.nl:sram:unit:<orgname>::<unitname1>:<coname>
```
to express the hierarchical ordering.

**Comment by mrvanes** [comment]
What's the requirement here?

**Comment by FlorisFokkinga** [comment]
Fundamental question: do we want to expose units to services at all?

**Comment by baszoetekouw** [comment]
Units were designed to allow Organisations to manage their internal structure.  The units are hardly exposed to regular users in the UI, so it probably doesn't make sense to allow Services to use this information.
