### ISSUE TITLE
Automatically remind users to accept outstanding invitations

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1275]
Quite often people forget to accept an invitation, or leave the invitation rotting in their inbox.  Therefore, it would be nice if we can periodically remind them.

**Comment by oharsta** [comment]
@FlorisFokkinga I have re-used the mail templates for sending invitations for collaborations, organisations and services. See https://github.com/SURFscz/SBS/blob/main/server/templates/collaboration_invitation.html, https://github.com/SURFscz/SBS/blob/main/server/templates/service_invitation.html and https://github.com/SURFscz/SBS/blob/main/server/templates/organisation_invitation.html. There are different sections for reminder mails and regular mails. You can easily introduce more reminder differentiations. A reminder mail has the same subject as a regular mail, but prepended with "Reminder: ".
