### ISSUE TITLE
Collaboration tab and table is doubled

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1277]
Occurs for organisation admins, does not occur for platform admins.

![avIzGIZ5hpmeE840](https://github.com/SURFscz/SBS/assets/80269262/2f5cf863-b2bc-407c-9d3d-8718a13543fe)

<img width="1495" alt="Screenshot 2024-03-04 at 10 45 00" src="https://github.com/SURFscz/SBS/assets/80269262/eee0512f-926d-4e87-9841-b28040afcf41">

**Comment by FlorisFokkinga** [comment]
The commit fixes the occurence for a service admin that is also an organisation admin.

**Comment by mrvanes** [comment]
Tested, ok
