### ISSUE TITLE
No errors logged when token decryption fails

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1296]
When token decryption fails (for example during a SCIM sweep), this is reported as a user-error to the client.  Instead, it should be a high-prio application error that should be mailed to sram-beheer.  The client should receive a 500 Internal Server Error.

Probably this exception https://github.com/SURFscz/SBS/blob/main/server/auth/secrets.py#L60 should be something different than a BadReqeust().

**Comment by oharsta** [comment]
`BadRequest` exceptions are mailed, but in the case of a sweep we catch all exceptions (see https://github.com/SURFscz/SBS/commit/9b41f475a2da1885baf433c5881b147713dfd508) so no mail was send.

**Comment by baszoetekouw** [comment]
But, but added more logging in https://github.com/SURFscz/SBS/commit/7507ec0e7205070bfef1b2853a4746f14a2b52be
