### ISSUE TITLE
Verbeteren flow bij accepteren van uitnodiging van CO waar je al lid van bent

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1303]
Als je een uitnodiging krijgt van een CO waar je al lid van bent, is dat niet direct duidelijk: je moet eerst nog de AUPs opniuew accepteren.  Beter zou zijn om direct naar het CO-scherm te gaan met de meldingsbalk "je bent al lid".

Ik twijfel ook of deze balk wel de goede boodschap geeft:
![Screenshot 2024-03-18 at 11 28 17](https://github.com/SURFscz/SBS/assets/1461740/dfc39b24-05c6-487d-b541-52228d6c23b9)
Misschien is ipv een rode error-balk een blauwe info-balk beter met als tekst iets van "You are already a member of this CO and do not need to accept a new invitation".

**Comment by mrvanes** [comment]
@FlorisFokkinga komt die in de buurt van de verwachtingen?
![Image](https://github.com/SURFscz/SBS/assets/1901782/8eeb43a5-1791-45a4-a7b8-85b7ac9bf6d3)

**Comment by FlorisFokkinga** [comment]
@mrvanes Ja, en hoe ziet de balk onder de header er nu uit?

**Comment by oharsta** [comment]
Die is weg. Leek me niet meer nodig.
<img width="1488" alt="image" src="https://github.com/SURFscz/SBS/assets/530657/0305c5d4-0bf1-45e8-ad69-5600bafed56c">
