### ISSUE TITLE
Wrong mime-type for attaching images.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1310]
followup for #707:

It turns out that SBS sends out mail with the wrong MIME-type, which causes the attached images (for example, in a CO invitation) not to be displayed in some mail clients.

Specifically, SBS sends mails with 
```
Content-Type: multipart/mixed
```
Instead, it should be
```
Content-Type: multipart/related
```
This might be a bug in the upstream flask-mailk package

On a sidenote, the flask-mail package seems unmaintained.  We might want to switch to (for example) https://github.com/waynerv/flask-mailman/tree/master/flask_mailman which seems to be able to support changing the mime-types: https://github.com/waynerv/flask-mailman/blob/master/flask_mailman/message.py#L182

**Comment by oharsta** [comment]
Migrated to flask_mailman and with the use of https://github.com/SURFscz/SBS/blob/main/server/mail.py#L31 we are backwards compatible in the tests

**Comment by mrvanes** [comment]
OK
```
Return-Path: <no-reply@localhost>
Received: from f3a706e92c71 (docker-docker1-1.docker_scznet. [172.20.1.32])
        by mail (Mailpit) with SMTP
        for <me@example.com>; Fri,  5 Apr 2024 14:04:10 +0000 (UTC)
Content-Type: multipart/related;
 boundary="===============4093742317137807820=="
MIME-Version: 1.0
Subject: Invitation to join collaboration AI computing (wsgi)
From: SURF <no-reply@localhost>
To: me@example.com
Date: Fri, 05 Apr 2024 14:04:10 -0000
Auto-submitted: auto-generated
X-Auto-Response-Suppress: yes
Precedence: bulk
message-id: 
 <de407ea3.9145.44fa.a1a7.d5fa03102b95@f3a706e92c71.internal.sram.surf.nl>
```
