### ISSUE TITLE
Service access rules screen switches to mobile view to quickly

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1311]
The Service accces screen is too narrow.  Even if the buttons easily fit next to each other, they are still wrapped:

This just fits:
![Screenshot 2024-03-20 at 10 02 41](https://github.com/SURFscz/SBS/assets/1461740/0d28a7d2-ae08-4cee-99b4-9ef41d3c00c1)

This doesn't:
![Screenshot 2024-03-20 at 10 02 53](https://github.com/SURFscz/SBS/assets/1461740/d5066e71-7eb8-4bd6-806d-5d4849360097)

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFnet/sds/commit/b27b1f589e7d30d5ee19e92245642dbc55768ec6

**Comment by mrvanes** [comment]
OK
