### ISSUE TITLE
Clicking on the Service Name of a Service Group as a CO admin leads to a 404

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1316]
Clicking here:

![Screenshot 2024-03-20 at 13 13 34](https://github.com/SURFscz/SBS/assets/1461740/6bb18e11-e648-4d2e-a912-d66856626781)

Leads the user to https://acc.sram.surf.nl/404 (if they don't have access to view the service, probably).

**Comment by baszoetekouw** [comment]
Gewenste gedrag: dit moet geen linkje zijn als je geen toegang hebt.

**Comment by mrvanes** [comment]
The service name should _not_ be hidden. It should be not-clickable.

![Image](https://github.com/SURFscz/SBS/assets/1901782/51fe713b-4569-4267-9c07-20ba32476953)

**Comment by mrvanes** [comment]
OK
