### ISSUE TITLE
As an Org/CO/Service admin, I want to be reminded of open requests

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1319]
Send weekly overview of open requests to admins of COs, Orgs and Services.

It is probably best to not send more than 1 mail per person.  If necessary, we could send one per per person per role (so if a person is Service admin and Org admin, they could get 2 mails), but don't send mails for each separate CO (because some users are admin of >100 COs).

**Comment by oharsta** [comment]
Can also be tested by the system/cron functionality for platform_admins. Only one mail is send to each recipient with all the requests grouped by type of request.

**Comment by mrvanes** [comment]
OK
