### ISSUE TITLE
include (some) account details in user suspension mail for more context for the reader and for easier debugging

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1320]
Cuirrent mail:
![Image](https://github.com/SURFscz/SBS/assets/1461740/b903c5e3-3e05-4297-b4c4-39ab1408ec7e)

probably doesn't give enough context for people who only use SRAM to get access to services and have no idea what SRAM is.

so add:
 - personal information: registered name, email, affiliation
 - which COs is user member of
 - which Services the user has access to

**Comment by mrvanes** [comment]
Er gaat nog iets niet helemaal goed bij de enumeration van affiliations:

![Image](https://github.com/SURFscz/SBS/assets/1901782/e34c1586-c129-4524-a7bb-a24f2c04b4e2)

**Comment by mrvanes** [comment]
OK
