### ISSUE TITLE
Show a modal when a user tries to accept an already accepted invitation

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1345]
https://github.com/SURFscz/SBS/issues/1314 was accepted as it handles the 404 better.
But what should this page actually look like?

**Comment by oharsta** [comment]
@FlorisFokkinga This is a bigger story than you think as we delete invitations on accept. We can change this, but this has impact in many parts of the code (and functionality). Github (and many other large sites) also display a 404 when you try to access an already accepted invitation. And we do have a custom message for the 404 is the user tried to go to an invitation page. Assign the story back to me if you think it is worth the effort.

**Comment by FlorisFokkinga** [comment]
Let's not do this then.

**Comment by FlorisFokkinga** [comment]
Thanks, Github. I give up.

**Comment by FlorisFokkinga** [comment]
I misread. Sorry for the spam.

Let's simply inform the user the invitation was already used (which is a safe assumption) if it doesn't exist. A modal seems an elegant solution.

**Comment by oharsta** [comment]
Duplicated by https://github.com/SURFscz/SBS/issues/1263
