### ISSUE TITLE
On creating/editing a collaboration, selecting an existing label (tag) saves the contents without labels, and without redirecting the page

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1359]
## Reproduction on TEST
- Create a CO https://test.sram.surf.nl/new-collaboration?organisationId=355
- Enter name, short name, purpose and a logo
- Select an existing label (e.g., 'label_01')
- Submit the form

### Expected
- Redirect to CO list
- CO saved with label

### Observed
- Form reloads
- CO saved without the label

**Comment by oharsta** [comment]
The server responded with a 500:
```
{"error":true,"message":"Circular reference detected"}
```

**Comment by baszoetekouw** [comment]
On test, existing labels are no longer shown in the "labels" dropdown when creating a new CO.

**Comment by oharsta** [comment]
Can not reproduce on test. See screenshot

![Image](https://github.com/SURFscz/SBS/assets/530657/3c44c40d-33f8-4ead-a4da-20ebf90bbf1b)

**Comment by oharsta** [comment]
When you create a new CO from the main CO tab (as platform-admin), it is possible that an ORG is chosen without label. But when you chose an ORG with labels, there also shown from this form

![Image](https://github.com/SURFscz/SBS/assets/530657/a8ee22f5-d120-4b85-b0e0-ed62a496221e)

**Comment by baszoetekouw** [comment]
works
