### ISSUE TITLE
As an organisation admin, I don't want suggestions for unused labels that were previously assigned to deleted collaborations

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1386]

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/fc52e51a405e421ab0d765759cb25e034068e21b

**Comment by HarryKodden** [comment]
Test Ok, steps taken:

* Added CO Label 'harry' to existing CO
* Deleted the CO
* Created new CO
* In field 'Labels' a suggestion list shows up with only labels of CO's that still exiss,
* label 'harry' does not show up, which is OK !
