### ISSUE TITLE
Add service is not possible

### ISSUE THREAD

**Issue by maxstaubach** [SURFscz/SBS#1388]
Hello,
I am currently evaluating your application and have set it up in docker. Branch "Fix-docker-compose.yml" rebased with main.

Now I can create organizations and collaborations via webui but no services.
I fill in all the fields as requested but neither an error is displayed nor is the service created.

There is also nothing in the log. Only "INFO:base:user: urn:john, Path /api/services/hint_short_name POST {"name": "service1"}".

I would be happy to provide more information.

My goal is to test "pam-weblogin" and publish the technical details in a service review.

Best regards
Maximilian

**Comment by baszoetekouw** [comment]
Hi Max!
Good to hear that you have at least gotten SBS to work in general.  The issue you're describing is pretty strange though; it sounds like a backend call fails, but should be able to see that in the logs.  

Which logs are you looking at exactly?  The docker-compose branch is not entirely stable, I think, so it might be that some of the logs end up at the wrong place.  You should get all the logs with `docker-compose logs server`, but they might also end up in the docker container in `/opt/server/logs` or so...  At the very least you should see something like this when the container starts:
```
[2024-05-16 14:46:51 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2024-05-16 14:46:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2024-05-16 14:46:51 +0000] [1] [INFO] Using worker: eventlet
[2024-05-16 14:46:51 +0000] [1026] [INFO] Booting worker with pid: 1026
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [apscheduler.scheduler] Adding job tentatively -- it will be properly scheduled when the scheduler starts
```

**Comment by maxstaubach** [comment]
Hi Bas,

Attached you will find the logs.
The directory /opt/server/logs does not exist.

I can also send you my compose file with the configuration by e-mail.

[dockerdesktopclient.log](https://github.com/SURFscz/SBS/files/15387088/dockerdesktopclient.log)
[dockerdesktopserver.log](https://github.com/SURFscz/SBS/files/15387089/dockerdesktopserver.log)

**Comment by baszoetekouw** [comment]
Sorry Max, this ticket was drowning at the bottom of my mailbox...
I think I made a mistake in my earlier message; the logs should be in `/opt/logs` inside the container.  Could you check if they are there?  

I've also just merged fixed to the docker-compose in main.  Could you perhaps try if the main branch does work?

**Comment by maxstaubach** [comment]
Hi,
I have tried it again with the latest version and now no error occurs anymore. 
My test was successful. Thank you very much!
