### ISSUE TITLE
At service history, a connected collaboration is filtered by properties, not connections on TEST

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1389]
![image](https://github.com/SURFscz/SBS/assets/80269262/2745551c-8242-455f-8f3e-47b4836052a9)

**Comment by HarryKodden** [comment]
Works !



![Image](https://github.com/SURFscz/SBS/assets/1842889/95479727-0c28-41e8-a753-ee17cf315c18)
