### ISSUE TITLE
Update the text in the service admin invite emails

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#139]
De CO tekst is hergebruikt met `collaboration` vervangen door `service`. Ik denk dat we een wat specifiekere tekst moeten verzinnen.

**Comment by FlorisFokkinga** [comment]
I believe that collaboration and service are variables in the email template. A new template is needed.

**Comment by oharsta** [comment]
The service invitation mail has been a separate template from the beginning. See https://github.com/SURFscz/SBS/blob/main/server/templates/service_invitation.html

@FlorisFokkinga You actually edit this file, see https://github.com/SURFscz/SBS/commit/27113bcdadf4dad01c8d41361abeb836f91b8e7e#diff-ddf1862287e6096b620ed4b68d60bd8da23e29a493ca0bf04d15db04b977ecde

**Comment by FlorisFokkinga** [comment]
https://github.com/SURFscz/SBS/commit/f35fde79f8c867d69c3e5f658fcea84e6f9ebd14
