### ISSUE TITLE
Als organisatiebeheerder/-manager van een restricted organisation wil ik kunnen zien welke diensten er verplicht zijn voor mijn organisatie

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#141]
Het gaat om het tonen van de situatie, niet om het wijzigen.
We kunnen geen reden bedenken om deze informatie niet (duidelijk) te tonen. Ik zou zo snel echter geen mooie oplossing kunnen bedenken om te tonen of een toegestane dienst verplicht is of niet. Greyed out maakt duidelijk dat deze gebruiker ze niet kan aanpassen, maar andere gebruikers mogelijk wel. Daaraan is echter niet heel duidelijk te zien welke er uit staat en welke aan.

Er zijn dus drie toestanden voor een gebruiker die niet mag wijzigen:
1.     Staat aan
2.     Staat uit, maar kan aangezet worden
3.     Kan niet aangezet worden.

Een mogelijke oplossing is voor de diensten die aanstaan de toggle naar rechts en grijs weer te geven, en voor de andere twee situaties een tooltip weer te geven met 'staat uit, zou aan kunnen' en 'mag niet worden aangezet'.
![Pasted Image at 2021_12_27_09_22 am](https://user-images.githubusercontent.com/80269262/160642303-7e7481ea-f6a0-474e-a3eb-7ae27feab3d2.png)

**Comment by baszoetekouw** [comment]
Is al opgelost op test.  De derde status is vervangen door een hoover.

**Comment by baszoetekouw** [comment]
Zie wel #314 voor een relateerd issue.
