### ISSUE TITLE
Error when service manager tries to remove themselve from service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1410]
https://github.com/SURFscz/SBS/assets/1461740/782984d6-a273-40d3-b2ee-b9feff06d86a

- Allow service admins and managers to remove themselves from the service.

Removing yourself is consistent with other admin roles and the invitation concept. For organisation, we have blocked removing the last admin.

**Comment by HarryKodden** [comment]
Test Ok !
