### ISSUE TITLE
Improve column alignment within AUP-dialog

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1414]
![Screenshot 2024-05-14 at 10 19 31](https://github.com/SURFscz/SBS/assets/1461740/3367ada2-467b-402c-b18d-35630fba745f)

**Comment by oharsta** [comment]
Small improvement made:
<img width="1358" alt="image" src="https://github.com/SURFscz/SBS/assets/530657/adc1d168-4251-4b2d-9f0b-9bf65456aacf">

**Comment by FlorisFokkinga** [comment]
Looks good.

**Comment by logan-life** [comment]
@oharsta @baszoetekouw  it looks like this has been released. can this ticket be moved to **Done**?

**Comment by mrvanes** [comment]
Checked
