### ISSUE TITLE
Add more details to PAM Web SSO Challenge Response

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#1416]
At this moment the PAM Weblogin / WebSSO Challenge Response (endpoint '/start') provides JSON response for a **non-cached session** like this:
- cached: false
- challenge: "Please sign in to: https://\<sram-url\>/weblogin/\<service\>/\<session_id\>\\n\<ascii QRODE\>"
- result: "OK"
- session_id: \<session_id\>

We would like to have some additional details added to this response:
- url: "https://\<sram-url\>/weblogin/\<service\>/\<session_id\>"
- qrcode_png: Base64 encoded PNG image of the \<url\>
- qrcode_ascii: \<ascii QRCODE\>

For backwards compatibility, the current challenge attribute may be kept as is.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/pull/1422
