### ISSUE TITLE
As a user suspended for inactivity, I just want a login to the UI to revert my suspension

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1427]
As the suspension email says:

>  If you want to keep using the services available through SURF Research Access Management, simply login using the link below or by going to https://sram.surf.nl/login. 

Probleem is dat die suspension nu ook gebruikt wordt voor gebruikers die echt niet moeten kunnen inloggen (omdat ze TOTP te vaak fout hebben gedaan).  Dat zouden we dan moeten omzetten in een andere vorm van suspension.

Do not change the behaviour for suspension for TOTP.

Related to
- #1402

**Comment by mrvanes** [comment]
Checked
