### ISSUE TITLE
Remove user_ip_networks

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1429]
From code and database.

**Comment by mrvanes** [comment]
Only migrations that contain user_ip_networks, which is to be expected. OK!

$ search user_ip_networks
./migrations/versions/cf89d41f30fe_remove_user_ip_networks.py:1:"""Remove user_ip_networks
./migrations/versions/cf89d41f30fe_remove_user_ip_networks.py:18:    op.drop_table("user_ip_networks")
./migrations/versions/cd11385cdc16_user_ip_networks.py:19:    op.create_table("user_ip_networks",
