### ISSUE TITLE
Remove existing 'last_activity_date' entries from the user history

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1430]
This is not trivial to remove from the database.  It's probably easier to filter them in the backend or hide them in the frontend.

**Comment by oharsta** [comment]
We don't want a migration as the query will run for a long time. Running the query won't lock the table.
```
DELETE FROM audit_logs WHERE state_after REGEXP '^\\{"last_activity_date":[0123456789.]{10}\\}' AND target_type = 'collaborations';
```

**Comment by baszoetekouw** [comment]
Done.  202868 rows deleted.

**Comment by mrvanes** [comment]
Could not find any reference to last login activities in acc
