### ISSUE TITLE
Sorting of CO members on name/email doesn't show sorting indicator arrow in table heading

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1431]

**Comment by HarryKodden** [comment]
Tested OK

**Comment by mrvanes** [comment]
Membership column doesn't have a sorting indicator?

**Comment by oharsta** [comment]
Added sorting indicator. Some columns are not sortable, discussed with Bas and decided to not sort some columns (and not show the pointer cursor and not do anything when clicked by the user).

**Comment by baszoetekouw** [comment]
works
