### ISSUE TITLE
PAM: Add a 'logged in' page after entering the verification code

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1445]
## Verifcation code page
- Update the text on the current page
- Change the copy icon into a copy button (without the icon?)

![Image](https://github.com/SURFscz/SBS/assets/80269262/29ee1048-133a-45a8-8646-987e92a8509d)

## New 'done' page
- Redirect to this page
  - after the verfication code has been entered on the terminal
  - if the verification code isn't valid 

![Image](https://github.com/SURFscz/SBS/assets/80269262/1c281482-a5cb-4a20-a764-4d6953df3344)

**Comment by mrvanes** [comment]
OK
