### ISSUE TITLE
SCIM server/client terminology

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1446]
Consider changing the SCIM terminology:

- "SCIM server" --> "SCIM push" (i.e., SRAM pushes updates to remote server)
- "SCIM client" --> "SCIM pull" (i.e., client fetches updates at SRAM)

**Comment by FlorisFokkinga** [comment]
Decided on:
- SCIM push to service
- SCIM pull by service

**Comment by mrvanes** [comment]
Ok
