### ISSUE TITLE
Protect SCIM resource endpoints 

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#1457]
at this moment the SCIM endpoints: **https://sram.surf.nl/api/scim/v2/Users/\<sram identifier\>** and
**https://sram.surf.nl/api/scim/v2/Groups/\<sram identifier\>**
are publicly accessible.

Although the SRAM Identifiers are not easy guessable, we would like these endpoints protected

**Comment by baszoetekouw** [comment]
works
