### ISSUE TITLE
Add an optional 'User support contact' address to collaborations

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1489]
Just like for a service.

![Image](https://github.com/SURFscz/SBS/assets/80269262/5ada7900-09b4-423c-90d2-01b4740febed)

If it has a value, email address or URL, display it on the collaboration's about tab, instead of the collaboration adminstrators' email addresses.

![Image](https://github.com/SURFscz/SBS/assets/80269262/9f0351e2-79e1-459e-bb01-4b6d7eb8063c)

**Comment by mrvanes** [comment]
Works like a charm, but the check can be fooled with. Don't bother fixing!
foobar+test@email.com.http://test/com
