### ISSUE TITLE
As a user unauthorized to log in to an application, I want the application admin to help me getting access

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1500]
From the perspective of the platform, there are many ways for a user to become member of a collaboration that grants them access to an application. The current page takes a few guesses and fails at giving the users concrete steps to resolve the issue.

In some cases, e.g., djeHuty and Health-RI, the application admin wants to help users get access. Let's give them the option to do so.

## Current page for an unauthorized user

![Image](https://github.com/SURFscz/SBS/assets/80269262/089b1145-d5d4-428e-af76-1a8837ba1862)

## Design

<img width="1187" alt="github_1500_no_access_screen" src="https://github.com/user-attachments/assets/1f65d514-644f-4f09-ac7e-6343fed71b45">

## Optional lines
1. The user can request/create a collaboration at their organisation, and the application is available for that organisation. Instruct the user to do this themself.
2. The application admin has enabled support for getting access. Then show the support link and optional text message.

- If the field is a URL, then just go to the URL. 
- If the field is an email address, then the button is a `mailto` link
```
Hi,

Please help me get access to the <application name> application.
Name: <name>
Email: <email>
Organisation: <organisation name/domain>
Reason:

Thanks!
```
### Text

```
Invitations and accounts

Access to Demo application is granted by membership of a collaboration.

    Have you been invited? Use the link in the email.
    You are logged in via eduid.nl. Do you perhaps have acccess via a different account?

Gaining access

    If someone pointed you to Demo application, ask them for help.
    You can [create/request] a collaboration via eduid.nl and connect the application.
    You can [contact] the application admin, they can help you.

Get support

If you have tried the solutions above, or think you should have access already, you can contact SRAM support at [sram-support@surf.nl] for help.

Make sure to include the information below.
```

## Application admin
Give the application admin the option to display the support address (e-mail, URL or invite link) to unauthorized users.
```
Show to unauthorized users
ℹ This email address or URL will be shown to users when they try to log in to your application without authorization, typically because the have no membership of a connected collaboration.
Toon aan ongeautoriseerde gebruikers
ℹ Dit e-mailadres of de URL wordt getoond aan gebruikers wanneer ze proberen in te loggen op de applicatie maar ongeautoriseerd zijn, doorgaans doordat ze niet lid zijn van een gekoppelde samenwerking.
```

![Image](https://github.com/SURFscz/SBS/assets/80269262/5ee0161a-d50f-4d24-8215-ffbd228c854b)

Add fixed email template with subject 'access to application so and so'.

**Comment by logan-life** [comment]
The helpdesk link provided by the application admin can already provide an email address or a URL (for e.g. a ticketing system) so we would add the checkbox to allow them to choose to display the email or link to the unauthorized end user.

If this is enabled, we should display this option (among the options already provided to try and guide the user) very prominently.

We can make it a nice big button. 

- If the field is a URL, then just go to the URL. 
- If the field is an email address, then a `mailto` link can be added. 
- If we want to be extra helpful for the user, we can consider creating an email template that is called with the `mailto` link and automatically populates the body of the email with some helpful variables filled in where appropriate.

**Comment by mrvanes** [comment]
The request access mail contains this body (test.sram.surf.nl, surfstar-idp.lab.surf.nl IdP).
```
Hi,

Please help me get access to the SRAM Demo RP} application.
Name: [missing "{{userName}}" value]
Email: martin.vanes@surf.nl
Organisation: surfstar-idp.lab.surf.nl
Reason:

Thanks!
```

I'm not sure why userName is missing? My username on test is mvanes (Generated by SRAM).
Apart from that, everything seems to work fine!

**Comment by oharsta** [comment]
Fixes made in https://github.com/SURFscz/SBS/commit/ba7514bf64ef15a5e36febf4e99a571da7e6167a to remove the bracket after the application name and resolved the type made in the variable user_name. The mail is now:
```
Hi,

Please help me get access to the Demo application.
Name: Paul Doe
Email: paul@ucc.org
Organisation: example.org
Reason:

Thanks!
```

**Comment by mrvanes** [comment]
Checked!
