### ISSUE TITLE
As a platform admin, I want redirect_urls in newly requested OIDC Services to be https (unless they point to localhost)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1501]

**Comment by mrvanes** [comment]
Shouldn't we include 127.0.0.0/8 as valid localhost targets as well?

![Image](https://github.com/user-attachments/assets/a355ee3d-1836-4810-97eb-c0075b624035)

**Comment by oharsta** [comment]
Good idea. Added `http:\/\/127\.(.*)` redirects to the reg exp.

**Comment by mrvanes** [comment]
Checked, works
