### ISSUE TITLE
As an organisation manager, I want to label CO's so our organisation's services can authorize and account groups of CO's

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#151]
### Context ###
- Deze feature is voor dienstenaanbieders van instellingen.
- Om (onder andere) onderzoekssamenwerkingen van meerdere instellingen te faciliteren willen ze SRAM inzetten.
- Ook anderssoortige groepen interne gebruikers moeten toegang krijgen via SRAM.
 - Deze use case verschilt daarmee van 'gasttoegang voor diensten met SURFconext', omdat daar vele gebruikers van een organisatie toegang hebben. In dit geval is het acceptabel om iedereen die toegang moet krijgen persoonlijk uit te nodigen.
- Om meerdere redenen willen ze echter één aanmeldoplossing per dienst.

### Omschrijving ###
- Een CO kan één of meerdere labels toegekend krijgen door een organisation manager (of hoger) van haar organisatie.
- De naam van een label mag vrij worden gekozen. Bij het invoeren wordt de organisation manager geholpen door een auto complete van reeds bestaande labels binnen de organisatie.
- Alle labels van een CO worden beschikbaar gesteld aan de CO gekoppelde diensten, via SAML, OIDC en LDAP.
- labels krijgen de scope van de organisatie mee: `organisation:label-name`.

### Ontwerp ###
Er bestaan nog geen labels in de GUI. Er zijn echter wel labelachtige invoerelementen:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/80269262/161261104-08fb0e9e-78ca-4046-a6f2-ee587d4ddb00.png">
En er zijn labels die worden weergegeven bij users:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/80269262/161261997-446e7cda-c699-4720-819b-ad6e60bb825d.png">

Labels zijn alleen zichtbaar voor organisation admin en hoger.

**Comment by FlorisFokkinga** [comment]
Discussed that @baszoetekouw will specifiy how to express tags in LDAP and SAML.

**Comment by oharsta** [comment]
Validation like short_name

**Comment by FlorisFokkinga** [comment]
Works. Output in LDAP not tested.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/80269262/167637880-be13f874-cbf1-4b1a-99e5-c084e82b5326.png">
