### ISSUE TITLE
SBS compose should use dev env for react

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1535]
The correct docker-compose/dockerfile uses a production build for the react components.  It would be nice if we could use a debug build there so that any changes you make to the code are reflected live.

This already works for the python components.

**Comment by mrvanes** [comment]
Even voor mijn begrip, wil je dan ongeveer hier
https://github.com/SURFscz/SBS/blob/main/.github/workflows/main.yml#L178
een tweede "dev build" ofzo?

daar dan hier
https://github.com/SURFscz/SBS/blob/main/.github/workflows/main.yml#L193
Een sbs-dev.tar.gz van maken?

En dan hier
https://github.com/SURFscz/SBS/blob/main/Dockerfile.sbs#L25
Die sbs-dev.tar.gz gebruiken in een Dockerfile.sbs-dev variant ofzo?

**Comment by baszoetekouw** [comment]
Nee, de docker compose doet zijn eigen yarn stuff, dus die gebruikt de standaard containers niet: https://github.com/SURFscz/SBS/blob/main/client/Dockerfile

In die `yarn build` stap maakt hij nu alleen een productie build (met minified js enzo).  Er is vast ook wel een manier om een dev build te maken (maar mischien kan @oharsta een een hint geven hoe, als hij terug is van vakantie).
