### ISSUE TITLE
User Last login date is updated on reverting suspension of their profile

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1544]
Page: https://sram.surf.nl/users/###

### Observed
- When reverting a suspension the 'Last login date' is updated

### Expected
- 'Last login date' is only updated after a succesful authentication

**Comment by oharsta** [comment]
@FlorisFokkinga The `last_login_date` is the date which is used to determine if a user will be suspended. We need to update this attribute to prevent the user being suspended again, after reverting the suspension. Consider it a feature.

**Comment by FlorisFokkinga** [comment]
Fixed by changing the text to 'last activity date'.

**Comment by mrvanes** [comment]
Checked
