### ISSUE TITLE
"Website" and "Login URL" field are automatically converted to lowercase, which causes problems for some services

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1545]
To reproduce: 
 - open the service details https://test.sram.surf.nl/services/990/details
 - change the website url and the login url to something with capitals 
 - press update
 - values will be lower case

This is an issue for (e.g.) Google Cloud, which is apparently case-sensitive in its url paths.

**Comment by mrvanes** [comment]
Checked
