### ISSUE TITLE
Invite link results in HTTP 404 on TEST

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#155]
For example: on https://test.sram.surf.nl/collaborations/465/admins this invite link is listed:
https://test.sram.surf.nl/registration?collaboration=efc25b72-e795-4456-8c69-59f07c0f0d0c

**Comment by oharsta** [comment]
@FlorisFokkinga If Bas can do a new deploy on test, then you can verify this works again.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw ?

**Comment by baszoetekouw** [comment]
Confirmed on test
