### ISSUE TITLE
TOTP reset doesn't show CO admins as option on TEST

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#156]
### Verwacht gedrag ###
Bij het vragen om een resetcode voor TOTP ziet de gebruiker (e-mailadressen van) de CO-admins als optie.

### Waargenomen gedrag ###
<img width="390" alt="image" src="https://user-images.githubusercontent.com/80269262/162425722-856389b4-eebb-4246-bd97-766424edb958.png">

### Gegevens ###
Op test.sram.surf.nl
Uid c46818640d83ec0355837ba66624b24a90ab619d@acc.sram.eduteams.org

**Comment by oharsta** [comment]
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/530657/163143155-14e83870-01ef-4f33-9b78-84777d63ca8b.png">

Locally is does work. I'll have a look on the test environment

**Comment by oharsta** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/530657/163143515-db8b42f9-8f21-4a86-860f-4b8cbf3d5fb4.png">
On test for admin of Mujina it also works. @FlorisFokkinga  Can you confirm that the user you have tried is a member of a collaboration that has administrators?

**Comment by FlorisFokkinga** [comment]
I cannot reproduce the problem.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/80269262/163413258-81ba8d2a-2a20-487f-87ef-8b3ddd414061.png">
