### ISSUE TITLE
As an organisation, I want to use the API to send invitations with the organisation name as the sender, instead of an organisation admin

### ISSUE THREAD

**Issue by logan-life** [SURFscz/SBS#1565]
Astron = requesting party

**Comment by logan-life** [comment]
- Sending the `organisation.name` is clear
- Sending the `organisation.email` is unclear -- what do we mean here? Organisations do not appear to have an email address associated with the Org in the data model.

**Comment by oharsta** [comment]
The organisation API has a new optional attribute for maximal flexibility: https://github.com/SURFscz/SBS/blob/main/server/swagger/public/schemas/InvitationBulk.yaml#L20

**Comment by mrvanes** [comment]
The **mail body** correctly identifies "Organisation Foobar" as the sender of the invitation, but the **mail from** doesn't.
Is this expected behaviour?
![Image](https://github.com/user-attachments/assets/ff3c415f-5702-41a7-97c3-4212870cf3e6)

**Comment by logan-life** [comment]
Yes, that's the expected behavior.

**Comment by mrvanes** [comment]
Done!

**Comment by FlorisFokkinga** [comment]
It defaults to 'the' organisation admin.
- #1633
requests this to default to the organisation name.

**Comment by logan-life** [comment]
@oharsta would you please clarify this part:

`The name of the sender. Defaults to the name of the organisation admin`


who is the organization_admin chosen for the default case?

**Comment by oharsta** [comment]
If the `sender_name` is not specified in the API call payload, then the name of a random organization_admin is chosen as the sender. If the organisation has no administrators, then the name of a random platform administrator is used. I don't think this has been an explicit requirements-driven decision. It dates back to 2020.
