### ISSUE TITLE
Add SCIM, PAM-weblogin, and token introspection IP addresses to https://servicedesk.surf.nl/wiki/x/k5lsB

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1569]
In current doc:
- LDAP is pull frmo SBS
- SCIM is push from SBS

Change the page accordingly.

**Comment by FlorisFokkinga** [comment]
https://servicedesk.surf.nl/wiki/display/IAM/IP+addresses

**Comment by baszoetekouw** [comment]
checked.
