### ISSUE TITLE
User get shown an OIDC secret even if 'manage' is disabled

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1570]
### Reproducition
- Visit the service request form: https://test.sram.surf.nl/new-service-request
- Select 'OIDC'
The shown secret is not the secret that should be used yet.

**Comment by logan-life** [comment]
@oharsta i see this is fixed on `test`



![Image](https://github.com/user-attachments/assets/440c0662-e57b-4a93-89ff-bbac1b9995a6)


but it is still present on `acc`



![Image](https://github.com/user-attachments/assets/24d633bb-05ac-4ee4-88c9-ea24d18b4f5c)

and on `prod`



![Image](https://github.com/user-attachments/assets/edab4f70-cc1d-4586-8d91-82a7c89dc7b6)


can you add the commit hash or PR link to this issue?

**Comment by baszoetekouw** [comment]
seems to have been fixed in the same commit as #1501
