### ISSUE TITLE
Performance improvement: search organisations with wildcard

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#1571]
In the ServiceDetails page all organisations are fetched with a dummy wildcard of `*`. The results contains the `logo` in base64 encoded format instead of the https:// format.

**Comment by mrvanes** [comment]
How to test?

**Comment by oharsta** [comment]
This can be tested by inspecting the JSON call to `/api/organisations/search?q=*` while loading the ServiceDetail page and confirming the logo's are http urls' instead of encoded base64 images.

**Comment by mrvanes** [comment]
Check!
