### ISSUE TITLE
Updated user attributes on IdP should update them in SBS

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1577]
- Name
- Email address
- Affiliation

Please test this on ACC, using eduID or Mujina.

**Comment by mrvanes** [comment]
Werkt niet zoals ik verwacht
![image](https://github.com/user-attachments/assets/d26d90db-905d-4288-895a-af49a45d4304)
![image](https://github.com/user-attachments/assets/400c0272-61e3-4346-a19e-418f7028aedd)

**Comment by baszoetekouw** [comment]
We need to check if EduTEAMS doesn't pass the new attribute, or if SBS doesn't update them

**Comment by FlorisFokkinga** [comment]
- Use Mujina to change attributes
- Use SAML trace to see which ones are sent to eduTEAMS
- View SBS logs to see which ones arrive at SBS

**Comment by FlorisFokkinga** [comment]
Test failed, only `voperson_external_id` is updated. Emailed edTEAMS the results.

**Comment by mrvanes** [comment]
Still not fixed, unless I don't understand the SBS update logic icw eduid attributes?
![image](https://github.com/user-attachments/assets/d3aad9ae-6ba2-48ae-b3f2-895b231bdf23)

**Comment by FlorisFokkinga** [comment]
No update from eduTEAMS.

**Comment by FlorisFokkinga** [comment]
Updated by eduTEAMS. We should test again.

**Comment by mrvanes** [comment]
Seems fixed now (via eduID TEST)
![Image](https://github.com/user-attachments/assets/a38b3ac9-7d12-454f-aec6-5bcd4ca4de73)
![Image](https://github.com/user-attachments/assets/0fb027f4-ba9b-489c-a1c7-83d64fad380d)

**Comment by FlorisFokkinga** [comment]
Changed email address: floris.fokkinga+eduid@surf.nl -> floris.fokkinga+eduid.nl@surf.nl

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/6c750691-925f-49aa-aa93-e0ed484019c0" />

<img width="1222" alt="Image" src="https://github.com/user-attachments/assets/6e04db65-5af2-49e9-8095-dd14046e852d" />

```
Jan 29 08:56:22 sbs-pf2 gunicorn[874091]: DEBUG [resume-session/user] user: ext_api, Userinfo endpoint results {'name': 'Floris Fokkinga (eduID)', 'given_name': 'Floris', 'family_name': 'Fokkinga (eduID)', 'eduperson_scoped_affiliation': ['member@sram.surf.nl'], 'voperson_external_affiliation': ['employee@surf.nl', 'affiliate@eduid.nl'], 'email': 'floris.fokkinga+eduid@surf.nl', 'uid': ['afad2da3-2815-466d-8fd0-74b1573e0687'], 'voperson_external_id': ['afad2da3-2815-466d-8fd0-74b1573e0687@eduid.nl'], 'eduperson_entitlement': ['urn:mace:surf.nl:sram:group:surf-ram#sram.surf.nl'], 'sub': '58f2b62e893e716eab2b16671dc20d06f1ac0c58@sram.surf.nl', 'voperson_id': ['58f2b62e893e716eab2b16671dc20d06f1ac0c58@sram.surf.nl']}
Jan 29 08:56:21 sbs-pf1 gunicorn[891196]: INFO  [base] user: eduteams, Path /api/users/proxy_authz POST {"user_id": "58f2b62e893e716eab2b16671dc20d06f1ac0c58@sram.surf.nl", "user_email": "floris.fokkinga+eduid@surf.nl", "service_id": "APP-732f7de4-6705-45c5-8617-ac9477ba4f16", "issuer_id": "https://login.eduid.nl", "uid": "afad2da3-2815-466d-8fd0-74b1573e0687", "homeorganization": "eduid.nl"}
Jan 29 08:56:21 sbs-pf1 gunicorn[891196]: DEBUG [user_api] user: eduteams, proxy_authz called with {'user_id': '58f2b62e893e716eab2b16671dc20d06f1ac0c58@sram.surf.nl', 'user_email': 'floris.fokkinga+eduid@surf.nl', 'service_id': 'APP-732f7de4-6705-45c5-8617-ac9477ba4f16', 'issuer_id': 'https://login.eduid.nl', 'uid': 'afad2da3-2815-466d-8fd0-74b1573e0687', 'homeorganization': 'eduid.nl'}
```

**Comment by FlorisFokkinga** [comment]
Fix deployed to production.

**Comment by logan-life** [comment]
@FlorisFokkinga should this be moved to `Done` now that eduTEAMS has deployed the fix?

**Comment by FlorisFokkinga** [comment]
I think so.
