### ISSUE TITLE
Don't log second_fa_uuid

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1580]
`Sep 06 12:31:07 sbs-af1 gunicorn[373748]: INFO  [base] user: 81691fc63ecd011d659ed71fcb54e3982de91cc8@acc.sram.eduteams.org, Path /api/mfa/verify2fa_proxy_authz POST {"totp": "508403", "second_fa_uuid": "dc652de8-6e85-44a7-bfe3-2cf62acb3830", "continue_url": "https://proxy.acc.sram.eduteams.org/session/continue/4ae1faa0-3de2-42c6-a959-6abedeca6041"}`

**Comment by mrvanes** [comment]
Fixed
```
Oct 02 12:58:50 app1-tf1 gunicorn[606927]: INFO:base:user: ab6146d7888deaa351e85036455596442e54451c@acc.sram.eduteams.org, Path /api/mfa/verify2fa_proxy_authz POST {"totp": "000000", "continue_url": "https://proxy.acc.sram.eduteams.org/session/continue/9f1cef8a-31cc-42df-a2fa-1fd51dec9cac"}
```
