### ISSUE TITLE
SCIM Resilience improvements

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#1593]
During integration testing with ResearchCloud we have identified few situations were we lost SCIM updates. For example, when a SRAM Service that is enabled for SCIM Provisioning (Service acts as a SCIM Server), but is not having a SCIM token, the updates to that SCIM Server will fail. But not only the updates to that SCIM Server will fail, but also the updates in that CO for any other SCIM Server that is also configured will fail. (the Raise condition will terminate the broadcasting of SCIM events)

This issue aims to identify the existing 'weak spots' in the current SCIM provisioning implementation to make it fault-tolerant and ready for scalable usage. 

The items identified sofar, are:
* Current logging does not give reason of SCIM failure, it only indicates "error", for better understanding during issue analyzing, the underlying raise condition should be logged, for example in method "apply_change" ```logger.error(f"Error in applying SCIM change ({str(e)})", exc_info=1)```
* Service isolation during SCIM Broadcasting , again in method "apply_change" a try/catch 
* The SCIM broadcasting is based on R/O operations against SBS database, therefor the Rollback/Commit statements are disputable. Shouldn't the outgoing SCIM Broadcasting be organised like:

1) Do SBS updates --> collect sequence of broadcast events
2) db commit
3) db Read/Only
4) collect all affected SCIM Service
```
for each S in scim_services:
   try:
      for b in broadcast_events
        send b to s
   except Exception as e:
        log("scim error:" , str(e))
```
6 db close 

NOT READY YET - TO BE CONTINUED

**Comment by HarryKodden** [comment]
* SCIM Sweep no longer stops sweeping to services if 1 service was misconfigured.
* Exceptions during sweep with any remote SCIM server endpoint are logged but processing will continue
* Delete operations are executed synchronously / Create+Update operations are broadcasts asynchronously, This is controlled via **current_app.sync_executor.submit** versus **current_app.executor.submit** (no longer with seprate parameter flag)
* Tests are adjusted.

**Comment by mrvanes** [comment]
Configured several correct and incorrect SCIM secrets, which didn't influence the flow and was correctly reported in the logs.
However, configuring an unreachable SCIM target (172.17.0.2) significantly delayed the execution (TCP timeout of 10s?) but it was not logged:
```
...
SBS: 2024-10-16 12:33:15,094 scheduler INFO Running scim_sweep for service network (https://network)
SBS: 2024-10-16 12:33:15,107 urllib3.connectionpool DEBUG Starting new HTTP connection (1): 172.17.0.1:8000
SBS: 2024-10-16 12:33:15,110 urllib3.connectionpool DEBUG http://172.17.0.1:8000 "GET /Groups?startIndex=1 HTTP/11" 401 22
SBS: 2024-10-16 12:33:15,110 scim ERROR Scim endpoint http://172.17.0.1:8000/ (SCIM Groups list) returned error 401: {}
SBS: 2024-10-16 12:33:15,113 scheduler INFO Running scim_sweep for service ldap_mon (https://ldap-monitor.example.org)
SBS: 2024-10-16 12:33:15,127 urllib3.connectionpool DEBUG Starting new HTTP connection (1): 172.17.0.2:8000
SBS: 2024-10-16 12:33:25,129 scheduler INFO Finished running scim_sweep_services job in 10109 ms
```

Should unreachable SCIM servers be logged and should TCP timeout be set a little lower than 10s?

**Comment by HarryKodden** [comment]
Suggested changes:
* `../server/scim/sweep.py`
Introduce constant for TIMEOUT = 3

* `../server/cron/scim_sweep_services.py`
in case of exception during sweep:
```
                logger.error(
                    f"scim_sweep for service {service.abbreviation} ({service.entity_id})"
                    f", exception: {str(e)}"
                )
```

**Comment by HarryKodden** [comment]
Test result:

```
sbs-server  | ERROR [scheduler] scim_sweep for service cloud (https://cloud), exception: HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /api/scim_mock/Groups?startIndex=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8f0dc090>: Failed to establish a new connection: [Errno 111] ECONNREFUSED'))
```

**Comment by logan-life** [comment]
log looks great, added a small suggestion for timeout constant. thx for quick look!
