### ISSUE TITLE
As a platform admin, I want a list of services without service admins

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#160]
In https://sram.surf.nl/system/validations 
There is already a list of Organization without admin.  Please add a list of Services without admins.

**Comment by oharsta** [comment]
@sam-cw  Would be nicer if we would have two tabs under actions with the organisation and services icons, where we show the current and new list.

**Comment by sam-cw** [comment]
> @sam-cw Would be nicer if we would have two tabs under actions with the organisation and services icons, where we show the current and new list.

So a second row of tabs under the first?
[**actions**] [cron] [seed] [...]
[organisations] [**services**]

- list item 1
- list item 2

**Comment by oharsta** [comment]
> > @sam-cw Would be nicer if we would have two tabs under actions with the organisation and services icons, where we show the current and new list.
> 
> So a second row of tabs under the first? [**actions**] [cron] [seed] [...] [organisations] [**services**]
> 
> * list item 1
> * list item 2

👌

**Comment by oharsta** [comment]
@sam-cw Sorry, I got confused with another application where we have many sub-tab pages. Currently in SBS we don't have this. So for version 0.1 it is perfectly OK to not do this and just add an additional section with services without admin. We can always later re-fector.

**Comment by sam-cw** [comment]
> @sam-cw Sorry, I got confused with another application where we have many sub-tab pages. Currently in SBS we don't have this. So for version 0.1 it is perfectly OK to not do this and just add an additional section with services without admin. We can always later re-fector.

👍

**Comment by FlorisFokkinga** [comment]
Werkt.
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/80269262/167623034-97f885de-42a6-4d3d-9444-119f94d2e168.png">
