### ISSUE TITLE
Disallow logo upload by url

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1604]
In the Org API, we currently allow logos (for COs for example) to be specified by URL.  This is a security risk, since it means that SBS needs to fetch unverified URLs.

See https://github.com/SURFscz/SBS/blob/main/server/api/collaboration.py#L602-L608

I would like to propose to disallow this, and only accept logos as base64-encoded images.  We can then easily limit the site of the field, and as the image is already put through a transformation, we are also sure that it really is a proper image.

Tracking issue for:
- [ ] https://github.com/SURFscz/SBS/security/code-scanning/64

**Comment by mrvanes** [comment]
The logo now requires a **bare** base64 string, which disallows the common `data:image/png;base64,` HTML prefix.
I found this confusing, to be honest. But it might be expected behaviour?

**Comment by oharsta** [comment]
Agree with Martin, added support for prefix `data:image/png;base64,`

**Comment by mrvanes** [comment]
Ok, I see you now explicitly allow `image/png`, does this mean we won't accept `image/jpeg` and other valid image MIME types?
https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types#image_types
