### ISSUE TITLE
Improve clarity of suspended membership email

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#163]
Explain to the user:
 - what SRAM is
 - which CO this is about
 - what this CO does (description + services)
 - what is means if this is "suspended"
 - what the user can do to prevent it

**Comment by FlorisFokkinga** [comment]
Current email:
> 
> Membership suspended notification
> Membership for user `<user name>` in `<CO name>` was suspended on `<date>`.
> 
> Click the button below to view this membership .
> 
> `[Login]`
> Dear,
> 
> Please login and change the suspension date of `<CO name>` if you want the user `<user name>` of this collaboration to login again on the services of this collaboration.
>
> We are using [SURF Research Access Management (SRAM)](https://edu.nl/vw3jx). Powered by [SURF](https://surf.nl/en).

Proposal:
> 
> Membership suspended notification
> Membership for user `<user name>` in `<CO name>` was suspended on `<date>`.
>
> Dear `<user name>`,
> 
> You are a member of `<CO name>`, a collaboration with description
> `<CO description>`
> As scheduled, your membership of this collaboration has ended. This means you cannot use the services it provides any more. If you think this is a mistake, please contact one of the collaboration's admin, who have also received this email.
>
> Message to the collaboration admins:
> Please login and change the suspension date of `<CO name>` if you want the user `<user name>` of this collaboration to login again on the services of this collaboration.
>
> `[Login]`
>
> We are using [SURF Research Access Management (SRAM)](https://edu.nl/vw3jx). Powered by [SURF](https://surf.nl/en).

Explaining what SRAM is seems to me a bit too much to explain to a user who is already member of a collaboration. A link to the SRAM documentation is included at the end of the email.

**Comment by oharsta** [comment]
@FlorisFokkinga @baszoetekouw Just to confirm: currently the email send out to the administrators of the collaboration and the user who's membership is / will be suspended.  Now we want two separate emails: one only to the user and the other to the administrators?

**Comment by FlorisFokkinga** [comment]
No, still one email to both the user and the admin(s). I see how this could be confusing, though. :)
