### ISSUE TITLE
Missing attribute srmInactiveDays in LDAP and SCIM

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#1631]
According to [link](https://servicedesk.surf.nl/wiki/display/IAM/LDAP+directory+structure#LDAPdirectorystructure-Schemasandextraconfiguration) we should publish the **sramInactiveDays** attribute.
At this moment that attribute is missing. 
Repair action:
* add attribute  to SBS Api **/api/plsc/sync**
* add attribute to PSLC to sync with LDAP
* add attribute to SCIM to sync with SCIM

**Comment by HarryKodden** [comment]
PR submitted (1632)

**Comment by HarryKodden** [comment]
Repair action:

&#9745; add attribute to SBS Api /api/plsc/sync (was already includes **last_login_date**)
&#9745; add attribute to PSLC to sync with LDAP
&#9745; add attribute to SCIM to sync with SCIM

**Comment by mrvanes** [comment]
Ik zie hele rare discrepanties hier in m'n local deploy:
Ik heb een user met sramInactiveDays 0 in ldap, maar 301 (!!!) in SCIM? En meerdere users met sramInactiveDays 30 in ldap en 33 in SCIM? 21 in ldap, 26 in SCIM? Maar ik zie ook overeenkomsten (ldap 0, SCIM 0)
Bovendien zie ik voor dezelfde user in 2 CO's een verschillende sramInactiveDays (0 en 300)? Die 300 is dan weer te linken aan de SCIM 301, maar dan een beetje fout?

**Comment by mrvanes** [comment]
Works as expected
