### ISSUE TITLE
Once an application is made available to an org an error occurs when trying to make it unavailable

### ISSUE THREAD

**Issue by logan-life** [SURFscz/SBS#1638]
- Behavior reproducible on `acc` and `test` 
- Does not appear to be happening in prod
- tested on prod with University of Harderwijk + SRAM Demo SP
- behavior occurs for user with Application Admin role and Platform Admin role

Works as expected:

- change from disallow -> on request
- change from disallow -> always
- change from on request -> always
- change from always -> on request

Error occurs:

- change from always -> disallow
- change from on request -> disallow

---

### Steps to reproduce:
1. Open SRAM Demo SP on test (or acc) as Application Admin or Platform Admin
https://test.sram.surf.nl/services/1035/details

2. Open Access Rules
3. Set Access Rules to `Connected Collaborations` + `Only Some` + `It Depends`
4. Choose an Organization and try to change the value of the `Connections from collaborations` options from either `Always` or `On Request` to `Disallow`

**Comment by logan-life** [comment]
{
	"col": 3255644,
	"error": "t.organisations is undefined",
	"line": 2,
	"message": "TypeError: t.organisations is undefined",
	"stack": "RZ/this.getAffectedEntities@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:3255644\nRZ/this.doDisallow@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:3254106\nRZ/this.changePermission@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:3253049\nonClick@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:3253746\nonClick@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:2070409\nonClick@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:2059946\nNe@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:479980\nIe@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:480134\n82730/Tr/<@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:500034\nTr@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:500128\nDr@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:500545\n82730/Fr/<@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:505987\nll@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:569645\nCe@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:479112\nFr@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:501839\nYt@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:486235\nHt@https://acc.sram.surf.nl/static/js/main.d95d223e.js:2:486017\n",
	"url": "https://acc.sram.surf.nl/static/js/main.d95d223e.js",
	"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"
}

**Comment by logan-life** [comment]
![Image](https://github.com/user-attachments/assets/1ed02558-3652-4dc8-8831-55070d8c4524)
![Image](https://github.com/user-attachments/assets/ed11590b-b958-48b9-a362-4409e1b4744f)
![Image](https://github.com/user-attachments/assets/07e14c68-1f85-4b74-9ab6-04bee53a5b7b)

**Comment by logan-life** [comment]
browser console 

```
Uncaught TypeError: t.organisations is undefined
    getAffectedEntities ServiceOrganisations.jsx:172
    doDisallow ServiceOrganisations.jsx:120
    changePermission ServiceOrganisations.jsx:81
    onClick ServiceOrganisations.jsx:109
    onClick index.js:940
    onClick index.js:402
    React 11
        Ne
        Ie
        Tr
        Tr
        Dr
        Fr
        ll
        Ce
        Fr
        Yt
        Ht
ServiceOrganisations.jsx:172:30
```

**Comment by oharsta** [comment]
New version on the test environment. The error occurred when you set an organisation to disallow and a collaboration of the organisation is linked to that application. The pop-up with the confirmation text caused a JS error (so no server side changes were necessary).

![Image](https://github.com/user-attachments/assets/92d4f626-f6c1-479e-bd7b-4208ea5805c7)

**Comment by logan-life** [comment]
checked on test, is working properly
