### ISSUE TITLE
As a Service Admin, I want Service Groups to be created in new COs in Organizations for which my service is mandatory

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#165]
Observe the following behaviour (in test):
 - Organization "Amsterdam UVA" (https://test.sram.surf.nl/organisations/124/services) has made service "Mail Services" mandatory for all its COs
 - Service "Mail Services" (https://test.sram.surf.nl/services/290/groups) has defined a Service group "Mail group"
 - If a CO admin from a different organization (e.g., "AI computing" https://test.sram.surf.nl/collaborations/421/services) connects the service "Mail Services", the Service Group "Mail Group" is created in that CO
 - If the Org admin from "Amsterdam UVA" creates a new CO, the Service "Mail Services" is automatically available in the CO, but its Service Group "Mail Services" is not created

Please adjust the behaviour such that for newly created COs the Service groups of mandatory Services are also created.

**Comment by FlorisFokkinga** [comment]
Dit werkt.
