### ISSUE TITLE
Too few entries shown in user tab

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#166]

**Comment by oharsta** [comment]
Show all users

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/5f59f0c7eb4c9100f77471486a8b7dd47f43f05a#diff-b631052f6803fef254794f3f4c195a81d582fab78d0f1b4a6526831803098240L208

**Comment by FlorisFokkinga** [comment]
With the test set I can't manage to get more than 17 results. This might be coincidence.

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/80269262/167624121-8169f8bf-75dc-47f2-8047-81ed17abaa04.png">


<img width="1240" alt="image" src="https://user-images.githubusercontent.com/80269262/167624196-eca9ab3e-04a3-4277-810e-94879c414e01.png">

**Comment by FlorisFokkinga** [comment]
Dit werkt.
