### ISSUE TITLE
On the error screen for a user not a member of a collaboration connected to an application, creating a collaboration is suggested even if it cannot be connected to that application

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#1662]
<img width="937" alt="image" src="https://github.com/user-attachments/assets/d4a3bdd8-96c7-4c6d-97cd-d00c5b80ba7e">

So, in this example, the 'SRAM Demo SP' application is not available to connect to a collaboration of the  organisation for the domain 'eduid.nl', so creating a collaboration is not a solution. That should only be suggested if the user's organisation's (by domain) collaboration can be connected to the application the users is trying to log in to.

**Comment by oharsta** [comment]
Implementation note: check the availability of the service against the organisation(s) of the schac_home. Client side logic is currently:
```
 const filteredServices = services
                    .filter(service => {
                        return (service.allowed_organisations.some(org => org.id === collaboration.organisation_id)
                                || service.access_allowed_for_all
                                || service.automatic_connection_allowed_organisations.some(org => org.id === collaboration.organisation_id))
                            && !service.override_access_allowed_all_connections
                            && (service.allow_restricted_orgs || !collaboration.organisation.services_restricted);
                    });
```
