### ISSUE TITLE
Update API documentatie

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#169]
https://github.com/SURFscz/SBS/wiki/External-API

**Comment by oharsta** [comment]
@FlorisFokkinga @baszoetekouw  I would opt to ditch the external API documentation in the Wiki and let the Swagger API specification be the single source of truth. See https://test.sram.surf.nl/apidocs/

**Comment by FlorisFokkinga** [comment]
Lijkt mij beter,  maar moet @baszoetekouw beslissen.

**Comment by oharsta** [comment]
Decided to drop the API docu and use https://test.sram.surf.nl/apidocs/
