### ISSUE TITLE
As a user, I dont want to accept AUPs for Services that  don't use, but I still want to be able to join a CO to use other Services

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#171]
Wanneer ik, al dan niet per ongeluk, een onboarding start vauit de collaboatie view, dan moet ik deze ook afmaken (AUPs accepteren ed.) en heb geen mogelijkheid om het proces af te breken, anders dan F5 te gebruiken.

**Comment by FlorisFokkinga** [comment]
@venekamp Wat bedoel je met 'onboarding starten'? Heb je een schermafbeelding of een stappenplan?

**Comment by FlorisFokkinga** [comment]
Dit is by design voor de eerste versie van de SP AUP. Je moet als je lid bent van een CO met een dienst waarvan de AUP gewijzigd is die accepteren, anders mag je niets meer in SBS.

**Comment by venekamp** [comment]
Ja... maar ik zit al in SRAM, ben al netjes ingelogd en heb alle AUPs geaccepteerd. Nu klik ik per ongeluk op onboading en dan krijg ik het bovenstaande scherm te zien en ik denk: "ojee, ik heb dat niet goed gedaan. Dit kan ik niet accepteren." Nu heb ik geen mogelijkheid om de onboarding te stoppen en weer terug te gaan naar het punt voordat ik op onboarding drukte. Tuurlijk, ik kan https://sram.surf.nl intypen, of F5 gebruiken, maar ik denk dat cancel netter is...

**Comment by baszoetekouw** [comment]
@FlorisFokkinga en ik hebben het hierover gehad.  De logische route lijkt om op dit scherm een "ik aaccepteer deze AUPs nu niet, zeur later maar"-knop toe te voegen.  Als de gebruiker daadwerkelijk naar de dienst gaat, moet hij natuurlijk wle verplicht de AUP van die dienst accepteren.

**Comment by FlorisFokkinga** [comment]
> @FlorisFokkinga en ik hebben het hierover gehad. De logische route lijkt om op dit scherm een "ik aaccepteer deze AUPs nu niet, zeur later maar"-knop toe te voegen. Als de gebruiker daadwerkelijk naar de dienst gaat, moet hij natuurlijk wle verplicht de AUP van die dienst accepteren.

Dit scherm zou daarmee een erg handig scherm voor de happy flow worden, en naar verwachting nog bijna altijd worden gebruikt.

**Comment by baszoetekouw** [comment]
Deel van een bredere discussie over verfijning van AUP-interfaces.

**Comment by baszoetekouw** [comment]
Meenemen in 
 - #260

**Comment by FlorisFokkinga** [comment]
The 'onboarding' function is only available for platform admins. I don't consider the UX when using that function a problem.
We could add an option to the not accept the AUP. I've created #665 for that.
