### ISSUE TITLE
Support multiple schachomeorgs per IdP for MFA-skipping

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1716]
Some institutions use multiple schachomeorgs.  Only one of those can be configured to base MFA-skipping on, causing some users from such an institution to have to do TOTP-MFA even if they also have institutional MFA.

See for example https://servicedesk.surf.nl/jira/browse/SD-89080

**Comment by mrvanes** [comment]
Tested on local deploy with this config:
```
# Lower case entity ID's allowed skipping MFA
mfa_idp_allowed: 
  - 'entity_id': 'https://idp.scz-vm.net/saml/saml2/idp/metadata.php'
    'schac_home':
      - 'ci-runner.sram.surf.nl'
      - 'ssid.example.edu'
```
No MFA was required after password login from test OP.
