### ISSUE TITLE
Only use switches in the GUI where appropriate

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#172]
Waarom zou je een toggle switch aan bijvoorbeeld een service admin laten zien als deze de switch niet mag aanpassen? Dit zie je bijvoorbeeld terug op de services page in de organisation tab. Hier ziet een service admin welke organisaties toegang hebben tot zijn dienst. Echter de service admin lijkt geen rechten te hebben om de status van de switch (Access Allowed) aan te passen. Beter zou het dan zijn om 'Yes/No' of iets dergelijks te gebruiken.

**Comment by baszoetekouw** [comment]
Dit is gefixed in v15
