### ISSUE TITLE
Add "Pam-WebSSO" frontend in SBS

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#175]
See #174 and https://github.com/SURFscz/pam-websso-c/blob/main/doc/protocol.md for a full description of the protocol.

This ticket describes the `/pam-websso/login` frontend for the WebSSO.  A user only end up here if the pam module has called the `/pam-websso/start` endpoint and has initiated a session.  At this point, the session contains:
 - a `session_id`
 - a `user_id` (not necessarily an ePPN or UID, possible also something like an email address)
 - an `attribute`, which describes against which OIDC claim/SBS identifier the `user_id` should be matched
 - a `service_id`, derived from the Bearer token used to authenticate
 
SBS has previously provided the user with a challenge url, which will typically be something like  `https://sbs.local/pam-websso/login/<session_id>`.  
This issues describes the functionality of this login page.

Functional:
When the user first opens the `/pam-websso/login/<session_id>` url, they are greeted with an explanation and are shown for which service they are going to log in.  For this screen no authentication is required. However, SBS must check that the `session_id` is valid and not expired (max lifetime 5 minutes).

Mockup:

![image](https://user-images.githubusercontent.com/1461740/166937846-ea10142e-bf50-40ed-b2e3-614842013633.png)

When the user presses the login button, they need to login to SBS in the regular fashion (including MFA etc).  Once they have successfully logged in, SBS makes an authorization check.  The user can continue if all of the following are true:
 - they have successfully logged in
 - the SBS user field corresponding to`user_attribute` (e.g., email, eppn, username) matches the `user_id` from the `/pam-websso/start` call
 - they are a member of a CO that has access to the specified service (directly or via the Org)

If any of those fail, SBS shows an error to the user:

![image](https://user-images.githubusercontent.com/1461740/166938063-b8235167-055a-4794-8e6f-c114c1d4ee06.png)

(Even though we don't show specific user messages to the user, please do add specific logging for all failures, so that we can check afterwards why the user couldn't log in).

If everything went ok, SBS should:
 - save the date of the successful login for this service to the database (in order to be able to check the `cache_duration` for subsequent calls)
 - generate a 4-digit pin, save it in the session and show it to the user:

![image](https://user-images.githubusercontent.com/1461740/166937957-1ad97898-391b-4b95-92b1-541563558f10.png)

**Comment by FlorisFokkinga** [comment]
````
Enter PIN

Please enter the PIN to the command line interface of <service name>.

1234

After entering the PIN, it is safe to close this screen.
````
And
````
Pin invoeren

Voer nu de pin in op de command line interface van <service name>.

1234

Na het invoeren van de pin, kan dit scherm worden gesloten.
````

**Comment by FlorisFokkinga** [comment]
The permission denied screen seems fine to me.

**Comment by oharsta** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/530657/167133946-202b8bb7-9bad-40c6-88ef-a874df45a4e2.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/530657/167134038-c935f716-0fce-45fd-a6bc-b07e1efb52c9.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/530657/167134181-fd1f5b6a-a870-4a05-beb9-5a1e85e71dad.png">

**Comment by baszoetekouw** [comment]
Tested by @HarryKodden
