### ISSUE TITLE
Remove the service and twofactorauthentication explanation

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#178]
Please remove the explanation panel on the services tab of collaborations.
Part of this help text gives more information than most users would have to know, so it is confusing. The first part of the text is a basic SRAM concept, and should not need an explanation.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/80269262/167402215-0f2e5b6d-f264-498d-adcf-25311bed958c.png">

Also remove the explanation of TwoFactorAuthentication, since that isn't used anymore.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw, lijkt me het beste deze tekst geheel te verwijderen.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/778db99802dad02717da8face6133c01fee908eb

**Comment by baszoetekouw** [comment]
Confirmed
