### ISSUE TITLE
As a platformadmin, I should never be suspended

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#186]
When a platformadmin reaches the MFA entry limit, he is suspended automatically.  This can be quite unfortunate.  
Please either never suspend platformadmins, or allow them to log in even when their account is suspended.

**Comment by thijskh** [comment]
Moeten de eisen aan een platformadmin niet eerder hoger zijn dan lager?

**Comment by baszoetekouw** [comment]
Ja, daar zit wel wat in; als we dit al implementeren zou het alleen voro dev/test moeten oid.
Maar bij nader inzien wordt dit misschien beter opgelost via #187
