### ISSUE TITLE
Revamp van Service edit scherm

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#189]
Het Service edit scherm is een rommeltje geworden.  Zeker als we dit meer aan diensten als self-sefvice willen aanbieden moeten we dit eens goed revampen.

Ik zou iig graag de functionaliteiten per type service bij elakar hebben onder een uitklapdingetje.  Dus: vink je "ldap support" aan, dan krijg je de ldap settings te zien, vink je "token support" aan, dan krijg je token-opties te zien etc.

**Comment by FlorisFokkinga** [comment]
Duplicated by #225.
