### ISSUE TITLE
user-facing endpoint voor pam-weblogin (/pam/login) aanpassen zodat servicenaam erin zit

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#192]
Voor gebruikers is het duidelijker als de login url als volgt is opgebouwd:
```
https://sram.surf.nl/pam-login/<my-service>
```
(precieze prefix ter discussie).  

Dan moeten we natuurlijk wel checken dat `<my_service>` idd overeenkomt met de dienst die deze call initieert (om phishing ed te voorkomen).

**Comment by oharsta** [comment]
Currently there are three pam-weblogin endpoints:
```
POST     /pam-weblogin/check-pin
GET      /pam-weblogin/<session_id>
POST     /pam-weblogin/start
```
Do we only change the last endpoint? Or also the others? And we then replace `start` with `<service.short_name>`?

**Comment by HarryKodden** [comment]
Tested OK:
See (client-facing) verification url containing short name of service:
https://test.sram.surf.nl/weblogin/cloud/4ae2b936-1d0d-4354-937d-2c7d99df6207
