### ISSUE TITLE
Expose CO contact email address in LDAP

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#194]
Story komt via @venekamp.
De vraag is natuurlijk nog welk e-mailadres dat dan moet zijn. Moet je laten zien wie de admins zijn? Of liever de admin zelf een contactadres laten opnemen (dat kan immers een roladres zijn, terwijl een admin altijd een persoon is)?

**Comment by baszoetekouw** [comment]
@venekamp Wat is de achterliggende usecase hiervan?

**Comment by venekamp** [comment]
Als service eigenaar wil ik in contact kunnen komen met de CO admin indien er problemen met de CO zijn. Volgens mij kun je namelijk als service eigenaar deze info niet zelfstandig uit SRAM halen.

**Comment by FlorisFokkinga** [comment]
@venekamp, do you have an example use case for which a service admin would like to contact a CO admin?

**Comment by arnoutt** [comment]
2 things should be implemented:
1) Service admins should be able to see CO info pages of those COs connected to their service; only the header should be visible (including all the information there) - no tabs or additional information
2) In LDAP, admin e-mail addresses should be added to the CO info. Separate ticket.

**Comment by oharsta** [comment]
@arnoutt this makes the the security model overly complex - implementation for viewing a collaboration:

- ORG admin of manager and the CO belongs to this ORG
- CO admin or member
- Service Admin of a service that is connected to a collaboration or the organisation of the collaboration has made the service mandatory for all collaborations

And based on the above, we need to limit the information disclosed. It would be much simpler if we add the admin's of a collaboration to the collaboration tab for service admins. Then he /she also does not has to follow the link and search for the admin email. We could use the Your Role column, as the service admin will not be a member (and if this is the case, then there is the normal member view)

**Comment by oharsta** [comment]
@arnoutt , or we don't change anything in the GUI and only add the admin email to the LDAP?

**Comment by arnoutt** [comment]
Agreed that it would be simpler to add the CO admins to the list of COs connected to your service, however: how? This will not fit, especially if the CO has more than 1 admin (which is highly likely).

Alternative idea: add an icon next to the bin icon (which appears when hovering over a CO) containing the envelope icon, which on click will send an email to all CO admins? (Also include a tooltip explaining what the icon does.) @FlorisFokkinga what do you think?

**Comment by oharsta** [comment]
@FlorisFokkinga your thoughts?

**Comment by FlorisFokkinga** [comment]
Adding it to the row in the CO tab of a service seems like a good solution! This is only accessible for a service admin, and not in the way at all.
Implement this just like the 'email selected members' of a CO, of course.

**Comment by baszoetekouw** [comment]
confirmed
