### ISSUE TITLE
SBS needs to keep track of which and how users have logged in and to which service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#207]
In particular we would like to keep track of which user logged in to which services.

**Comment by mrvanes** [comment]
Audit log only contains these two (new) lines:
Updated Collaboration DEMO CO at September 7, 2022 1:15 PM by Unknown (last_activity_date changed)
Updated User Martin van Es at September 7, 2022 1:15 PM by Unknown. (last_accessed_date changed)
There is no information about the visited service

**Comment by baszoetekouw** [comment]
Ik zou graag een log regel willen met deze informatie:
 - userid
 - service
 - login type
 - was login toegestaan of denied
 - datum

En eigenlijk wil ik die informatie ook voor pam-weblogin en tokens, zodat login_type dan (bv) de volgende waarden kan hebben:
 - `sbs_login`
 - `proxy_authz`
 - `pam_weblogin`
 - `user_token_introspect`

Het doel is drieledig:
 - we willen statistieken kunnen maken van hoeveel het platform gebruikt wordt.  Dit is een manier om alle gebruikers te vangen die inloggen bij diensten
 - we willen in de toekomst bij diensten/COs/Orgs een log laten zien van wie er (volgens ons) is ingelogd geweest
 - we willen de gebruiker kunnen tonen waar hij op ingelogd is geweest

**Comment by baszoetekouw** [comment]
IK kan me voorstellen dat dit eigenlijk niet goed past in de audit log.  Wellicht is het dan handiger om hier een speciale access_log voor te maken.

**Comment by oharsta** [comment]
@mrvanes We agreed that we would keep track of user logins through the proxy-authz endpoint. These are stored in a separate table: `user_logins`. We have also decided that we don't expose the contents (yet). This is the content on test:
```
id,user_id,service_id,created_at
1,21106,319,"2022-08-17 08:30:28"
2,21102,319,"2022-08-19 12:31:52"
3,21106,319,"2022-09-07 11:09:51"
4,21106,319,"2022-09-07 11:13:16"
5,21106,319,"2022-09-07 11:15:59"
```

**Comment by oharsta** [comment]
@baszoetekouw You have changed the requirements quite a bit;-) Will make it so.

**Comment by baszoetekouw** [comment]
works as expected, see #359 for additional feature.
