### ISSUE TITLE
Only show table row buttons on hover over row and/or selection of row(s)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#209]
- Toon de knoppen die alleen beschikbaar zijn wanneer een of meerdere rijen van een tabel geselecteerd zijn, alleen als er een selectie gemaakt is.
- Toon deze knoppen ook als icoontje op de rij bij een mouse over van een rij.

**Openstaande vraag**: hoe te zorgen dat het verticaal niet verspringt bij selecteren?
Ter inspiratie: zie de webinterface van Gmail.

**Comment by arnoutt** [comment]
@oharsta De huidige implementatie op test is nog niet helemaal wat Edwin bedoelde. Het idee is dat de buttons niet boven de table header verschijnen maar _op_ de table header (in plaats van dus, zie Gmail). Nu is er ook een loze witruimte als de buttons hidden zijn, die moet dan ook weg zijn.

**Comment by oharsta** [comment]
@arnoutt en wat doen we dan met de table headers? Die heeft Gmail niet, maar wij wel.
