### ISSUE TITLE
Remove accounts that don't connect to any CO or org or request a CO within a certain period

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#211]
Anyone can create a central SRAM account by authenticating to SBS. If a user doesn't become a member of a CO or Org and doesn't request a CO (do we have all reasons one would create an account for with that scope? No accounts relating to SP management on the platform yet ;-)) within a week of creating a central account, delete the account. Email the user "We noticed an account was created in the SURF Research Access Management service. But we haven't noticed any follow up activity that signals us the account is necessary. In order to protect your privacy and make sure we don't store personal information we don't need, we have deleted the account. If you think we shouldn't have done this, please let us know by sending an email to sram-support@surf.nl ."

**Comment by baszoetekouw** [comment]
Na overleg met @arnoutt en @FlorisFokkinga willen we dit toch herzien.

We willen drie dingen veranderen:
1.  Er moet geen mail gestuurd worden naar de gebruiker; die heeft tenslotte niks gedaan in SRAM en er is dus geen reden om hen hiermee lastig te vallen.
2. Er moet wel een (geaggregeerd) mailtje worden gestuurd naar eduteams (`mail.eduteams_email`) met cc naar sram-beheer (`mail.beheer_email`) , met de boodschap:
  > The following users have been removed from SRAM.  Please delete them from the MMS:
  > uid1 
  > uid2
  > ...
3. We willen niet alle gebruikers zonder lidmaatschappen weghalen, maar alleen de gebruikers die nog nooit ergens lid van zijn geweest.  Dus grofweg de volgende set:
```sql
select u.id, u.email, u.last_login_date , ac.num
from users u 
left join (
	select al.user_id, count(*) as num 
	from audit_logs al 
	where al.target_type not in ("aups")
	group by al.user_id
	) ac on u.id=ac.user_id
where ac.num is null;
```

**Comment by oharsta** [comment]
The query implementation
```
select * from users u where not exists (
    select al.user_id from audit_logs al 
    where al.user_id = u.id and  al.target_type <> 'aups');
```

**Comment by FlorisFokkinga** [comment]
@baszoetekouw , how can we test this?

**Comment by baszoetekouw** [comment]
@okke, I can't get this to work.  It seem that new users (even if they don't do anything) always get the following `audit_logs` entries:

|id|user_id|subject_id|target_type|target_id|action|created_at|state_before|state_after|parent_name|parent_id|target_name|
|--|-------|----------|-----------|---------|------|----------|------------|-----------|-----------|---------|-----------|
|73193|21247|21247|users|21247|2|2022-10-17 10:00:59|{"name": null, "affiliation": null, "entitlement": null, "family_name": null, "given_name": null, "email": null, "eduperson_principal_name": null}|{"name": "Bas Zoetekouw", "affiliation": "member@acc.sram.eduteams.org", "entitlement": "urn:geant:eduteams.org:acc.sram.eduteams.org:group:surf-ram#acc.sram.eduteams.org", "family_name": "Zoetekouw", "given_name": "Bas", "email": "bas@zoetekouw.net", "eduperson_principal_name": "a3788af4-491b-4a3c-9567-5131e70a2498@eduid.nl"}|||Bas Zoetekouw|
|73194|21247|21247|users|21247|2|2022-10-17 10:00:59|{"username": null}|{"username": "bzoetekouw"}|||Bas Zoetekouw|
|73195|21247|21247|aups|20717|1|2022-10-17 10:01:03||{"id": 20717, "au_version": "1", "user_id": 21247, "agreed_at": 1666000863}||||


The last one (`aups`) is ignored by the query, but the first two aren't.

**Comment by oharsta** [comment]
@baszoetekouw Did not think about that. We can just add the `al.target_type <> 'users'` to the query. Can you think of any problems that would give?

**Comment by baszoetekouw** [comment]
I think that should work

**Comment by baszoetekouw** [comment]
works now
