### ISSUE TITLE
As an SRAM user I would like newline characters to be removed from data entered in the public key data entry form field, so that I can paste my public SSH key more realiably

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#216]
Multiple users have reported problems using their ssh key registered in SRAM to authenticate to a ResearchCloud workspace: their key is not accepted by the servce. 
It turns out that these users have copy/pasted their public key into SRAM in such a way that the characters are split into multiple lines of text. Manually removing the newlines in the SRAM public key data entry form field and saving the result resolves the issue.

To the casual observer, the public key in SRAM seems to be exactly the same as at a source location, which makes the cause of the problem difficult to find for both the user and support staff.

(Requested by Ton Smeele, UU)

**Comment by oharsta** [comment]
@FlorisFokkinga This is unfortunately not trivial. If for instance I would remove all line-breaks in the following string
```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20160402"
AAAAB3NzaC1yc2EAAAABJQAAAgEAiL0jjDdFqK/kYThqKt7THrjABTPWvXmB3URI
pGKCP/jZlSuCUP3Oc+IxuFeXSIMvVIYeW2PZAjXQGTn60XzPHr+M0NoGcPAvzZf2
u57aX3YKaL93cZSBHR97H+XhcYdrm7ATwfjMDgfgj7+VTvW4nI46Z+qjxmYifc8u
VELolg1TDHWY789ggcdvy92oGjB0VUgMEywrOP+LS0DgG4dmkoUBWGP9dvYcPZDU
F4q0XY9ZHhvyPWEZ3o2vETTrEJr9QHYwgjmFfJn2VFNnD/4qeDDHOmSlDgEOfQcZ
Im+XUOn9eVsv//dAPSY/yMJXf8d0ZSm+VS29QShMjA4R+7yh5WhsIhouBRno2PpE
VVb37Xwe3V6U3o9UnQ3ADtL75DbrZ5beNWcmKzlJ7jVX5QzHSBAnePbBx/fyeP/f
144xPtJWB3jW/kXjtPyWjpzGndaPQ0WgXkbf8fvIuB3NJTTcZ7PeIKnLaMIzT5XN
CR+xobvdC8J9d6k84/q/laJKF3G8KbRGPNwnoVg1cwWFez+dzqo2ypcTtv/20yAm
z86EvuohZoWrtoWvkZLCoyxdqO93ymEjgHAn2bsIWyOODtXovxAJqPgk3dxM1f9P
AEQwc1bG+Z/Gc1Fd8DncgxyhKSQzLsfWroTnIn8wsnmhPJtaZWNuT5BJa8GhnzX0
9g6nhbk=
---- END SSH2 PUBLIC KEY ----
```
Then the key would actually be invalid (and the conversion to OpenSSH will fail). Could you ask Ton for example keys? Because most line feeds are actually valid in public SSH keys.
