### ISSUE TITLE
As a ORG/service admin, I want to be able to leave the ORG/service from the 'I'm a ORG/service admin' menu

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#222]
In the same way a CO member and CO admin can. Also include the warning whenever the person leaving is the last admin.

**Comment by oharsta** [comment]
@FlorisFokkinga currently the last admin can not leave the organisation. This is implemented by design. I'll include this logic in the drop down menu

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/67f2bf3385f681a3925cd334bfbabbe4fd2f8c30
