### ISSUE TITLE
Revamp the landing page

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#223]
Revamp the landing page as shown in the mockup. Its functionality remains unchanged.

![Image](https://user-images.githubusercontent.com/80269262/176119526-2ce5ae43-90f3-4ab5-82c1-57a0b197cfcf.png)

![collaborate](https://user-images.githubusercontent.com/80269262/176131857-641a7047-bc5b-4ed6-9d8d-53f85b440592.svg)

![Create](https://user-images.githubusercontent.com/80269262/176131859-fda7d6d9-f73c-4804-b9e6-5506475b08ee.svg)

![invite](https://user-images.githubusercontent.com/80269262/176131861-b89f0e3c-a965-4650-9712-45b2ac82b2a1.svg)

![join](https://user-images.githubusercontent.com/80269262/176131864-d8a0cf74-90c5-475d-bf25-665a609fb4d2.svg)

![sram-goodteam](https://user-images.githubusercontent.com/80269262/176132060-8e1c94a5-2471-4a82-a962-d87b37c15910.svg)

**Comment by FlorisFokkinga** [comment]
We've discussed for these white section frames the cutoff of 1300px is a bit wide, the desktop layout should also work on tablets, not on mobile phones, though.

**Comment by FlorisFokkinga** [comment]
Looks good, also on tablet and phone format.

**Comment by baszoetekouw** [comment]
wat mij betreft prima; dit gaat nu met release 15 mee.  Als @arnoutt nog iets wil aanpassen dan graag een nieuw issue aanmaken.
