### ISSUE TITLE
Institution 'unkown' displayed as '[[UNKNOWN]]'

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#226]
Observed on PROD.

![Image](https://user-images.githubusercontent.com/80269262/176859891-a2f2580c-bfa8-4450-8bb2-506df2a7baed.png)

**Comment by FlorisFokkinga** [comment]
https://github.com/SURFscz/SBS/commit/27b1a039b328846b0a39f6860e00a070badd347a

**Comment by baszoetekouw** [comment]
Dat is mijn schuld: https://github.com/SURFscz/SBS/blob/main/server/api/user_saml.py#L214-L215

Verderop in het MFA-proces zjn deze waarden nodig, en gaat SBS op z'n bek als de waarde None is.  Ik had me alleen niet gerealiseerd at deze waarden ook in de UI worden getoond.

Betere optie is gewoon de looup bij de MFA te fixen. Ik zoek het even op.
