### ISSUE TITLE
publieke CO pagina?

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#227]
Willen we publieke CO-pagina's maken.  Hier wortd bv om gevraagd in https://servicedesk.surf.nl/jira/browse/SRAM-1305

**Comment by FlorisFokkinga** [comment]
Voorlopig niet, niet totdat er meer om gevraagd wordt.
Het heeft flinke gevolgen als de informatie van CO-pagina's openbaar wordt gemaakt, terwijl die nu verondersteld is uitsluitend toegankelijk te zijn voor de leden.
