### ISSUE TITLE
As a user first invited, I would like to see a familiar organisational name and logo in the CO invitation email, so I pay attention to it

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#228]
Sometimes, users mistake the emails for phishing. Especially the first email a user receives, offers very little recognizable elements because the name SURF Research Access Management might not be familiar.

Add the name and logo of the organisation responsible for the CO to the email, as shown in the design.

![Image](https://user-images.githubusercontent.com/80269262/177179383-0a4d55d4-8d87-42b6-9a95-56cb83effaef.png)

*Optionally* apply this redesign to other emails.

**Comment by FlorisFokkinga** [comment]
- Horizontal scroll bar is visible, regardless of width.
- Newlines in message are removed.
- CO title, CO description and button seem to be displayed inline, instead of on new lines.

![Image](https://user-images.githubusercontent.com/80269262/187431170-46382b28-08be-4253-a6a3-4374244e5132.png)

- Image for test organisation 'UVA' seems to be missing

![Image](https://user-images.githubusercontent.com/80269262/187431218-e60a9ef4-ef1a-41ed-b778-70b0176327f3.png)

**Comment by oharsta** [comment]
@FlorisFokkinga Ziet er bij mij heel anders uit.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/530657/187433517-95dda6d0-7a4f-410d-b65c-24e0154580b2.png">

**Comment by FlorisFokkinga** [comment]
Juist, blijkbaar heeft de Outlook web client daar een 'ongelukje' met de opmaak. Gmail doet hetzelfde:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/80269262/187435297-10cd5cea-f83d-4ef0-9ed3-d48532901d41.png">

De horizontale scrollbalk is er zowel in de Outlook web client als Outlook desktop for Mac.

**Comment by FlorisFokkinga** [comment]
I would consider those important email clients to support. 🙃

**Comment by oharsta** [comment]
We useFlask-Mail in SBS, but Flask-Mail is “dead” and we have to migrate to https://github.com/marktennyson/flask-mailing.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/82e9337b8aa72098223cced4b73a86fd1a89386f
