### ISSUE TITLE
As a platform admin, I would like to be able to see the view a Service Admin gets, so I can effectively assist them with their questions

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#229]
Deze functie is vergelijkbaar met de "View as member"-knop in het CO-scherm, alleen dan voor Services.

**Comment by FlorisFokkinga** [comment]
This option is available and seems to work.



![Image](https://user-images.githubusercontent.com/80269262/178013065-d5ae29ae-7f01-4020-b6c6-469b0b2e5369.png)
