### ISSUE TITLE
Top left logo on error page redirects to broken AUP page

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#236]
### Observed ###
The top left SRAM logo on this (expected) error page redirects to a broken AUP page.
https://sram.surf.nl/service-denied?service_name=SURF+Research+Cloud+&error_status=4

### Expected ###
The link redirects to the SRAM landing page (when not logged in) or the SRAM home page (when logged in).

**Comment by baszoetekouw** [comment]
works
