### ISSUE TITLE
CO short names that start with a number freeze the GUI and eventually result in an HTTP 404 error

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#239]
Wanneer bij het maken van een nieuwe CO de short name met een cijfer begint, dan lijkt er niks te gebeuren. Er verschijnen geen characters en de platform identifier wordt niet geupdated. Na een tijdje komt firefox met de melding: 'This page is slowing down Firefox. To speedup your browser, stop this page.' Nadat je op stop gedrukt hebt, kun je weer typen. Hierbij kun je alles typen en net zo veel als je wilt. De checks staan immers uit. Ook wordt de platform identifier niet geupdated. Wannneer je de save button gebruikt, volgt er een 404 melding.

Harry heeft dit issue met Chrome getest en krijgt vergelijkbare resultaten.

**Comment by FlorisFokkinga** [comment]
Reproduced on both Firefox and Chrome on macOS.

**Comment by HarryKodden** [comment]
Tested: OK
