### ISSUE TITLE
Invite flow for existing user breaks on 'accept changed AUP' screen with redirect to home page

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#240]
### Reproduction ###
Required:

- CO A with user M as a member and a connected service with an AUP
- CO B

1. Reset the AUP for the service connected to CO A
2. Create an invite for membership of CO B
3. Start the accept invite flow as user M
4. Accept the changed AUP for (the service connected to) CO A

#### Expected ####
Screen with prompt to accept the invite for CO B.

#### Observed ####
Redirect to home page after accepting AUP for (the service connected to) CO A.

**Comment by FlorisFokkinga** [comment]
@oharsta, is the WIP fix also the actual fix?

**Comment by oharsta** [comment]
@FlorisFokkinga I thought so, but when re-testing I found another issue in the flow. Now it is fixed.
