### ISSUE TITLE
Add 'Provisioned by service <Service Name>' to description of groups in COs created by service groups, so CO admins understand what created the groups and help them understand what they are for

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#250]
Add 'Provisioned by service <Service Name>' to description of groups in COs created by service groups, so CO admins understand what created the groups and help them understand what they are for.

So, when a service with service groups is connected to a CO, on creating the group in the CO, prepend its description with the text 'Provisioned by service <Service Name>'.

**Comment by baszoetekouw** [comment]
works.
