### ISSUE TITLE
Improve help tekst when an SSH key is deemed invalid

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#258]
nu: "invalid ssh key". Wat meer info geven, iig over welke soorten keys we supporten
Handigste is denk ik een verwijzing naar de wiki en daar een handledingachtig iets.

Dit kan in de locale worden aangepast.

Client side is checked if the SSH public key begins with one of these prefixes:

- ssh-rsa
- ssh-ed25519
- ecdsa-sha2-nistp256
- ecdsa-sha2-nistp384
- cdsa-sha2-nistp521
- ---- BEGIN SSH2 PUBLIC KEY ----
- ---- BEGIN PUBLIC KEY-----
- -----BEGIN RSA PUBLIC KEY-----

On the server it is tried to convert the SSH public key to an OpenSSH public key for the last three prefixes listed. In that case the user gets notified.

**Comment by baszoetekouw** [comment]
Oplossing: wiki pagina met ssh-key uitleg; Martin kan daarbij assisteren.

**Comment by FlorisFokkinga** [comment]
Explain that if your key starts with one of the listed lines, it probably will work.

**Comment by FlorisFokkinga** [comment]
Documentation: https://wiki.surfnet.nl/display/SRAM/SSH+ciphers

**Comment by baszoetekouw** [comment]
URLs in de vertaling gana niet goed;  @oharsta is dat makkelijk te fixen, of zal ik voor nu gewoon de url er even uithalen?

**Comment by oharsta** [comment]
@baszoetekouw Because we sanitise all HTML in the translations using `DOMPurify` the `target="_blank"` is stripped from the link. I consider that a feature.

**Comment by baszoetekouw** [comment]
Agreed, but the link isn't rendered at all; I'm not sure is we would want that, but it breaks the translation here.  For v17, I'm removing the link.

**Comment by oharsta** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/530657/201891374-1c29f3ef-daa2-4457-b866-d7748956f3b0.png">

**Comment by baszoetekouw** [comment]
fb79a16
