### ISSUE TITLE
An invitee for a CO needs to accept AUPs if there are none

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#260]
Currently, if a CO only uses services with NO aup provided, users joining still have to "agree" to the AUP. This should not happen. Instead, an alternative "join screen" should be presented (design TBD).

Also, the design should be changed for COs who use both services with and without AUPs. Because for the latter, no permission/agreement is required (only a link to the (mandatory) privacy policy). Design TBD.

**Comment by arnoutt** [comment]
Zie ook
 - #171

**Comment by FlorisFokkinga** [comment]
Current screen for accepting an invite to a CO with only services without an AUP.


![Image](https://user-images.githubusercontent.com/80269262/233984394-87e216fe-1937-415e-90b3-0e8f86121b8b.png)

@baszoetekouw, would simply removing the text "Before joining this collaboration, you must review the acceptable use policy (AUP) and privacy policy of the service and accept them." and removing the checkbox resolve the problem?

**Comment by FlorisFokkinga** [comment]
Works!

![Image](https://user-images.githubusercontent.com/80269262/236776118-28b19e60-0c74-4318-a28b-0e6a6cfceac1.png)



![Image](https://user-images.githubusercontent.com/80269262/236776148-2a5345eb-1e5f-4af4-8fa1-3443d982ca21.png)



![Image](https://user-images.githubusercontent.com/80269262/236776202-03a7baf1-e33a-4396-a1b6-e1f5e2437173.png)
