### ISSUE TITLE
As an organisation admin or manager I want to search for users and invites within my organisation's COs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#266]
On the organisation screen add a tab 'Users' that displays all the members and invites for all the COs of that organisation and make it searchable.
This seems like a filtered copy of the 'Users' tab for the platform admins, with added invites (only searchable on the email address, of course).

Use case van Ander (SRC): "mijn use case is dat iemand van de helpdesk vragen krijgt van gebruikers. En in SRC werken ze altijd in termen van projecten, die we nu als CO’s mappen. Dus wij moeten ze vaak helpen aan de hand van het project waar ze werken" en “kun je mij opnieuw de uitnodiging sturen, want die is nu verlopen?”

**Comment by arnoutt** [comment]
We received another request for similar functionality. In this case, it's mostly about deprovisioning. As the institution under which the collaboration falls is responsible (GDPR-wise) for the processing of personal data, this means organisation admins (/ managers) should have sufficient controls to remove (certain) authorisations. One could argue removing/disabling the user's account in the IdP should be sufficient, but some institutions maintain certain grace periods which in practice sometimes means users can still login even though they have no formal relation with the institution (anymore).

This means the organisation admin/manager should be able to find information about and memberships of users who fall under the responsibility of the organisation. Thus: users/memberships of COs managed by said organisation.

So in addition to what @baszoetekouw describes above, after finding a user and clicking him/her to see the details, the COs which are managed by the organisation at hand this user is a member of should also be listed. These COs should be clickable such that the organisation admin/manager can quickly browse to the CO and remove the user from the CO.

**Comment by baszoetekouw** [comment]
werkt zoals beschreven.

**Comment by FlorisFokkinga** [comment]
@arnoutt, this feels like more information than necessary.


![Image](https://user-images.githubusercontent.com/80269262/189126015-a553a2cb-9d3d-4a8f-b8a9-51a4efb14ed8.png)

For deprovisioning I'd say:
- Name
- Email
- Username
- Institution
- Last login date
- SSH public keys (number of)
- In collaborations managed by your organisation
