### ISSUE TITLE
Profile page makeover

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#267]
Pagina heeft nu andere layout dan rest van SBS.  Teksten zijn slordig (ik ben helemaal niet ingelogd via eduteams, naar mijn gevoel).

Bij Profile kan ik mijn gegevens (uiteraard) niet wijzigen. Misschien instructie toevoegen (als je naam niet klopt... wijzig die dan op de IdP?)
Voorstel tekst:
> Below you'll find the information we have about you. Some info we've received from the identity provider you used to access SRAM, like an institution or guest identity provider: if you want to change that data, you have to do so at that identity provider.

> Hieronder vindt je gegevens die wij over je hebben. Sommige gegevens hebben we ontvangen van de identiteitsprovider die je hebt gebruikt om toegang te krijgen tot SRAM, zoals een instelling of gastidentiteitsprovider: als je die gegevens wilt wijzigen, moet je dat bij die identiteitsprovider doen.

**Comment by thijskh** [comment]
Mijn full name kan ik wel zelf wijzigen in SRAM, wat daar staat heeft niks te maken met wat mijn IdP vrijgeeft dus wijzigen bij de IdP heeft vermoedelijk ook geen effect.

**Comment by FlorisFokkinga** [comment]
I've split this issue into three. This ticket is now only about the redesign, not about the profile history or exporting user data.

**Comment by FlorisFokkinga** [comment]
## For review ##

![Image](https://user-images.githubusercontent.com/80269262/205658774-0516df9e-f764-4d5e-8e77-75061bfb865e.png)



![Image](https://user-images.githubusercontent.com/80269262/205658786-5d19ae6c-7a20-4f72-b16a-9d60665c7675.png)



![Image](https://user-images.githubusercontent.com/80269262/205658810-66f6e5cf-272d-4cff-bb3c-d5f2d180d0b7.png)

**Comment by baszoetekouw** [comment]
Design is prima.  Hangt nog wel af van andere stories om daadwerkelijk de informatie die we hier nodig hebben in SBS te krijgen.

**Comment by baszoetekouw** [comment]
Dus we gaan dit splitsen in losse stories: eerst het design implementeren met de huidig beschikbare informatie (dus zonder de schildjes en "provided by UniHarderwijk").  Die komen dan later in een losse story.
