### ISSUE TITLE
As a Servcie Owner, I want to allow some CO/Org's to connect my Service automatically, while others still need to get my approval before connecting

### ISSUE THREAD

**Issue by HendriHondorp** [SURFscz/SBS#272]
Voor het koppelen van een service aan een CO heeft de service-beheerder de waarde voor een koppelverzoek ingesteld (automatisch of toestemming geven).
Een API voor het maken van zo'n koppeling wordt  meestal in een automatisch proces gedaan, bijv in een script dat CURL gebruikt.
Hierbij heeft de service-beheerder een code (service_entity_id) meegegeven die met CURL gebruikt wordt.

Het zou handig zijn als deze API de waarde van het koppelingverzoek kan overrulen zodat deze automatisch plaats kan/mag vinden, default is de waarde die in SRAM service webpagina is ingesteld (bijv parameter "automatic_connection_allowed").
Dit zou rond regel 76 van server/api/collaborations_services.py toegevoegd kunnen worden.

**Comment by baszoetekouw** [comment]
Dank voor het inschieten van het issue!  Dit is inderdaad de handigste manier om dit soort verzoeken in te dienen.

Ik neem aan dat het over deze API gaat: https://sram.surf.nl/apidocs/#/default/put_api_collaborations_services_v1_connect_collaboration_service ?
Dat is namelijk een call die gedaan wordt door de Organisatie.  In het algemene geval is het niet de bedoeling dat de Organisatie-admin zomaar de keuze van de Dienst-admin (die automatisch koppelen uit heeft gezet) kan overrulen.  

Maar ik vermoed dat in jouw geval het je eigen dienst is die je aan je eigen CO/Organisatie wilt koppelen?  Dus dat de Dienst-admin en de Organisatie-admin dezelfde persoon zijn?  In dat geval is het inderdaad onlogisch dat je eerst nog handmatig toestemming zou moeten geven.

**Comment by HendriHondorp** [comment]
Klopt inderdaad wat je schrijft.

**Comment by baszoetekouw** [comment]
Misschien is de meest logische oplossing dan om de setting "automatic_connection_allowed" configureerbaar te maken per Organisatie.  Dus in plaats van een generiek vinkje, kan je als diensteigenaar dan instellen welke Organisaties wel en welke niet automatisch mogen koppelen.

Zou dat wat jou betreft een goede oplossing zijn?

**Comment by HendriHondorp** [comment]
Dat zou al een verbetering zijn. Dan zijn er drie opties mogelijk:
1. voor niemand automatisch koppelbaar (default).
2. voor iedereen automatisch koppelbaar;
3. voor sommigen automatisch, de rest niet. Eigen instelling (service-owner = organisatie-owner) mogelijk boven aan de lijst plaatsen of default op koppelbaar zetten?

Optie 1 en 2 is nu al van toepassing dmv de aan/uit optie in de Service webpagina.

**Comment by oharsta** [comment]
Made a typo in the commit https://github.com/SURFscz/SBS/commit/dab3151e02e34a702ff54d60d2c42732bc74a572. This commit has nothing to do with this issue.

**Comment by baszoetekouw** [comment]
ook https://github.com/SURFscz/SBS/commit/6d9ec6a8ecc43092be48db3e8ca3bb96426776e3 hoort bij een ander ticket (https://github.com/SURFscz/SRAM-deploy/issues/272)

**Comment by oharsta** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/530657/204128860-7d568bfe-3e10-4fca-bd81-c3a4fdb4ba81.png">
If a Service does not allow for automatic connection requests then the platform_admin or service_admin can select organisations (from the list of all allowed organisations), where the collaborations of these organisations can automatically connect to this service. If a Service does allow for automatic connection requests , then the multi-select is emptied and disabled.

**Comment by mrvanes** [comment]
Werkt zoals beschreven
