### ISSUE TITLE
Betere database seed voor test

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#276]
- er is een CO die Universiteit Utrecht heet
- er zijn te weinig Os
- geen users die CO kunnen aanvragen
- betere beschrijvende namen
- geen echte instellingen gebruiken

**Comment by oharsta** [comment]
De huidige seed is historisch zo gegroeid en als we deze fors willen re-factoren, dan is het best veel werk om de testen te fixen. Ik zou opteren voor een tweede seed, die dan in de System pagina kan worden gedraaid.

**Comment by baszoetekouw** [comment]
Ok, dan vraag ik Martin en Harry om een nieuwe seed te maken die beter aansluit bij het echte gebruikt.

De requirements zijn (@FlorisFokkinga kun jij aanvullen?):
 - geen namen die overeenkomen met echte instellingen.  uni-harderwijk.nl en uni-franeker.nl zijn eventueel beschikbaar als fake instellingen
 - er moet een beetje vulling zijn qua aantallen
 - de demo-sp en demo-rp (zie huidige test) moet erin zitten
 - de verschillende statussen van de Orgs moeten voorkomen: surf/niet-surf, auto-approve CO's
 - de verschillende statussen van de COs moeten voorkomen: actief,expired, met en zonder join requests, met en zonder hidden members, met en zonder hidden email
 - de verschillende statussen van Services moeten erin zitten: auto-approve ja/nee, SURF service ja/nee, algemeen toegankelijk
 - de verschillende soort diensten moeten erin zitten: saml, oidc, ldap, token, pam

Uiteraard kunnen we dat iteratief doen; als we een begin hebben is het tamelijk eenvoudig uit te breiden.

**Comment by FlorisFokkinga** [comment]
- Ik gebruik de testomgeving wel eens voor korte demo's.
  - Objecten moet een duidelijke, representatieve naam hebben (er is nu een CO die 'Universiteit Utrecht' heet, dat is verwarrend).
  - Dus een organisatie moet iets van een universiteit, hogeschool, umc of onderzoeksinstelling zijn. Het liefst van alles wat.
  - Een CO moet een onderzoekssamenwerking zijn, en doorgaans toegang geven tot meerdere diensten.
  - Je mag natuurlijk wel werken met getallen om wat aantallen te bereiken (bijvoorbeeld CO 'UCF research project 153').
- Alle functionalteit die je terug kunt zien in de GUI moet je kunnen terugzien.
- Het moet, zoals Bas al impliceert, uitbreidbaar zijn.
- Ook een 'SURF' organisatie met een aantal 'SURF only' diensten.
- De meeste services moeten een admin hebben.

Daarnaast zou ik heel graag, maar ik weet niet of dat in scope is, een aantal gebruikers hebben die beperkte rollen hebben, zowel voor demo- als testdoeleinden. We lopen er regelmatig tegenaan dat we niet weten (of onvoldoende getest hebben, zie #284) hoe functionaliteit precies werkt voor andere rollen dan platform admin.
Dus misschien een aantal gebruikers uit de [SURFconext test IdP](https://idp.diy.surfconext.nl/showusers.php) (of iets vergelijkbaars) één of een aantal rollen geven?

**Comment by oharsta** [comment]
@baszoetekouw @FlorisFokkinga Wat we ook kunnen doen, is op de test omgeving de database leeg gooien. Jullie kunnen dan de database weer vullen met organisaties, collaborations, services en uitnodigingen versturen en accepteren met Mujina en de juiste user attributen zetten bij het inloggen op Mujina. Op het moment dat de data goed gevuld is, dan maken we een copy van de database en dat is dan de test-seed. Ik kan de System functionaliteit voor de platform admin's uitbreiden met een demo seed tab. Goed idee?

**Comment by FlorisFokkinga** [comment]
Best belangrijk:
- Vul in een aantal objecten (zeker niet allemaal, dat zit in de weg) heel veel of heel weinig, of bijzondere gegevens in. Dus een organisatienaam van duizend karakters, en een CO-naam bestaand uit alleen emoji's, dat soort dingen.

**Comment by baszoetekouw** [comment]
> Op het moment dat de data goed gevuld is, dan maken we een copy van de database en dat is dan de test-seed.

Ik heb daar uit de Serviceregstry-tijd van SURFconext slechte ervaringen mee; het werkt wel, maar is lastig te beheren (je moet het steeds opnieuw doen als de database verandert) en het is moeilijk aan te passen en uit te breiden.

Ik ga dus liever voor een "handmatige" vulling vanuit python code; dat is nu wel wat meer werkt maar levert op de langere termijn veel voordeel op.

**Comment by oharsta** [comment]
> 
> Ik heb daar uit de Serviceregstry-tijd van SURFconext slechte ervaringen mee; het werkt wel, maar is lastig te beheren (je moet het steeds opnieuw doen als de database verandert) en het is moeilijk aan te passen en uit te breiden.
> 
> Ik ga dus liever voor een "handmatige" vulling vanuit python code; dat is nu wel wat meer werkt maar levert op de langere termijn veel voordeel op.

Ik had een fancy feature voor ogen, zodat je de demo-seed kan inladen op een omgeving, veranderingen maken in de GUI en weer persisteren (met een versie). Maar wellicht pakt dat inderdaad verkeerd uit. Ik doe wel een eerste aanzet en zal de demo-seed toevoegen aan de system tab voor platform-beheerders.

**Comment by baszoetekouw** [comment]
@mrvanes was er eerder deze week ook aan bezig, dus overleg even met hem voor jullie dubbel werk doen.

**Comment by oharsta** [comment]
Ik kan volgende week de - alleen op test en door platform admins - functionaliteit maken om deze seed te draaien in de `System` tab. @baszoetekouw Ik neem aan dat de bedoeling is?

**Comment by oharsta** [comment]
Demo data can now be run on the seed tab in system section. Going to assign this Floris to add more data to https://github.com/SURFscz/SBS/blob/main/server/test/demo_seed.py. I can help of course, but it is more a functional task then technical.

**Comment by FlorisFokkinga** [comment]
After conferring with @mrvanes, I propose to have three data sets:
 - For unit tests.
 - For demos, with realistic feeling data to explain functionality and to show SBS's features.
 - For human testing, with extreme forms of data, e.g., long values, emoji, and large numbers of entries.

**Comment by baszoetekouw** [comment]
Projectje van maken.

**Comment by baszoetekouw** [comment]
done
