### ISSUE TITLE
gebruik van dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#281]
Cure53 zegt over het gebruik van `dangerouslySetInnerHTML` in `components/BreadCrumb.jsx`:

> the testing team was unable to determine a reason as to why breadcrumbs needed to return the page’s path using user-supplied input[...]. The optimal solution in this case, then, would be to have the application determine the location and render the component dynamically without user interaction.

Is het mogelijk de applicatie aan te passen zodat hij idd geen user input gebruikt voor die breadcumbs?

**Comment by baszoetekouw** [comment]
Of kunnen we niet helemaal van `dangerouslySetInnerHTML` af?  Als di efunctie zo heet dan is er toch vast ook wel een minder gevaarlijk alternatief?

**Comment by oharsta** [comment]
Unfortunately we can't use an alternative as we use this method to render HTML from the locales (like <strong> and mail:to etc) as well in some situations to render user supplied input (like the name of a collaboration with emphasis). The solution to use this safely is to escape the input using the `Dompurify` library. Which I have done after the findings.

**Comment by baszoetekouw** [comment]
Woul dit make sense to define a global `SetEscapedInnerHTML` function that defines the escaping in one place, and that we can use everywhere?  That would make any unsafe uses easy to detect by grepping for `dangerouslySetInnerHTML`.

**Comment by baszoetekouw** [comment]
Op https://stackoverflow.com/questions/29044518/safe-alternative-to-dangerouslysetinnerhtml wordt gesuggereerd om ofwel een ESlint plugin te gebruiken die die kan checken (https://github.com/theodo/RisXSS/) ofwel om de library interweave (https://interweave.dev/) te gebruiken ipv direct dangerouslySetInnerHTML te gebruiken.  Dat eerste lijkt me sowieso een goed idee; is het overschakelen naar Interweave ook zinvol?

**Comment by oharsta** [comment]
Added https://github.com/SURFscz/SBS/blob/main/client/.eslintrc.js file with the ESLint plugin. Solved all warnings. Had a look at interweave, but this has a lot of features that we don't want and migration is a lot of work.

**Comment by oharsta** [comment]
See https://github.com/SURFscz/SBS/commit/2ed7ccef3a72b55ab0554bd920d0816913434d8b
