### ISSUE TITLE
find_by_identifier API leaks information

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#283]
The endpoint `/api/collaborations/find_by_identifier` leaks multiple types of information
 1. CO information to non-members of the collaboration
 1. Member information of COs that do not disclose member information
 1. Member email addresses of COs that do not disclose email addresses

The latter two should be easy to fix by simply adding a check for those CO settings and filtering the information

The first one might be harder to fix, because (I assume) this endpoint is needed to fetch information of COs in the invitation process (i.e., to show to user who are in the process of accepting an invitation, but are not members of the CO yet).  The main issue, I think, is that we assumed the CO uuids to be unguessble.  However, these uuids are included both in the invitation and in the LDAP, so should be considered public information.

**Comment by baszoetekouw** [comment]
Nav gesprek op Slack:
Als we CO-informatie dichtzetten voor publieke consumptie (en dan met name informatie over welke diensten aan welke CO zijn gekoppeld) is de consequentie daarvan dat we op het Join-request landingsscherm niet meer kunnen tonen welke diensten gebruikt moeten worden:

![image](https://user-images.githubusercontent.com/1461740/187407048-86b0a245-797a-43a3-a698-dc4fdd1f51dc.png)

@FlorisFokkinga @arnoutt Het lijkt me wel acceptabel om dat stukje "Where we collaborate" te verwijderen voor nu, denk ik?

**Comment by oharsta** [comment]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/530657/187408109-3b26764f-1739-410c-bf91-5eb317941d42.png">
Dit is de huidige pop-up als iemand een collaboration membership request doet.

**Comment by baszoetekouw** [comment]
Ah ja, sorry, ik had het verkeerde schermpje gedeeld idd; als je lid bent mag je natuurlijk wel zien waar er wordt samengewerkt; het scherm van Okke hierboven is waar het om gaat

**Comment by oharsta** [comment]
Nee, in de huidige implementatie is dat scherm de tweede stap in het aanvragen van een collaboration membership request.

**Comment by FlorisFokkinga** [comment]
So, this means that a user requesting membership of a CO can only see the services and accept their AUPs after the request has been accepted?

**Comment by oharsta** [comment]
That' s the idea indeed.

**Comment by oharsta** [comment]
I can revert the change, but then the services ACL is broken. Business decision.

**Comment by FlorisFokkinga** [comment]
It is already possible to be a member of a CO of which a connected service changes the AUP.
If, after accepting the invitation, the user ends up in a similar situation of being a member, but needing to accept the AUPs, that seems acceptable.

So if I understand the situation, leave the change as it is.

**Comment by baszoetekouw** [comment]
correct gefixed
