### ISSUE TITLE
Revert login button size, text size and the size of the subtext on the landing page, changed in #223

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#285]
The mockup in #223 showed a smaller login button and smaller text underneath the button, which was exactely implemented.
I think we shouldn't have made the button and text smaller though.

Please revert the button size, and the text on the button to what is was before.
Also, please give the text below the button the same size as the text that was above the button before (as it is on ACC and PROD now).

**Comment by oharsta** [comment]
@FlorisFokkinga Can you attach a screenshot of either acc and prod of the desired landing page button size. I don't have access to these environments.

**Comment by FlorisFokkinga** [comment]
TEST
<img width="803" alt="image" src="https://user-images.githubusercontent.com/80269262/187385034-fc6b08c5-fde8-4509-9306-f3b9359e2167.png">

ACC
<img width="458" alt="image" src="https://user-images.githubusercontent.com/80269262/187385081-e5806954-c5d7-4b4c-85fc-f4d8c4c05129.png">

ACC and PROD are publicly accessible, though. :)

**Comment by baszoetekouw** [comment]
klopt op test
