### ISSUE TITLE
Use better RNG for ldap secrets

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#289]
LDAP password are generated using `random.sample`, which is cryptographically insecure: 
https://github.com/SURFscz/SBS/blob/main/server/api/service.py#L142 

Instead, we should use `secrets.SystemRandom`

Also, maybe we should have a central function in SBS te generate password and tokens, so that we can easily update them if requirements change?

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/blob/main/server/auth/secrets.py
