### ISSUE TITLE
Consider using modern bcrypt/scrypt password hashes for ldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#290]
Need to check first if openldap and the bulleye version of libs properly support the modern hashing methods.

If it's supported, we could easily change https://github.com/SURFscz/SBS/blob/887dfd670359ae2bd504280b102ba81162bca9f7/server/auth/secrets.py#L29 to use bcrypt/scrypt instead.

- [x] check support in Debain 11 glibc for scrypt
- [x] doublecheck if they work when put in ldap for authentication
- [ ] implement in SBS for new passwords

**Comment by baszoetekouw** [comment]
also see #464

**Comment by baszoetekouw** [comment]
Debian 11 ondersteunt zowel bcrypt als scrypt.

**Comment by mrvanes** [comment]
Works for slapd

**Comment by baszoetekouw** [comment]
confirmed on test.
