### ISSUE TITLE
Insecure CSP headers needed for swagger pages

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#293]
Swagger uses inline scripts and therefore needs to set `script-src: 'unsafe-unline'`.  This is undesireble.

The only part of swagger that seems to use the inline script is this: https://github.com/flasgger/flasgger/blob/master/flasgger/ui3/templates/flasgger/swagger.html
According to the comment in https://github.com/flasgger/flasgger/blob/master/flasgger/ui3/templates/flasgger/index.html it should be easy to override this; if we can just put the js in its own file and include only a `<script src="bla">` in the index.html, that should suffice.

**Comment by baszoetekouw** [comment]
According to @oharsta flassger seems to be unsupported atm, so it might make sense to simply make a fork and fix this issue there.

**Comment by oharsta** [comment]
Already did this: https://github.com/SURFscz/flasgger

**Comment by baszoetekouw** [comment]
@mrvanes kun jij hier eens mee prutsen?

**Comment by baszoetekouw** [comment]
Dit is gefixed met https://github.com/SURFscz/SBS/issues/476 en https://github.com/SURFscz/flasgger/pull/1
