### ISSUE TITLE
Swagger uses google fonts

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#294]
Flassger lijkt niet meer echt actief onderhouden te worden, dus misschien moeten we dit mar in onze eigen fork fixen.  Probleem zit iig hier: https://github.com/SURFscz/flasgger/blob/master/flasgger/ui3/templates/flasgger/head.html#L3

Moeten we wel die fonts zelf nog even lokaal neerzetten natuurlijk.

**Comment by oharsta** [comment]
@baszoetekouw Given the fact that we only enable Flassger for non production environment and given the fact that Google fonts are trustworthy: is this worth the effort?

**Comment by baszoetekouw** [comment]
we actually do use Flassger in prod.  I agree it's not a really big issue, but one I'd like to fix if at all possible.

**Comment by baszoetekouw** [comment]
@mrvanes  has fixed this in https://github.com/SURFscz/flasgger/pull/2, put it seems the UI wasn't using these fonts in the first place (even though it was defining them and loading them).
