### ISSUE TITLE
Beveiliging tegen CSRF attacks

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#296]
Uit de audit:
>[...] the SBS application does not appear to have established any preventative measures against cross-site request forgery (CSRF) attacks. Naturally, [the audit team] advises implementing adequate actions to ensure CSRF vulnerabilities cannot proliferate within the SBS application.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/8ca62f9e70e3c7efd7f8e7ad3d3b91cf45f1d4d2
