### ISSUE TITLE
On a service without any LDAP ACL IP ranges, switching to the 'Details' tab gives the error on its empty field 'This is not a valid IPv4 or IPv6 address.'

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#300]
Reproduction:
1. Open a service without any LDAP ACL IP ranges (or delete de LDAP ACL).
2. Switch to a different tab, e.g., 'Organisations'.
3. Switch back to the 'Details' tab.
4. Observe 'LDAP' in the TOC is red.
5. Observe the 'LDAP ACL IP ranges' field displays the error 'This is not a valid IPv4 or IPv6 address.'.

Observed on TEST

![Image](https://user-images.githubusercontent.com/80269262/188101091-7c3a622b-9d67-4931-97a2-5dc6f76e9642.png)

**Comment by FlorisFokkinga** [comment]
Reproduction:
1. Open a service without any LDAP ACL IP ranges (or delete de LDAP ACL).
2. Switch to a different tab, e.g., 'Organisations'.
3. Switch back to the 'Details' tab.
4. Observe 'LDAP' in the TOC is red.
5. Observe the 'LDAP ACL IP ranges' field displays the error 'This is not a valid IPv4 or IPv6 address.'.

Observed on TEST

![Image](https://user-images.githubusercontent.com/80269262/188101091-7c3a622b-9d67-4931-97a2-5dc6f76e9642.png)

**Comment by baszoetekouw** [comment]
Werkt nu goed op test.
