### ISSUE TITLE
As a service admin, I want to add the member's username and CO shortname to the service URL as a variable, so users can log into a CLI (SSH) service from the CO screen directly

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#302]
To the field labeled 'Service URL', please add two variables, one for the username of the logged in user and one for the shortname of the currently displayed CO, to be filled in on the member view of a CO page.

![Image](https://user-images.githubusercontent.com/80269262/188131937-1870c600-a81d-4531-9ef6-1a87c9f1b576.png)

The variables SHOULD be named CO_short_name and SRAM_username.
The variables COULD use '_' as a separator.
The variables COULD be indicated by '{' and '}'.

Tooltip EN:
URL where to reach this service, displayed prominently to collaboration members.
These variables will be replaced with the appropriate values: {CO_short_name} and {SRAM_username}.

Tooltip NL:
URL waarop de dienst bereikbaar is. Wordt duidelijk getoond aan leden van samenwerkingen.
Deze variabelen worden vervangen door de corresponderende waarden: {CO_short_name} en {SRAM_username}.

Use case is CLI, where SRAM username and, in rare cases, the CO is required to log in.

**Comment by oharsta** [comment]
@FlorisFokkinga Is the variable named SRAM_username or username? Both variations are mentioned.

**Comment by baszoetekouw** [comment]
Doe maar zonder `SRAM_` prefix; dit wordt toch alleen intern gebruikt binnen SRAM.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw I don't understand. These variable names will be documented and will need to be entered by service admins.

**Comment by mrvanes** [comment]
Het is {co_short_name} en {username} geworden, maar er is nog wel iets geks aan de hand.
Als ik in de service, de service URL zo definieer:
https://demo-sp.sram.surf.nl/rp/test/{co_short_name}/{username}

Dan staat er bij de CO dit:
https://demo-sp.sram.surf.nl/rp/test/democo@/{username}

{username} wordt niet gesubstiueerd en is de @ achter democo@ by-design?

![Image](https://user-images.githubusercontent.com/1901782/188832716-c3da0c8e-e8bc-4c4f-9db2-dbc8945ac9d9.png)
![Image](https://user-images.githubusercontent.com/1901782/188832697-860e230d-4603-4c8a-a668-bc69901f85fe.png)

**Comment by oharsta** [comment]
I was under the impression that either one of variables would be used to specify the user. e.g. `https://admin@some.ssh.service` and that the URL configured would be `https://{username}some.shh.service` or `https://{co_short_name}some.shh.service`. @FlorisFokkinga I made a wrong assumption?
