### ISSUE TITLE
`/api/mfa/sfo` endpoint is obsolete 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#303]
This endpoint is now obsolete (replaced by the logic in `/api/users/proxy_authz`).  Please remove it (and i think that also removes the need for jwk private keys etc).

**Comment by oharsta** [comment]
Note for cleaning up: also the `/jwks` endpoint can be removed and all references to `session["in_proxy_flow"]`

**Comment by oharsta** [comment]
All references to:
```
  private_rsa_signing_key_path: config/jwt_private_key
  public_rsa_signing_key_path: config/jwt_public_keys.json

```
can be deleted from the SCZ-deploy project.
