### ISSUE TITLE
GET on `/api/collaborations/v1` gives 500

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#304]
Should return a 405 Method Not Allowed instead (only POST is allowed).

**Comment by oharsta** [comment]
@baszoetekouw Can you provide a curl example? I'm getting a 404 with:
```
curl -vik -u sysadmin:xxx "https://test.sram.surf.nl/api/collaborations/v1"
```
And that is because there is a GET endpoint which expects a `identifier` path parameter at the end of the url. See https://test.sram.surf.nl/apidocs/#/default/get_api_collaborations_v1__identifier_
