### ISSUE TITLE
HTTP 500 on invalid image API URL

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#306]
Reproduction: https://test.sram.surf.nl/api/images/collaborations/b7f621e3-de98-4de4-aca0-1573f4eb8319
Expected: HTTP 404
Observed: HTTP 500

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/8ca62f9e70e3c7efd7f8e7ad3d3b91cf45f1d4d2
