### ISSUE TITLE
Swagger: curl command in apidocs is missing 'bearer'

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#308]
Command displayed and executed by https://test.sram.surf.nl/apidocs is:

`curl -X GET "https://test.sram.surf.nl/api/organisations/v1" -H  "accept: application/json" -H  "Authorization: AFUFiO32aIfBgacjZSTR8Ww207gOy-bCQGqtXhEDs6pY"
`

This results in an error:

`
florisfokkinga@m123456 ~ % curl -X GET "https://test.sram.surf.nl/api/organisations/v1" -H  "accept: application/json" -H  "Authorization: AFUFiO32aIfBgacjZSTR8Ww207gOy-bCQGqtXhEDs6pY"
{"error":true,"message":"Unauthorized: https://test.sram.surf.nl/api/organisations/v1. IP: 10.24.0.20. Invalid username or password"}
`

Adding the word 'bearer' before the token fixes this:

`florisfokkinga@m123456 ~ % curl -X GET "https://test.sram.surf.nl/api/organisations/v1" -H  "accept: application/json" -H  "Authorization: bearer AFUFiO32aIfBgacjZSTR8Ww207gOy-bCQGqtXhEDs6pY"
{"category":"University","collaboration_creation_allowed":false,"collaborations":[],"collaborations_count":0,"created_at":1662372210,"created_by":"e84a37938bf633d1e08377ab36024398308a8e22@acc.sram.eduteams.org","description":"","id":133,"identifier":"9cbfddb8-1ef6-449a-be07-2896dc77ab6f","logo":"https://test.sram.surf.nl/api/images/organisations/042dac60-6862-452c-acfd-f838eb20da2e","name":"APIa","on_boarding_msg":"","organisation_memberships_count":0,"schac_home_organisations":[],"services_restricted":false,"short_name":"apia","updated_by":"e84a37938bf633d1e08377ab36024398308a8e22@acc.sram.eduteams.org","uuid4":"042dac60-6862-452c-acfd-f838eb20da2e"}
`

**Comment by oharsta** [comment]
@FlorisFokkinga The way this works, is that you have to add the `bearer` keyword yourself when you add the Authorization. This is a feature of the swagger framework and can not be - easily - changed.

**Comment by oharsta** [comment]
![Image](https://user-images.githubusercontent.com/530657/188455846-5d347bb1-c7d3-4859-9606-86927c529c47.png)
