### ISSUE TITLE
"Update" knop voor diensten werkt niet in SBS 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#312]
Als ik in SBS op een service scherm data wijzig (bv description of policy url), dan blijft de "Update" knop grijs en kan ik er niet op drukken.

**Comment by oharsta** [comment]
@baszoetekouw Zijn er rode menu-items links in het service overview scherm? De update knop is disabled als er foutieve / missende data is en de standaard seed bevat incomplete services. Heb je anders een voorbeeld URL voor mij op de test omgeving?

**Comment by baszoetekouw** [comment]
Inderdaad een missende security contact.  Ik zie nu ook dat het menuitempje waar data mist rood wordt, dus ik weet niet hoe ik dat heb kunnen missen...
