### ISSUE TITLE
Incorrecte tooltip bij koppelen diensten SURF-Org

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#314]
Een SURF Org mag geen niet-SURF-services koppelen.  Dit is correct geïmplementeerd, maar de tooltip klopt niet (en dat maakt het verwarrend):
<img width="1948" alt="Screenshot 2022-09-07 at 10 55 14" src="https://user-images.githubusercontent.com/1461740/188836330-3b262ecb-e67b-41eb-953f-0b4b611242da.png">

De tooltip heeft het over mandatory services, maar dat is helemaal niet van toepassing: hij moet gewoon zeggen dat de dienst niet gekoppeld mag worden omdat die niet voor SURF-organisaties beschikbaar is.

**Comment by FlorisFokkinga** [comment]
Can't reproduce due to bug:
- #339

**Comment by FlorisFokkinga** [comment]
This works for me. The grey buttons have a double meaning, though. We'll fix that with the new design system.
