### ISSUE TITLE
Long description, affiliation in table: limit length and word wrapping

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#319]
Sommige kolommen (bv Description van ene groep of CO, en Affiliation in een Org memberlist worden momentele heel lelijk afgebroken:

<img width="1618" alt="Screenshot 2022-09-07 at 13 58 48" src="https://user-images.githubusercontent.com/1461740/188873630-f92543bb-a178-48d5-84bb-0ce6bad83cb0.png">

Als ik hier de CSS `word-break` op `break-word zet`, ziet het er al veel beter uit:

<img width="1618" alt="Screenshot 2022-09-07 at 13 58 30" src="https://user-images.githubusercontent.com/1461740/188873424-42c07dc6-0bab-4a02-8d8e-3c6f4ba8cc0d.png">

Al is het dan weer niet mooi uitgelijnd.  

Ik zou willen voorstellen om de description in lijsten te beperken tot ene paar (2, 3?) regels, en die op woorden af te breken.  In het detailscherm kan dan de hele description worden getoond (en die wordt nu al correct afgebroken).

**Comment by baszoetekouw** [comment]
Let op, niet alleen beperkt tot bovenstaand scherm, maar alle descriptions in zo'n tabel

**Comment by oharsta** [comment]
![Image](https://user-images.githubusercontent.com/530657/216342954-a65135ae-5ff7-4f19-90ad-234602ab3a46.png)

Altering the number of lines, can be done here: https://github.com/SURFscz/SBS/blob/feature/design-system/client/src/stylesheets/forms.scss#L36

**Comment by FlorisFokkinga** [comment]
Cannot be tested, results in endless spinner.
