### ISSUE TITLE
Upgrade i18n-js to version 4

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#322]
Followup for #247 

We are at i18n-js version 3.9.2, and would liek to upgrade to version 4.0.2

> Upgrading i18n-js gives loads of warning and errors. Could not find any documentation on how to upgrade.

**Comment by baszoetekouw** [comment]
Does this help? https://github.com/fnando/i18n-js/blob/main/MIGRATING_FROM_V3_TO_V4.md

**Comment by oharsta** [comment]
The link is for migration of the Ruby / JS project https://github.com/fnando/i18n-js/. We use the companion JavaScript package: https://github.com/fnando/i18n. The version 4.0.2 of the Ruby project also upped the version of the I18n project and investigation is required as to the internal changes.
