### ISSUE TITLE
Upgrade react-router-dom to version 6

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#324]
Followup for #247

We would liek to upgrade react-router-dom to version 6.

>  Migration from 5 to 6 for react-router-dom is actually well documented, but also not trivial.

**Comment by baszoetekouw** [comment]
Deze moet ook nog een keertje...

**Comment by oharsta** [comment]
We have more than 140 occurrences of `this.props.history.push` which is not supported anymore in V6. The migration guide recommends using the `useNavigate ` hook, but all occurrences of `this.props.history.push` are in non-functional classes that extend `React.Component` and functional hooks can not be used in class components. 

There is a wrapper hook described here: https://reactrouter.com/en/main/start/faq#what-happened-to-withrouter-i-need-it. Everywhere where we use `this.props.history.push` we will have to use `router.navigate`, but we also need to update all the instantiations of every component that uses `this.props.history.push` to use the wrapper functionality.

**Comment by baszoetekouw** [comment]
See https://github.com/SURFscz/SBS/pull/1175
