### ISSUE TITLE
User who is a member of exactly 1 CO cannot request new collaboration

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#325]
If a user is a member of exactly 1 CO and doesn't have any other (Org/Service) roles or outstanding requests, they cannot request a new CO.

They cannot reach the normal home screen (/home) that contains the "Request CO"-button, but are always redirected to /home/collaboration/NNN.

I propose to show the regular home screen to users if they are allowed to requests new COs.  If possible, it would still be nice to use the CO screen of their single CO as the default landing page after login.

**Comment by baszoetekouw** [comment]
Ik denk dat @arnoutt en @FlorisFokkinga nog even moeten kijken of deze oplossing de beste is om deze functie bereikbaar te maken.

**Comment by oharsta** [comment]
@baszoetekouw Ik meen me te herinneren dat we dit tijdens het redesign ook hebben voorgelegd aan Edwin en we hebben destijds het "Request collaboration" toegevoegd aan het uitklapmenu rechts boven.
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/530657/189082918-fe462428-4a2e-47e8-8210-42253f58e564.png">

**Comment by FlorisFokkinga** [comment]
This button is hard to discover, but it's a fringe use case. I'd propose to leave it as it is.
