### ISSUE TITLE
Fallback MFA flow werkt nog niet goed

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#331]
Geobserveerd:
- bij inloggen op acc in SBS met eduid test hoeft geen TOTP te worden ingevuld
- bij inloggen op demo-sp acc met eduid test moet dan opeens wel een TOTP worden ingevuld
- na het invullen van de TOTP wordt je naar de verkeerde pagina teruggestuurd (lijkt de vorige login poging van SBS; ik kreeg bv "deze invitation bestaat niet meer" toen ik aan het inloggen was op de demo-sp).

**Comment by FlorisFokkinga** [comment]
I cannot reproduce this with certainty without knowing what the TOTP grace period is for SBS.

**Comment by baszoetekouw** [comment]
Dit is inmiddels gefixed (in v22 en v23)
