### ISSUE TITLE
Waar moeten service connection requests heen?

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#332]
Service connection requests gaan nu altijd naar de admin contact, en niet naar de beheerders van de dienst.  Is dat wenselijk?  
Ik had een mail naar de beheerders verwacht iig.

**Comment by FlorisFokkinga** [comment]
Ik zou haast zeggen dat dat een bug is.

**Comment by baszoetekouw** [comment]
Mails moeten sowieso naar de Service Admins (want ie zijn die enigen die er überhaupt iets mee kunnen).  Als er een Administrative Service Contact is, mag die op Cc.

Als er geen Service Admin is, is een mail naar allen de Admin Contact voldoende.

**Comment by oharsta** [comment]
And if there are no service admins and no admin contact, then we send the mail to one of the platform admins.

**Comment by baszoetekouw** [comment]
confirmed on acc
