### ISSUE TITLE
As a Org admin or platform admin, I want to be able to quickly view which COs I am a member of

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#334]
Ik kan in de paginated CO-lijst niet meer zien van welke CO ikzelf lid of admin bent.  Wellicht andere sortering of filtering aanbrengen?

**Comment by baszoetekouw** [comment]
Bij nader inzien, kan er een optie komen om die paginatie helemaal uit te zetten?

**Comment by baszoetekouw** [comment]
Dicussed with @arnout and @floris:
only a problem for org admins
actual issue is that a org admin can't easily find the CO he is a memeber or admin of.

So solution: make the membership status visibe in the list and add an option to sort or filter on the member status.

**Comment by arnoutt** [comment]
Minor addition: as platform/org admin, a label is shown for those COs of which I am an admin, but the label for those of which I am a member does not appear. Bug?

**Comment by oharsta** [comment]
@arnoutt If you add yourself to a CO or change your role, then the memberships are not correctly updated in your local cache. If you reload then also member labels are shown.
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/530657/191906125-514ad7aa-1811-4944-9d10-2c900be9e5a3.png">

**Comment by oharsta** [comment]
LOL, almost two years ago I removed the "Your role" header - that was sortable - with the remark _Can't decide - ask at the demo_. See https://github.com/SURFscz/SBS/commit/0d28df50b0c63bbf0ae38ef98b08690c736a094f. However I can't remember if I actually asked the question😀

**Comment by oharsta** [comment]
Show the your role sortable header in collaboration and organisation overviews: See  https://github.com/SURFscz/SBS/commit/e822e06f13b92fa3673b778c59100d6d5e248975

**Comment by baszoetekouw** [comment]
werkt op acc
