### ISSUE TITLE
Replace email, bin and puppet icons on member row with icons from the set

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#336]
![Image](https://user-images.githubusercontent.com/80269262/189355258-7575fe9b-68e1-4a55-85bc-543efeadd278.png)

If icons are not available yet, use these:

![Image](https://user-images.githubusercontent.com/80269262/190408248-ca079c27-e2ef-4da5-8f94-56c07c9b47b3.svg)

![Image](https://user-images.githubusercontent.com/80269262/190408388-6395f629-ff62-450a-8d45-99870cd061d8.svg)

![Image](https://user-images.githubusercontent.com/80269262/190408780-6f909a78-dbca-459f-a7b1-9119cbcbe352.svg)

**Comment by baszoetekouw** [comment]
✔ on acc
