### ISSUE TITLE
TEST: Endless spinner on making a service mandatory on impersonating org admin

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#339]
### Reproduction ###
1. Go to https://test.sram.surf.nl/organisations/131/admins
2. Impersonate Jane Doe
3. Go to 'AU university', 'Services' tab
4. Connect a service, either 'Storage' or 'SRAM Demo SP'

Expected: service made mandatory for all COs of this ORG
Observed: endless spinner, no change on page refresh

![Image](https://user-images.githubusercontent.com/80269262/190427775-a8efbd85-7f19-46fc-9076-ff67c6a620e7.png)

**Comment by oharsta** [comment]
Can be reproduced locally. On the test environment the AU University is marked as a SURF organisation. Only platform admins are allowed to connect services to SURF organisations. That the organisation admin Jane Doe is allowed to do so, is a bug in the GUI code.

**Comment by baszoetekouw** [comment]
No, Org admins should be allowed to connect SURF Services.

Everything regarding SURF orgs/service should be as usual with one exception: SURF Orgs (and COs in a SURF Org) are NOT allowed to connect to non-SURF Services.  

So the set of services that is available for SURF Orgs is limited, but connecting and requesting connections etc should be exactly the same as for regular Orgs.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/e0efdb1c4490bb771d0a4ddd5ba935de9415f4f5

**Comment by FlorisFokkinga** [comment]
Fixed.
