### ISSUE TITLE
Profile suspension and deletion email redesign

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#340]
- Change the content for emails that are sent to notice users before and on suspension and deletion of their identity.
  - Explain the functionality loss for non-web services
  - Notice the user in the suspension emails about deletion in 90 days
  - Offer the user a link to the identity removal modal on their profile page
- Change the configuration so the inactivity period is not extended by the reminder period.

![Image](https://user-images.githubusercontent.com/80269262/205326799-f1258b02-0bd6-454e-9291-8452d424937d.svg)

## Texts ##
INTRO {{ salutation }}, According to our information, it's been <days> days since you last used SURF Research Access Management. Because we do not want to store your information longer than necessary,

ACTIVATE If you want to keep using the services available through SURF Research Access Management, simply login using the link below or by going to {{ base_url }}.

DELETE NOW If you want to delete your profile right away, please go <account deletion modal>.

KTHXBYE If you have any questions, please let us know by replying to this email.
        Kind regards,
        SURF Research Access Management support

#### Suspend notice ####
INTRO
your profile will be marked inactive on <suspension date>. This means non-web services might not work anymore. On <deletion date>, your profile will be deleted.
ACTIVATE
DELETE NOW
KTHXBYE

#### Suspended ####
INTRO
your profile has been marked inactive, and non-web services might not work anymore. On <deletion date>, your profile will be deleted.
ACTIVATE
DELETE NOW
KTHXBYE

#### Deletion notice ####
INTRO
your profile will be deleted on <deletion date>.
ACTIVATE
DELETE NOW
KTHXBYE

#### Deleted ####
INTRO
your profile has been deleted on <deletion date>.
KTHXBYE

**Comment by arnoutt** [comment]
Ter inspiratie

![Image](https://user-images.githubusercontent.com/8791564/191045402-68c0c4f6-97ef-4d2d-94e2-d6bac117e26b.png)

**Comment by FlorisFokkinga** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/80269262/191223228-77fadb26-1193-4aa0-8abd-b3ec89bdbcb5.png">

**Comment by FlorisFokkinga** [comment]
- Change the content for emails that are sent to notice users before and on suspension and deletion of their identity.
  - Explain the functionality loss for non-web services
  - Notice the user in the suspension emails about deletion in 90 days
  - Offer the user a link to the identity removal modal on their profile page
- Change the configuration so the inactivity period is not extended by the reminder period.

![Image](https://user-images.githubusercontent.com/80269262/205326799-f1258b02-0bd6-454e-9291-8452d424937d.svg)

**Comment by oharsta** [comment]
There are now 4 mail templates:

- suspend_delete_notification.html - Deleted
- suspend_delete_warning_notification.html - Deletion notice
- suspend_suspend_notification.html - Suspended
- suspend_suspend_warning_notification.html - Suspend notice

**Comment by baszoetekouw** [comment]
getest op acc
