### ISSUE TITLE
Clarify CO label filter drop down

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#342]
On top of the CO list, a drop down menu allows users to filter de CO list for specific labels. However, the drop down contains no explanation or indication what it does, so it's unclear for users what it is.

Also, should regular users be able to filter based on labels as well? Or just org admins?

**Comment by FlorisFokkinga** [comment]
I don't see any harm in regular users viewing what labels organisations have assigned to COs they are (at least) member of.

**Comment by baszoetekouw** [comment]
It's indeed clearer like this.
![Screenshot 2022-11-15 at 10 29 46](https://user-images.githubusercontent.com/1461740/201882890-6ad10f71-fd70-4b33-a39e-906525761645.png)
