### ISSUE TITLE
Review expiration date and last activity column header and content format

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#344]
- Kolomtitel Expiration date: **Status:** “active” ****“expires in 59 days” | “expired”
- Kolomtitel Last activity: **13 days ago | xx weeks ago | xx months ago**

**Comment by FlorisFokkinga** [comment]
## Current situation ##

### CO list ###

![Image](https://user-images.githubusercontent.com/80269262/191779241-75b80a50-c4e1-45cf-bc03-0c2d94031991.png)
![Image](https://user-images.githubusercontent.com/80269262/191779281-ca861911-0de8-4ff2-a8c4-4bc2b05e9b71.png)

### Members list ###

![Image](https://user-images.githubusercontent.com/80269262/191779598-4026bb40-8a1d-477c-aaf5-e26138aee94e.png)
![Image](https://user-images.githubusercontent.com/80269262/191779617-1d0552d6-40fd-47d6-b0e8-052bfaf6c086.png)

**Comment by FlorisFokkinga** [comment]
To improve readability we revise the expiration texts and dates
- Shorten texts
- Use relative timestamps
  - Is there a default or standard for relative timestamps?
  - Sorting of relative timestamps should be chronological

#### CO ####
Expires in / Verloopt over
1 day
2 weeks
1 year
never

#### CO ####
Last activity / Laatst actief
Today
This week
This month
2 months ago
11 months ago
1 year ago


#### Membership ####

Expires / Verloopt (black, yellow when shortly)
in 1 day
in 2 weeks
in 1 year

Expired / Verlopen (red)
1 day ago
2 weeks ago
1 year ago

Never expires / Verloopt nooit

#### Invites ####
Invited on Sep 22 / Uitgenodigd op 22 sept
Invite expired / Uitnodiging verlopen



![Image](https://user-images.githubusercontent.com/80269262/191900489-3be798fa-f47f-4898-bf79-830baf098db4.png)



#### CO header ####
Expires in 3 months
Empty when no expiration date is set.

![Image](https://user-images.githubusercontent.com/80269262/191901194-959bbf8b-607c-458c-a2df-62137f2481ed.png)

**Comment by FlorisFokkinga** [comment]
* Make exact expiry date of a CO visible in the header
* Never expires: consider 'Set expiration'

**Comment by oharsta** [comment]
@FlorisFokkinga  For consistency - I will use the https://www.npmjs.com/package/timeago.js/v/4.0.0-beta.3 library - I would suggest that we format the last activity date the same as the Expired value. 
**Last activity**
8 hours ago
1 day ago
2 weeks ago
1 year ago 

Ok?

**Comment by oharsta** [comment]
@FlorisFokkinga , with the timeago.js library it is very easy to support different formats for different purposes. You can configure it the way you want in the locales. See https://github.com/SURFscz/SBS/blob/main/client/src/locale/en.js#L2033.

**Comment by baszoetekouw** [comment]
checked on acc
