### ISSUE TITLE
Zoeken in audit log werkt niet goed

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#349]
Ik wil zoeken op (bv) CO shortname of service shortname, maar dat geeft geen hits.

**Comment by oharsta** [comment]
The audit logs only contain the name of the object (if name is an attribute) and the changes made (if it is an update). Not the entire state is captured in an audit_log record when doing an update. Therefore the short-name is not present in the actual audit_log table, and searching for it is currently not possible. This implementation can of course be changed, but then we would need to define which fields are searchable per object type (or store the entire state as JSON in the audit_log record, but that would also traverse child objects)

**Comment by baszoetekouw** [comment]
ok, but search for displayname also doesn't really work.  For example, in prod I would expect that a search for "Bas" would return quite a few entries.  Instead, I get only a very limited amount of entries, and when I switch the number to "all", I get a timeout and an error (probably a query/http timeout).

Could it be that the page tries to load _all_ entries and only after that filters on the client side?  Because sql queries like 
```sql
select * from audit_logs al 
where target_name like '%bas%'
order by id desc limit 500;
```
are quite fast (~300ms).

Also, maybe we could allow searching the `state_before` and `state_after` fields?  That would be crude, but easy.

**Comment by oharsta** [comment]
The search is done client side, soo that explains it. I'll change that.

**Comment by baszoetekouw** [comment]
perfect!
