### ISSUE TITLE
Niet alles wordt in audit_log geregistreerd

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#350]
Ik zie in de audit logs niets over:
 - koppleen diensten aan COs
 - aanmaken van groepen in COs
 - aanmaken van servicegroepen in COs

**Comment by oharsta** [comment]
@baszoetekouw If I go to https://test.sram.surf.nl/system/activity and select `Service groups` or `Group` and click Fetch, then I see new, updates and deletions. Also when I connect a Service to a CO (from the CO services tab) then this is also captured in an audit_log. Or do you mean a different audit_log?

**Comment by baszoetekouw** [comment]
Idd, ik keek scheel.  Ik was in de database aan het kijken, maar had niet gezien dat ik nog een filter op mijn kolommen had staan...
