### ISSUE TITLE
SRAM GUI accepts typing characters outside the range [a-z][0-9] as a first character

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#351]
When creating a new group SRAM allows, as a first character only, any character outside the range of [a-z][0-9]. The `$test` can be typed, whereas `$$test` cannot. Hitting 'save' seems to add `test` as a new group rather then `$test`, however not error or warning is displayed.

**Comment by FlorisFokkinga** [comment]
What is the expected behaviour? That typing illegal characters is not possible?

**Comment by baszoetekouw** [comment]
works on acc
