### ISSUE TITLE
SFO for users without uid or sHO

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#354]
Currently, if a user is redirected to the SSID SFO endpoint, but SBS has not received a uid (or sHO, I assume), SRAM sedns teh following subject in the SFO request:
```
   <saml:Subject>
        <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">urn:collab:person:uniharderwijk.nl:None</saml:NameID>
        <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer" />
    </saml:Subject>
```
Note the `None` in the NameID.

While this gracefully fails (SBS correctly interprets the SSID SAML error message and falls back to its internal TOTP implementation), it it quite invisible to the user and hard to debug.  

I suggest two changes:
 - before sending a user off to ssid, check if we have the required info; if not, don't send the user to ssid at all, but treat this as if we had received an error form ssid (and continue with TOTP).  This prevents spamming ssid with unknown users and also prevents any users named "None" to be annoyed.
 - clearly log this issue as an error (it indicates a configuration error, in SBS or at the IdP)

**Comment by oharsta** [comment]
@baszoetekouw Currently the NameID is constructed like `name_id = f"urn:collab:person:{user.schac_home_organisation}:{user.home_organisation_uid}"`. See https://github.com/SURFscz/SBS/blob/main/server/auth/ssid.py#L27. 

Is this correct? Or do we need to use the `uid` instead? If it correct we need to check if `schac_home_organisation` and `home_organisation_uid` are not `None`.
