### ISSUE TITLE
SCIM support

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#358]
See https://wiki.surfnet.nl/display/coininfra/SCIM+User+Stories

- [x] User delete - send apply_changes_all_membership_collaboration, send delete_user SCIM call to all connected services?
- [x] SCIM endpoint  /api/scim/Users 
- [x] SCIM endpoint  /api/scim/Groups
- [x] Sync endpoint on mock-scim to fetch (and sync) users and groups
- [x] Swagger endpoint descritions

**Comment by baszoetekouw** [comment]
@okke, kan deze dicht?
