### ISSUE TITLE
As a future service admin I want to be able to request a service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#361]
We hebben nu https://wiki.surfnet.nl/display/SRAM/Service+registration+form 
Dar moeten we nu alles 2x overtiepen: 1x in SBS en 1x in EduTeams.  Dat kan makkelijker

De oplossing is om het direct in SBS in te typen zodat we de data niet meer in SBS hoeven over te typen en ook de service admin meteen goed staat.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw Now, eduTEAMS creates the entity ID or SAML equivalent. Would you propose SBS does that instead?

**Comment by FlorisFokkinga** [comment]
Specify the form.

**Comment by baszoetekouw** [comment]
And we need to consider how the flow should be exactly?  Shoudl this create a "draft" Service, to be approved by platform admins?

**Comment by baszoetekouw** [comment]
Lage prio.  Oppakken als we uberhaupt naar self-service service signup gaan kijken.
