### ISSUE TITLE
Wrong message when search COs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#363]
When searching COs in an Org (e.g., on https://test.sram.surf.nl/organisations/139/collaborations) and no CO is found, the message "There are no collaborations yet..." is shown.  Instead, it should say "No collaborations found".
![Screenshot 2022-10-18 at 12 02 02](https://user-images.githubusercontent.com/1461740/196400398-c4a61051-78ce-4329-aaa1-cafede7d16df.png)

**Comment by baszoetekouw** [comment]
De huidige oplossing (zie screenshot) lijkt me niet correct.  

![Screenshot 2022-11-15 at 11 02 49](https://user-images.githubusercontent.com/1461740/201890769-d60ebb11-5be3-4f5b-bec6-f63144ac087e.png)

We moeten onderscheid maken tussen deze twee gevallen:
 - er zijn geen COs (in de Org); in dit geval is de huidige melding correct
 - er zijn wel COs (in de Org) maar het huidige filter matcht niets; in dit geval moet de melding zijn "no matching COs found" oid.

(of als alternatief moeten we een tekst bedenken die in beide gevallen voldoet)

**Comment by mrvanes** [comment]
Werkt
