### ISSUE TITLE
Mail voor uitnodigen org herzien

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#364]
Ziet er nu zo uit:
![Screenshot 2022-10-18 at 14 35 35](https://user-images.githubusercontent.com/1461740/196430970-53ce3fb4-bcc5-450b-93ce-354a5d6f8e4b.png)

maar het is niet duidelijk wat "join organization X" dan betekent.  Maak duidelijk dat het erom gaat dat je admin of manager wordt.

**Comment by FlorisFokkinga** [comment]
'Join' only works for COs, not for organisations and services (that would be 'become admin'), and perhaps for platform admins.

**Comment by FlorisFokkinga** [comment]
Fixed in #433.
