### ISSUE TITLE
As a service owner I want to know all valid user ssh keys

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#365]
Voor een alternatieve implementatie van de PAM weblogin module heb ik een lijstje van alle geldige ssh keys van de gebruikers van alle CO's waar de service aan gekoppeld is nodig. Naast ssh keys is het uiteraard ook handig om dan ook wat meer info terug te geven voor eventuele andere services.

**Comment by baszoetekouw** [comment]
Werkt op acc:
```
curl -H "Authorization: Bearer ABCDE_mijn_key_XYZ" https://acc.sram.surf.nl/pam-weblogin/ssh_keys
```

We moeten dit wel nog ergens documenteren.  De rest van de API staat nu hier https://github.com/SURFscz/pam-weblogin/blob/main/doc/protocol.md maar misschien moet dit dichterbij SRAM worden gedocumenteerd.

Verder in #397
