### ISSUE TITLE
As a user, I want to see who or what organisation needs to approve my CO request, so I know who to contact

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#367]
This screen, as shown to the requester, doesn't make clear who needs to approve the collaboration request. There is no detail page for the requester.

![Image](https://user-images.githubusercontent.com/80269262/198239390-4ca58950-f172-4ca2-97a7-97d3f5882b38.png)

**Comment by baszoetekouw** [comment]
What information should we show?

**Comment by FlorisFokkinga** [comment]
Assuming this table shows the same columns for the requester and admin, add a column 'Institution' directly right to the 'Collaboration name' column.
If that's not sufficiently clear, we can add a help tooltip later.

**Comment by oharsta** [comment]
Added the Institution column, but right from the username to be consistent with the other tables.

**Comment by FlorisFokkinga** [comment]
I don't get this. The insitution should be the one to approve the request, not the user's institution.

**Comment by oharsta** [comment]
I made a mistake in my head - did not read the issue thoroughly.

**Comment by FlorisFokkinga** [comment]
It's not there in the requester's table.


![Image](https://user-images.githubusercontent.com/80269262/222467475-63eb5b80-2da4-45dc-ad96-c4b309af8b52.png)

**Comment by oharsta** [comment]
![Image](https://user-images.githubusercontent.com/530657/223710877-6f894bb3-c955-465e-92fb-e7ff728c1667.png)

**Comment by baszoetekouw** [comment]
Confirmed.
