### ISSUE TITLE
main.js heel groot

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#371]
main.js is inmiddels bijna 3MB groot; Is er geen manier om daar iets aan te doen?  Of desnoods om hem op te splitsen in kleienre files (die de browser dan parallel binnenharkt)?

**Comment by oharsta** [comment]
https://reactjs.org/docs/code-splitting.html#route-based-code-splitting

**Comment by baszoetekouw** [comment]
Een andere oplossing is wellicht om de grote main.js file als precompressed file te serveren 
(zie https://docs.nginx.com/nginx/admin-guide/web-server/compression/ en https://blog.llandsmeer.com/tech/2019/08/29/precompression.htmlen  http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html of https://github.com/google/ngx_brotli)

@mrvanes zou jij dat eens kunnen proberen?

**Comment by baszoetekouw** [comment]
@oharsta ik snap denk ik niet zo goed wat er op die react-pagina staat.  Denk je dat het doenbaar is om het in react op te lossen?  Want die compressie-route lijkt ook wel zinvol.

**Comment by oharsta** [comment]
@baszoetekouw Het is wel doenbaar, maar niet triviaal. Als we het kunnen oplossen dmv compressie heeft dat mijn voorkeur.

**Comment by baszoetekouw** [comment]
checked on acc.  Large js/css files are gzip-compressed, small ones aren't.  For main.js, this reduces the on-the-wire size to about 800kB.
