### ISSUE TITLE
Fix code scanning alert - Full server-side request forgery

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#377]
Tracking issue for:
- [x] https://github.com/SURFscz/SBS/security/code-scanning/30

Even though this API is in principle only called by trusted parties, it would be good to fix this.

So we should make sure that 
 - the provided url is "sane" (in some sense, it's probably ok to make sure that it is a proper url, that is http/https, is reasonable in length, doesn't have any query parameters and doesn't have "weird" chars).
 - the image we fetch is an actual image and is reasonable in size.  As a reference, the largest image currently in the DB is 280kB base64, and the typical image is 30kB, so an upper limit of 300kB seems more than ok.  Or is the fetched image sanitised anyway, before we use it?

**Comment by oharsta** [comment]
The fetched image is stored and only used to display as `img src="data:image/jpeg;base64,"`. If the image is not valid the browser displays a broken link.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/3294c56f22e786cabd28076ba28bf68c3fa0ce71
