### ISSUE TITLE
Fix code scanning alert - Information exposure through an exception

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#382]
Tracking issue for:
- [ ] https://github.com/SURFscz/SBS/security/code-scanning/28

I'm not entirely sure if this is a valid issue; are these stack traces really returned in the json output of the API, or are they only sent by emails to sram-logs?

**Comment by oharsta** [comment]
The stack-trace is not returned in the response. It is only included in the email we optionally send.
