### ISSUE TITLE
CO labels not exposed in Org API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#385]
CO labels are currently not visible in the Org API.

Specifically, `/api/collaborations/v1/{identifier}` doesn't return the labels in the json response

Also, please document in teh Swagger docs how to specify a `tag` input is in POSTs to `/api/collaborations/v1`.  The syntax (e.g., `"tags":[{"label":"hoilabel","value":5}]` is not obvious.
Maybe we could change this to something a bit more friendly?  I.e. simply specifying `"tags": ["tag1","tag2"]` and letting SBS figure out whether it's new and what the identifier is?

Please add this functionality.

**Comment by mrvanes** [comment]
Tags are now returned like this in GET /api/collaborations/v1/{coid}
```
"tags": [
        {
            "id": 6,
            "tag_value": "label_1"
        },
        {
            "id": 7,
            "tag_value": "label_2"
        }
    ],
```
