### ISSUE TITLE
Viewing user details, for some organisations, the org ID instead of the org name is displayed in the breadcrumbs

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#392]
For example: https://acc.sram.surf.nl/users/171/details/21

![Image](https://user-images.githubusercontent.com/80269262/201668508-0ae6dda4-f8c8-4126-8354-06e8d2994c9d.png)

**Comment by oharsta** [comment]
@FlorisFokkinga Can you also reproduce on the test env? Or slack me a mujina user with platform-admin role? Otherwise I can't reproduce?

**Comment by oharsta** [comment]
This happens when you're platform admin and you're not a member of this organisation. It uses the current_user organisation memberships to retrieve the organisation name with a fallback to the id of the organisation.
