### ISSUE TITLE
Adjust "where we collaborate" if no services are connected

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#400]
Currently looks weird: 

![Screenshot 2022-11-16 at 10 39 21](https://user-images.githubusercontent.com/1461740/202145262-78c4e98e-9db3-48a3-9e2d-15997f580d36.png)

**Comment by baszoetekouw** [comment]
beter oplossing: "(0 services)" weglaten als titel in eronder zetten "no services connected yet"

**Comment by mrvanes** [comment]
Where we collaborate was removed completely, instead of only (0 services):
![image](https://user-images.githubusercontent.com/1901782/207081240-b4c9073c-4c2c-41c2-9b4b-f1502d4bf031.png)

**Comment by oharsta** [comment]
I overlooked the second comment  from Bas.

**Comment by baszoetekouw** [comment]
Tested the updated.  Looks good now!
