### ISSUE TITLE
Allow uploading of webp images

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#401]
Webp images are supported by SBS, but by default the upload window doesn't allow me to select them because the browser thinks that they are not of a "supported type".

![Screenshot 2022-11-16 at 10 44 23](https://user-images.githubusercontent.com/1461740/202146239-2474982e-917c-4b32-82a1-98d1e0f6877e.png)

Please adjust this.

**Comment by mrvanes** [comment]
Gefixt
