### ISSUE TITLE
Disallow specification of non-routable ipv4 addresses in ldap ACLs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#402]
Please reject the special-use ipv4 ranges in LDAP ACLs as sepcified here: https://en.wikipedia.org/wiki/IPv4#Special-use_addresses

**Comment by oharsta** [comment]
Use the CSV files from https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml and 
https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

**Comment by baszoetekouw** [comment]
works
