### ISSUE TITLE
Allow disabling of ldap for a service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#403]
nader uit te werken: wat betekent dit precies?

Voordelen: schaalbaarheid/performance van plsc sync
Overzichtelijkheid interface voor Service admin

pas op dat interne ldap-uuids enzo niet veranderen als je de ldap uitzet en dan weer aanzet

**Comment by arnoutt** [comment]
Conclusie: gaat om UI (service admin options).

**Comment by baszoetekouw** [comment]
Simople solution: remove ldap password if ldap service is disabled

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/3fc7a6a107130132949bf4f9fde3508b40082a9d

**Comment by mrvanes** [comment]
Waiting for https://github.com/SURFscz/plsc/pull/105

**Comment by baszoetekouw** [comment]
Werkt niet helemaal als bedoeld:
 - bij het disablen van ldap wordt de tree leeggemaakt
 - maar het adminaccount blijft bestaan en wachtwoord blijft zoals het was.

dat laatste moet eigenlijk niet.  Maar ik zal daar een aparte story voor maken: https://github.com/SURFscz/plsc/issues/106
