### ISSUE TITLE
Platform consent screen slightly too narrow

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#404]
![Screenshot 2022-11-16 at 11 22 54](https://user-images.githubusercontent.com/1461740/202155190-32e8c0b8-feed-4a21-931d-f14e2971f8c0.png)

**Comment by baszoetekouw** [comment]
makkelijke oplossing: tekst aanpassen.  Is sowieso aan de formele kant.

**Comment by arnoutt** [comment]
Let wel, dit vinkje + text komt vaker voor (ook bijv. bij het CO join screen)

**Comment by arnoutt** [comment]
Text suggestions:

[EN]: "I accept the acceptable use policy"
[NL]: "Ik accepteer de acceptable use policy"

**Comment by FlorisFokkinga** [comment]
Fixed by SDS.

**Comment by baszoetekouw** [comment]
ziet er goed uit

![Image](https://github.com/SURFscz/SBS/assets/1461740/25a3b84e-f974-458d-a0b9-fc38059be4ca)
