### ISSUE TITLE
As a Service Admin, I want to be able te create and manage Service Groups by myself without bothering a platform admin

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#406]
Currently, only pltaformadmins can create service groups.  Pleas enable this also for Service Admins.

**Comment by baszoetekouw** [comment]
@FlorisFokkinga @arnoutt mee eens?

**Comment by baszoetekouw** [comment]
ja

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/4f24f7e4e20485260dc953e5ac162efb3997d473

**Comment by mrvanes** [comment]
Werkt
