### ISSUE TITLE
Move the API key (userToken) tab to the service, so a user can view their API keys on a logical place

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#411]

**Comment by oharsta** [comment]
A regular member of a collaboration does not have a services tab. The only way to see the (pretty empty) detail page of a service for regular member is to go to the instructions. Let's discuss how we GUI-wise can implement this.

![Image](https://user-images.githubusercontent.com/530657/202738747-8ec3ad08-b86e-416e-b798-de7321c1cc5c.png)

**Comment by oharsta** [comment]
Decided to duplicate the tokens tab to the service detail page. Later we decide what the final UI solution will be
