### ISSUE TITLE
Add the landing page explainers to the welcome pages

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#412]
Some explanation was added to the landing page (for non-authenticated users).

![Image](https://user-images.githubusercontent.com/80269262/205659863-9227b949-1d82-41bb-b0af-397f5f833034.png)

Please also add these to the welcome pages (for authenticated users without any membership or admin role), for instance:

![Image](https://user-images.githubusercontent.com/80269262/205660048-cadae9ce-57da-40a4-b39d-71781cc2591b.png)

**Comment by oharsta** [comment]
@FlorisFokkinga Do we want to add all info sections (Create, Invite, Join and Collaborate) to the bottom (?) of the welcome page? Do we also want to show this if a user can request a collaboration?

**Comment by oharsta** [comment]
Added all info blocks. Looks ok.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/530657/205914788-4f8a67ce-2b9b-46c6-8105-1ab728811bc2.png">

**Comment by mrvanes** [comment]
Gecheckt
