### ISSUE TITLE
As a user, I want a GDPR compliant option to export my data from the profile page

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#413]
Split from #267

**Comment by mrvanes** [comment]
Ik krijg een Network error in Chrome, maar geen foutmelding in de netwerk of console tab en ook geen fout in de SBS logs?
![image](https://user-images.githubusercontent.com/1901782/207083585-c71787f3-d3b3-401b-adc8-2cc1bb2caee3.png)

**Comment by oharsta** [comment]
Dat is gek. Bij mij werkt het op de test omgeving. Krijg je wel de save dialog van Chrome?

**Comment by mrvanes** [comment]
Ja, alles is normaal tot ik op 'Save' druk en dan zie ik die error onderin.
Het rare is dat het nu wel lukt, als ik naar de Profile page ga maar de _tweede_ poging mislukt.

**Comment by oharsta** [comment]
Ik kan het zo vaak doen als ik wil, en ik krijg geen errors op test.

**Comment by mrvanes** [comment]
Op test gaat het bij mij ook goed? Zal wel iets met de dockers zijn dan?
