### ISSUE TITLE
As a user, when creating an object, I want to know what the requirements for the shortname are

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#416]
- note the requirements for the shortname in the ui
 -  autogeneratd a proposed shortname from the displayname

**Comment by oharsta** [comment]
The current implementation notes the requirement for the short_name. Is that not enough?

![Image](https://user-images.githubusercontent.com/530657/202736982-b257a2f8-68f6-458e-8b25-5fd0a53076da.png)

**Comment by oharsta** [comment]
Decided to leave as-is for now.
