### ISSUE TITLE
As a member, I want my membership request to be deleted on becoming member by accepting an invitation

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#418]
When a user first requests membership, and then gets invited, the membership request remains.

![Image](https://user-images.githubusercontent.com/80269262/194560760-2d4f6b7a-55c5-4094-854a-1c480951d544.png)

![Image](https://user-images.githubusercontent.com/80269262/194560781-0bbaeb75-64ca-4da5-85e6-58251344cd44.png)

**Comment by mrvanes** [comment]
Gecheckt
