### ISSUE TITLE
Improve welcome pages layout and text

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#419]
## Current ##
![Image](https://user-images.githubusercontent.com/80269262/194337066-ad7dbb8e-4c1c-4281-b6e8-986cdf6d77ca.png)

**Comment by baszoetekouw** [comment]
Lage prio.  Misschien even wachten op nieuwe design.

**Comment by FlorisFokkinga** [comment]
Check out the current state.

**Comment by FlorisFokkinga** [comment]
### Redesign ###
There are three possibilities: user can create CO, request a CO or can't do anything. In all cases, first point the user to their invitation email, if any.

![Image](https://github.com/SURFscz/SBS/assets/80269262/d5c62e50-e00d-4060-b2af-7e126e1c0268)


```
Hi Floris,

With <strong>SURF Research Access Management</strong> you can login to research services and collaborate with other researchers.

Joining a collaboration
Have you been invited to join a collaboration? Join by using the link from the invite email.

Creating a collaboration
You have logged in via <strong>eduid.nl</strong> which does not allow you to create a collaboration. If that is unexpected, please contact <a href="mailto:sram-support@surf.nl">sram-support@surf.nl</a> for help.
```

![Image](https://github.com/SURFscz/SBS/assets/80269262/96f30ccb-8923-4e82-bd3f-b59c70771c69)

```
Creating a collaboration
You have logged in via <strong>Harderwijk University</strong> which allows you to create a collaboration, to which you can connect services and invite researchers.
```

![Image](https://github.com/SURFscz/SBS/assets/80269262/a03efefd-363e-41d4-9fd0-ef7b5152be7e)


```
Creating a collaboration
You have logged in via <strong>Harderwijk University</strong>, and you can request them to create a collaboration for you. After they approve your request, you can can connect services and invite researchers.
```

**Comment by FlorisFokkinga** [comment]
As requested, I've added a header (Message from <organisation name>) in case the organisation has set an on-boarding message. The button should be placed below the onboarding message. The current styling of the message, with a border, seems good to me.

**Comment by FlorisFokkinga** [comment]
Please note that the on-boarding message was move to the request/add CO screen.
- #900
