### ISSUE TITLE
As a CO admin, I want to easiliy see what labels are assigned to my CO

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#422]
CO labels zitten nu erg verstopt: ze zijn alleen zichtbaar in het edit-scherm van de CO. 
Het zou handig zijn als ze ook zichtbaar zouden zijn in het CO-lijst van de Organisatie, en misschien in de CO-header.

**Comment by baszoetekouw** [comment]
@FlorisFokkinga wat vind jij hiervan?

**Comment by FlorisFokkinga** [comment]
Labels are also visible as filters on the CO tab of an organisation or user.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/80269262/204256357-261755fd-5a98-4fb4-b610-f4b83778c335.png">

Would adding them to the header of a CO (except for the member view) suffice?

**Comment by baszoetekouw** [comment]
Kolom erbij in het Org scherm met Collaboration is niet praktisch.  Kan misschien later.

Hoeft niet prominent zichtbaar te zijn voor reguliere CO-gebruikers (alleen voor admins).
Wel toevoegen in de details pagina van de CO.

Even wachten tot na implementatie het nieuwe designsystemen en hoe de properties van COs daar eruitzien.

**Comment by FlorisFokkinga** [comment]
Story for org admins split to
- #810

**Comment by FlorisFokkinga** [comment]
Please also change the look of the labels on the CO edit screen.
