### ISSUE TITLE
url check in client is niet strict genoeg

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#428]
NA invullende Service form kreeg ik een "this is embarrassing" error, mijn formulier werd leeggemaakt, en de server zei:
```
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 149, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/service.py", line 279, in save_service
    valid_uri_attributes(data, URI_ATTRIBUTES)
  File "/opt/sbs/sbs/server/db/defaults.py", line 64, in valid_uri_attributes
    raise ValueError(f"{uri} is not a valid uri")
ValueError: https://auth.tudelft.nl/auth/realms/sram/protocol/saml/clients/amazon-aws  is not a valid uri
```
(er lijkt een extra spatie achter de url te staan)

Best vervelend, vooral omdat mijn data ook echt weg was.  

Kun je iets slims inbouwen in de entityid-veld-check die iig checkt dat er geen spaties voorkomen?

**Comment by mrvanes** [comment]
De spaties hebben geen invloed op de matching, maar het lijkt me niet handig ze op te slaan?

**Comment by oharsta** [comment]
Ik strip de spaties van de URL-velden eraf op de server, maar (verwarrend doordat entity-id wordt genoemd in de beschrijving) het veld entity-id is een free-format veld. Daar zit geen input validatie op, maar ik ben het met je eens dat het niet handig is om de spaties op te slaan.

**Comment by mrvanes** [comment]
Fix werkt nu ook op entity-id.
