### ISSUE TITLE
Split text for invite acceptation pages for collaboration member/admin, organisation admin and service admin

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#433]
The problem is that the current text use the term 'join', which is appropriate for membership. For admins, 'become an admin of' is much better.

**Comment by mrvanes** [comment]
The dialogs work, but the mails don't reflect the changes.

**Comment by oharsta** [comment]
@FlorisFokkinga Is changing the emails in scope for this issue? If so, do you want to update the mails or shall I do it?

**Comment by FlorisFokkinga** [comment]
I haven't found the time. If you can, please do.

**Comment by oharsta** [comment]
See https://github.com/SURFscz/SBS/commit/a1592d8b6dd63e98a60eb6364994740d661c2c7e

**Comment by baszoetekouw** [comment]
perfect!  werkt
