### ISSUE TITLE
Layout issue by the lange AUP url

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#435]
als de AUP url lang is, wordt de header van Services opeens te breed en valt het menu rechts van de pagina:

![Screenshot 2022-12-06 at 15 42 45](https://user-images.githubusercontent.com/1461740/205942609-8288568e-41c4-411c-acca-203ca4dc5372.png)
![Screenshot 2022-12-06 at 15 43 46](https://user-images.githubusercontent.com/1461740/205942629-0976b303-df60-463b-a3d6-39876748bf3c.png)

**Comment by mrvanes** [comment]
Checked by Martin
