### ISSUE TITLE
Service Groups herzien

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#437]
Service groups need to be more tightly coupled the templates set by the Service admin.  Specifically:
 - if short name/description changes, this needs to be changes in the service groups in all COs
 - if a new Service group is added, it need to be added to all relevant COs
 - Service groups also need to be provisioned and updated in COs which are already connected to the service but do not have the service groups yet

See also #230 and #425.

**Comment by oharsta** [comment]
@baszoetekouw Is a CO admin allowed to change anything in a Group derived from a Service Group? The CO-admin can add  members if the Group is not marked as `Auto-provision collaboration members`, but can the CO admin also change this setting? And is it allowed to change the Description by the CO admin (although this will be overridden when de Service admin changes the description of the Service Group)?

**Comment by FlorisFokkinga** [comment]
I'd say the CO admin controls who is member of the group, and the service admin controls all other group properties and they cannot be changed by the CO admin.

I  think we should keep the ``Auto-provision collaboration members`` as an exception: that value can be changed by both the CO admin and the service admin.

**Comment by arnoutt** [comment]
Agreed, but one extra remark: if we now choose to implement that CO admins are no longer able to modify certain properties of the service group (name, description), then I would like some visual mark that a service group is a special group. We can do this later too (I don't have a good idea yet), or we can opt to implement the CO-admin-is-not-allowed-to-modify-service-groups later (when the design is ready).

What do you think @FlorisFokkinga and @baszoetekouw?

**Comment by FlorisFokkinga** [comment]
Sure. I've created an issue for this:
- #518

**Comment by baszoetekouw** [comment]
Gestest, zie #562
