### ISSUE TITLE
SCIM Groups: Delete of Group is failing

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#440]
Deleting a group in SRAM is not deleting the group in the remote SCIM Server

**Comment by HarryKodden** [comment]
Hmm, when I now delete 1 group, alle groups and all users gets removed in SCIM endpoint...

**Comment by oharsta** [comment]
@HarryKodden Can you write down the steps using the test seed data? If I clear the stats in http://localhost:3000/system/scim and sweep the Cloud service then 2 groups are provisioned to the Cloud service (uva:research and uva:research:science). If I then delete the science group in uva:research CO and refresh the stats, then only one group remains and I see the DELETE /api/scim_mock/Groups/3709480a-4694-4eb2-8d80-a7586589d06a in the http_calls for Cloud.
