### ISSUE TITLE
SCIM Groups: Deleting a Collaboration member not updating SCIM

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#442]
When User X is member of a Group in a Collaboration. 
He is (by definition also) member of the Collaboration.
When X is removed from the Collaboration, he is automatically also removed from the Group in SRAM
However is update is not triggering an SCIM Delete of that group Member in the remote SCIM server

**Comment by oharsta** [comment]
Confirmed  and solved in feature/scim-sweep
