### ISSUE TITLE
SCIM Users: Delete of Collaboration member not deleted in SCIM

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#443]
When deleting a member of a CO is deleted, he is not deleted in the SCIM Users endpoint of the remote SCIM Server

**Comment by oharsta** [comment]
@HarryKodden This is somewhat tricky. We do SCIM PUT the CO (and underlying Groups) to update the memberships, but we don't delete the user as this user might be in another Group or CO of this Service. So we need to check if this user is orphaned in the SCIM remote (e.g. has no more CO memberships in the connected CO's.).

The delete membership is now handled in a generic way, so we need to change this.
