### ISSUE TITLE
When a join request is approved, live updates are not sent

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#446]
When approving a join request, the requesting user's page does not get live updates (i.e., the join request keeps status "open" and the CO membership is not shown).

To reproduce:
 - submit join request and keep https://acc.sram.surf.nl/home/joinrequests pen
 - accept the join request as the CO admin in another browser
 - observe that the first browser is not updated.

**Comment by mrvanes** [comment]
Checked by Martin
