### ISSUE TITLE
CO welcome screen text

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#447]
![Screenshot 2022-12-13 at 13 32 14](https://user-images.githubusercontent.com/1461740/207318994-47a893a6-79f0-4eaf-bcbb-111c879409c9.png)

@arnoutt Klopt dit welkom schermpje wel?  Je moet ergens mee akkoord gaan, maar het is niet duidelijk waarmee dan.  Komt dat omdat er geen diensten zijn? Ook als er wel AUPs zijn lijtk em de formulering niet helemaal correct: je moet akkoord gaan mat de AUP, maar de PP is alleen ter info toch?

**Comment by arnoutt** [comment]
Kan dit niet reproduceren, volgens mij is het dan ook opgelost? Hieronder een voorbeeld van hoe het scherm eruit ziet als er wel een privacy policy is maar geen AUP. Akkoord geven is dus niet nodig.

![Image](https://github.com/SURFscz/SBS/assets/8791564/48e981ba-8bc9-42d2-b05f-b1d890585256)
