### ISSUE TITLE
Redesign the interface for service admins where they manage which ORGs and COs (can) connect (to) their service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#448]
The UX for a Service to define for which Organizations are available to a Service needs to be reviewed and redesigned. 

There are multiple issues:
 - Org and COs are currently displayed on equavalent tabs, but they have differnet meanings (Orgs that are allowed to use the Service vs COs that are actually connected to our Service)
 - Orgs that can connect are configured in the Org tab, whereas Orgs that can _automatically_ connect are configured in Details/Connection ("Trusted or owned organisations")

**Comment by FlorisFokkinga** [comment]
#### Overview page ####
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/80269262/215033004-2db288d6-9f6c-4cc5-8897-92b07ea93fb1.png">

Currently, settings about organisational access and connecting/connected COs are both under Details -> Connection, and the Org and CO tabs.

**Comment by FlorisFokkinga** [comment]
These are the settings currently available to platform admins.
### Organisations ###
<img width="122" alt="image" src="https://user-images.githubusercontent.com/80269262/215043267-e9ed7e95-a56f-4e80-88e4-cf681c52b338.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/80269262/215043235-064e4281-024a-40c0-8798-5af70cc94ef7.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/80269262/215043189-260b03e4-a287-4c62-8347-cb308c4b58ba.png">
<img width="169" alt="image" src="https://user-images.githubusercontent.com/80269262/215043207-b5df4808-ad6c-45c6-85d5-cf809bf6f26a.png">

### Collaborations ###
<img width="418" alt="image" src="https://user-images.githubusercontent.com/80269262/215045608-1d83ed11-4b28-4333-a509-c8df805a7ad4.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/80269262/215045635-ee0b9395-8b40-49a7-848f-0c8bdf0132fa.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/80269262/215045721-4affe6c3-c335-4e76-9ae9-97e6b4cc4ed2.png">

**Comment by baszoetekouw** [comment]
Uitgangspunt moet zijn om alle Org setting op de Org pagina te hebben, en alle CO settings op de CO-pagina (en dus niet meer onder de details)

Mogelijke oplossing: extra kolom in de Org tabel.

**Comment by FlorisFokkinga** [comment]
## Current settings ##
Allow request/connect from ORGs - Toggle in table
Allow request/connect from all + future ORGs - Button above table ‘make available to all ORGs’
Allow request/connect from SURF ORGs - Checkbox in settings ‘SURF service’
Toggle request/connect from above - Checkbox in settings ‘connect without approval’
Allow connect from ORGs - Chips in settings ‘trusted or owned ORGs’
Use service without CO - Checkbox in settings ‘accessible without membership’
## Design proposal ##
Replace or move all the settings above to the organisations and collaborations tabs:
### Organisations tab ###
- Rename tab to 'Organizational access'
- Move tab to the right of 'Groups' tab
- Move the checkbox for 'SURF service' to between the tab and the table with organisations.
This checkbox now also hides all SURF organisations in the table.
- Add radio buttons between the tab and the table with organisations:
⚫️ Choose permission for each organisation
🔘 Allow connection requests from collaborations from all current and future organisations
🔘 Always alllow connections from collaborations from all current and future organisations
The first one is the default, with no organisations selected. The second and third option grey-out the segmented controls in the table.
- The table shows segmented controls for each organisation, with the control in the first column:

Connections from collaborations | Name | Short name...
( Disallow | On request | Always ) | Org 1 | ...
( Disallow | On request | Always ) | Org 2 | ...

### Collaborations tab ###
- Rename tab to 'Organizational access'
- Move tab to the right of 'Groups' tab
- Move the checkbox for 'Accessible without membership of a collaboration' to between the tab and the table with organisations.
This checkbox now also hides the table under the groups tab.

**Comment by FlorisFokkinga** [comment]
Dicussion: What would the uses cases be for making the service available for new organisations, but also differentiate for existing organisations?

**Comment by FlorisFokkinga** [comment]
Cosmetic:
- [ ] The radio buttons and checkbox lack a padding left on a narrow screen
- [ ] SURF ORGs are counted in the tab number, but not visible for non SURF services 
- [ ] Place the logo next to the ORG name
- [ ] If COs are ignored for access, show the same the explanation also on the CO access tab: "All users of the platform can access this service, regardless of any collaboration membership."

**Comment by FlorisFokkinga** [comment]
All fixed.
