### ISSUE TITLE
Button for adding/requesting a CO with permission from the user's IdP's domain organisation

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#449]
Als ik als user met een org domain dat bij een org hoort verwikkeld ben in andere orgs of services kan ik geen CO aanvragen voor de organisatie van mijn domain, als ik alle connecties verwijder krijg ik de welcome landing page en kan ik wel een CO aanvragen voor de org van m'n domain. Is dat by-design?

**Comment by FlorisFokkinga** [comment]
@mrvanes, de discoverability hiervan neemt inderdaad flink af. De optie zit in het profielmenu, rechtsboven.
Dit komt alleen voor als je niet lid bent van een CO, maar wel admin van een service of org of als je uitsluitend lid bent van van één CO.

**Comment by FlorisFokkinga** [comment]
Think of a good solution.

**Comment by FlorisFokkinga** [comment]
Button seems to be missing from the table tab.

![Image](https://github.com/SURFscz/SBS/assets/80269262/3191a0ad-23dc-4308-a97f-229cc16d5328)

**Comment by FlorisFokkinga** [comment]
## Creating a CO with permission from the user's IdP's domain organisation
- For a user without any membership or admin role, the button is on the welcome page (no change required)
- For a user that is member of only one CO, activate the home page
  - One the homepage, show the CO tab and show the add/request CO button
  - Activate the breadcrumbs and logo link to the home page
  - Keep the redirect to the single CO on login to SBS
- For a user that is a service admin, but not member of any CO on the home page, also show a CO tab with an emtpy table, like the CO tab on an organisation without any CO. Show the tree swing and the add/request CO button.
- Remove the request/create CO link from the menu on the top right

**Comment by FlorisFokkinga** [comment]
I'd expect a 'request collaboration' button on the table.
<img width="1332" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/be27f626-05a4-4494-9239-1c2830e9ed57">

**Comment by oharsta** [comment]
@FlorisFokkinga  The last commit is https://test.sram.surf.nl/info and https://github.com/SURFscz/SBS/commit/ddb06f5651a232d9269c432f101b4277199d1a19 has not been deployed yet.

**Comment by FlorisFokkinga** [comment]
The locale for an empty collaboration table for organisations is reused: `There are no collaborations yet within your organisation.` Please seperate these.

**Comment by FlorisFokkinga** [comment]
Since I designed this, I think someone else should also take a look if the solution covers all use cases.

**Comment by FlorisFokkinga** [comment]
A user with only requests, so that only has the 'My requests' tab, cannot request a CO.


![Image](https://github.com/SURFscz/SBS/assets/80269262/66a0bf0f-7a16-4584-aa0f-c393757bacad)

**Comment by mrvanes** [comment]
All works as expected, except this one:
- Keep the redirect to the single CO on login to SBS

**Comment by baszoetekouw** [comment]
Now works correctly on test
