### ISSUE TITLE
Wrapping in description fields is rather primitive

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#452]
Long descriptions in tables look like this: 

![Screenshot 2022-12-14 at 11 20 29](https://user-images.githubusercontent.com/1461740/207569584-98f8d2c8-eb84-4dc9-8a67-309b8be51ed8.png)

For these types of free-text fields, we should use proper word wrapping.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/95b87e796f12825c21be4c6cc6a43c3829890538

**Comment by baszoetekouw** [comment]
Now looks ok:

![Image](https://github.com/SURFscz/SBS/assets/1461740/13e455bc-4cb7-49b7-958a-07d7029fa54a)
