### ISSUE TITLE
Changing "automatic connectings allowed" for a service is not shown in CO Service overviews until reload

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#456]
When changing the setting "Collaborations can connect without your approval" in a Service, this is not shown in the Service overview of COs until the CO page is reloaded.  Until the reload, the Services are still shown as "Request Connection".

**Comment by baszoetekouw** [comment]
Same when the Service adds an Organization to the "Trusted or owned organisations" who may automatically connect.

**Comment by mrvanes** [comment]
Checked by Martin
