### ISSUE TITLE
For Services without automatic connections, AUP is never shown to CO Admins when requesting the connection

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#457]
For automatic connections, the Service AUP is shown tot he CO Admin before connecting his CO to the Service.  For Services without Automatic connections, it would make sense to also show the AUP to CO Admins who request a connection

**Comment by arnoutt** [comment]
Solution: add link + checkbox for AUP to Request Connection tab/dialog.

**Comment by baszoetekouw** [comment]
Confirmed.

![Image](https://user-images.githubusercontent.com/1461740/221607260-55c45001-7fa9-462c-b0b4-30d5130b8487.png)
