### ISSUE TITLE
"Trusted or owned orgnisations" doesn nto work when Service is available for all Orgs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#458]
If a Service is available for all Orgs, the "Trusted or owned organisations" selector under connections (to select COs in which Orgs can connect automatically without further approval) shows "No Options".

However, we want to support the following scenario: a Service is in principle available to all COs in all Orgs (but they need approval first).  Only COs for a small number of Orgs may be automatically connected.

So in the case that the Service is available to all Orgs, we still would like to be able the select a number of Orgs who may connect automatically.

**Comment by oharsta** [comment]
@baszoetekouw  This is not the behaviour I see on test. The "Trusted or owned organisations" drop-down is only disabled when the checkbox "Collaborations can connect without your approval" is checked. If this checkbox is unchecked and the service is made available for all organisations , then the dropdown is active. See https://test.sram.surf.nl/services/345/organisations as an example.

**Comment by baszoetekouw** [comment]
I can still reproduce this on acc.  Note though that the checkbox is not disable; I can click it, but it show "no options".

I can now also reproduce this on test:
- uncheck "make available for all orgs"
- uncheck all orgs
- recheck "make available for all orgs"
- go to connection tab and click on the dropdown.

Strangely enough, if some orgs were selected, and after that the "enable for all orgs" is set, only the orgs that were enabled before the "enable for all orgs" was enabled are shown in the dropdown.

![Screenshot 2022-12-20 at 11 00 17](https://user-images.githubusercontent.com/1461740/208639567-f3d38022-574c-4db2-9820-f4e51bf9ed5f.png)

**Comment by oharsta** [comment]
Reproduced and fixed.

**Comment by mrvanes** [comment]
Checked by Martin
