### ISSUE TITLE
Unexpected error when a live update leads to a permission denied

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#460]
To reproduce:
 - open service screen as service admin and select the "Admins" tab
 - in a different screen with a different user, remove the first user as Service Admin
 - the original user will no longer have access to the service and his page will shown an Unexpected Error.

**Comment by baszoetekouw** [comment]
Proper solution would be to either show a special "You no longer have access to Service/CO/Org X" screen, or to simply redirect the user to `/home`.

**Comment by mrvanes** [comment]
Checked by Martin
