### ISSUE TITLE
SURF Orgs should not be visible for regular Services

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#462]
In the list of available organisations for a Service, always all Organisations are shown.

So what often happens is that a non-SURF-service enables their service for a SURF Org (e.g., Harderwijk) and is then surprised to not see the Service in the list of available Services in a CO.

So in the list of Org in the Service screen, we should make clear that this non-SURF-service cannot be made available to SURF Orgs in the first place.

**Comment by arnoutt** [comment]
Solution: make sure that for non-SURF-services, the SURF organisation(s) are never shown.

**Comment by FlorisFokkinga** [comment]
This works, assuming this should only apply to the service point of view, not the organisation point of view, regarding mandatory services.
