### ISSUE TITLE
Remove session cookie upon Seed / Reload

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#463]
[ issue during development ]
When running SBS in test mode, for example on localhost, you have te option to Reload database Seed. 
This will make your exisiting session cookie not matching anymore with server state. 
This will result in error code 502 / Bad Gateway.
You can resolve by erasing SBS session cookie in your browser.
Reqeust to have the session cookie automatically removed when doing database seed reload.

**Comment by baszoetekouw** [comment]
werkt!
