### ISSUE TITLE
SURF Design System: overall layout/fonts/colors/etc.

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#465]
- Color: there is currently no reason to switch to a different color (than orange) so please make sure SRAM conforms to the official color scheme mentioned in the SDS. Also take the official 'support color' into account.
- Layout: make sure SRAM conforms to SDS layout recommendations
- Logo: make sure logo is displayed according to SDS
- Fonts: make sure SRAM conforms to SDS
- Tooltips: all tooltips must be in line with the SDS

**Comment by FlorisFokkinga** [comment]
This all looks good. I'm sure we've missed a few minor occurences; we'll fix those after the first release.
