### ISSUE TITLE
SURF Design System: redesign main area + footer

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#467]
- Tables: make sure all tables / cells / rows / columns are in line with the SDS. Also, the pagination should be aligned on the bottom left intead of right
- Notifications: make sure they are in line with the SDS (either the alert or the toaster component)
- Modal: make sure the modals are designed according the SDS. Note that SRAM's modal is much bigger and contains more information, which is fine.
- Footer: ensure footer is in line with SDS

These points likely require some discussion first:
- CO sub groups page: this now looks like a sort of mini page inside a page with its own mini header. Do we want to keep that?
- CO services tab: any ideas how to improve that?
- User detail page: how do we want to improve that?

**Comment by FlorisFokkinga** [comment]
- Pagination button text is bold ```font-weight: 600;```, but in the SDS it has a regular weight.
- Warning bar on the top of the page should be higher, according to the SDS. This will also leave space for placing a button.
- Modals will require a complete text rewrite, which we won't manage before the SDS release.

The last three points are interesting discussion points, but out of scope.
