### ISSUE TITLE
Display count on tabs as label

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#484]
As a replacement of the current '<title> (#)'.

![Image](https://user-images.githubusercontent.com/80269262/192547286-e915b2ad-1e96-46e4-b5b6-56c6a40ea3fb.png)

**Comment by baszoetekouw** [comment]
use "chip" in design system.

**Comment by FlorisFokkinga** [comment]
![Image](https://user-images.githubusercontent.com/80269262/222372300-7d04a8f8-0f8d-4c73-a84e-ca9ec8698a54.png)
