### ISSUE TITLE
Remove number from blue dot at tab bar

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#485]
The goal of the blue dot is indicating an action is required. In hindsight, the number on the blue dot confuses because the tabs also display the number of elements.

![Image](https://user-images.githubusercontent.com/80269262/202673354-2c31d2e6-103f-41dd-8efe-46da0617cc9f.png)

**Comment by oharsta** [comment]
@baszoetekouw Can do this, but then there is no visual indicator anymore that an action is required for the user. We are ok with the deletion for this call-to-action?

**Comment by FlorisFokkinga** [comment]
As agreed, the indicator is still there, the number is removed.
