### ISSUE TITLE
Warning bar 'CO to expire soon' remains when opening a service from that CO

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#487]
1. Open a CO that is to expire soon, either by end date or inactivity
2. Open its service tab
3. Open de link to one of its services

![Image](https://user-images.githubusercontent.com/80269262/213986227-7991584d-ef16-45cf-a85b-c09b6fb932c4.png)

**Comment by baszoetekouw** [comment]
confirmed
