### ISSUE TITLE
support voor emaildressen in de vorm `Pietje Puk <piet@puk.example.edu>` in invitation boxes

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#494]
Bv nuttig voor het sturen van uitnodigingen naar adressen die je uit een mailclient kopieert.

Als je dus nu paste in een invite-field, lijtk SBS te te snappen maar maakt hij er toch een invalid emailadres van.

**Comment by oharsta** [comment]
https://github.com/SURFnet/sds/blob/main/src/components/EmailInput/EmailInput.tsx

**Comment by baszoetekouw** [comment]
works
