### ISSUE TITLE
Encryption of stored SCIM Beaer token for remote SCIM servers

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#498]
SCIM bearer tokens (e.g., secrets to access remote SCIM servers) should be stored encrypted in the database, so they aren't exposed when a database dump is leaked, for example.  Note that we are protecting against a database compromise, not an SBS compromise (in which case we would be f*cked, anyway), so storing the encryption key in the SBS config is perfectly fine.

For the implementation, note the guidelines here: https://soatok.blog/2023/03/01/database-cryptography-fur-the-rest-of-us/
In short:
 - don't use internal mysql encryption function
 - use an AES-GCM cipher (e.g., https://cryptography.io/en/latest/hazmat/primitives/aead/#cryptography.hazmat.primitives.ciphers.aead.AESGCM), and *NOT* AES_CBC (like cryptography.fernet, see https://cryptography.io/en/latest/fernet/#implementation)
 - encrypt the bearer token with context (so eg `f"{database_name}*{table_name}*{row_id}*{base64(scim_url)}*{base64(token)}"`) instead of the plain bearer token (otherwise an attacker can manipulate the db to trick SBS to send the decrypted key to an url of their choosing)

I would prefer to not be backward compatible here, and to add a database migration that encrypts all existing secrets.

**Comment by HarryKodden** [comment]
I get this error during Test and Sweep operations.
Could not connect to remote SCIM server (SSLError) on 
The SSL Certificate is valid (https://scim.e-tunity.net/api/v2)
Are certificates updated on SBS host ?
