### ISSUE TITLE
Revise the profile page

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#501]
![image](https://user-images.githubusercontent.com/80269262/214848300-04458a7d-e33e-4df8-bba2-24cde4e66333.png)
![image](https://user-images.githubusercontent.com/80269262/214848402-a8ad78db-e9a3-4f50-93db-47a7424f06ab.png)
![image](https://user-images.githubusercontent.com/80269262/214848451-33980ef4-b915-4293-be98-c204c521762a.png)

This was designed before the SURF design system. It should be closer to it than the current profile page though.
The data for the shield icons isn't available yet, so don't implement those.

Attributes from the old profile page map to the new profile page as follows:

New - Old
Email address - Email
Name - Name
Organisation - New, the user's organisation/IdP's full name
Affiliation(s) - eduPersonScopedAffiliation (multi valued)
SRAM internal username - Username

provided by <institution domain> - Organisation domain name

Two-factor authentication - <no change>
SSH public keys - <no change>

**Comment by baszoetekouw** [comment]
Zie ook https://github.com/SURFscz/SBS/issues/267

**Comment by baszoetekouw** [comment]
We would like to make some changes to the screen above so that for ssh keys, the default action is "upload an key" and "paste a key" becomes more hidden.

**Comment by FlorisFokkinga** [comment]
As discussed with Okke, we want to nudge users to uploading a key file, because mistakes occur with copying and pasting SSH keys as text.
For instance, by showing the upload/import link/button as soon as the 'Add new SSH keys' button is used, and offering pasting a key as an alternative, just as 'Or import a key' is shown in the mockup.

**Comment by FlorisFokkinga** [comment]
Looks good.
The 'Delete your account/profile' button could us a header with text, placed under the 'Download' and 'Update buttons, like in the design.

### Verwijder je profiel ###
Als je je profiel verwijdert, worden ook al je lidmaatschappen en beheerrollen verwijderd. Dit kan niet ongedaan worden gemaakt.

### Delete your profile ###
Deleting your profile will also remove all your memberships and admin roles. This cannot be reverted.

**Comment by FlorisFokkinga** [comment]
Looks good.
