### ISSUE TITLE
CO expiry mails should only go to CO admins, not members

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#514]
Currently, emails which are sent when a CO is about to expired / is expired is sent to _all_ members. That is not correct, they should only be sent to the CO admin(s) of the specific CO. (If there are no admins, the mails should be sent to the org admins + managers.)

**Comment by oharsta** [comment]
@arnoutt Are you sure? When I look at the code then the memberships are filtered on `role == admin`.

**Comment by arnoutt** [comment]
@oharsta hmm, that's weird, I tested it last week and indeed all members get the email, even if they are not admin...

**Comment by oharsta** [comment]
The mail that is sent when a membership will expire is send also only to the CO admins + the user which membership will expire.

**Comment by arnoutt** [comment]
There are 2 types of expiry: (1) a membership (of a CO) can expire and (2) the CO itself can expire. In this issue I'm referring to (2). Only the CO admin can do something about that, so only they should receive those emails. (For (1), it is indeed right what you are saying.)

**Comment by oharsta** [comment]
In scenario 2) the emails are send only too CO admins. However the email is also sent to all members of the organisation regardless if there are CO admins. I'll change that.

**Comment by baszoetekouw** [comment]
confirmed
