### ISSUE TITLE
As a CO admin, I want to see what groups are created by what service, so I understand which ones I can edit

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#518]
Split from
- #437
And combine this with what service the group was created for. De edit form of a service must remain visable, the CO admin can toggle auto provisioning, with the other fields read only.
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/80269262/218023063-291941e0-dd9b-490e-9325-3648902442bb.png">

**Comment by baszoetekouw** [comment]
confirmed
