### ISSUE TITLE
SCIM Sweep: Too much Group Updates

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#524]
The membership compare between remote scim and SRAM shows inequality caused by wrong attribute comparison

File: server/scim/sweep.py line 60:

Current:
```
remote_users_by_id = {u["id"]: u for u in remote_scim_users}
```

Suggested to change into: 
```
remote_users_by_id = {u["externalId"]: u for u in remote_scim_users}
```

**Comment by oharsta** [comment]
Current implementation is correct. Group updates were occurring because of empty string vs None comparison.
