### ISSUE TITLE
SDS implementation improvements

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#527]
- [x] Footer is niet conform SDS. Terms of Use: https://edu.nl/6wb63, Privacy Policy: https://edu.nl/fcgbd. Let ook op link kleuren en grootte SURF logo.
- [x] Links moeten vet worden weergegeven.
- [x] Verticale uitlijning (member list) ![Image](https://user-images.githubusercontent.com/80269262/219357803-66a163b2-a58d-4166-bebf-e02ce7b72466.png)

Landing page:
- [x] Chips/badges 'admin role' herstijlen.
- [x] Kleur: 'How does is work?' moet zwart zijn.
- [x] TOTP instellen: Knop 'next' standaardbreedte

SRAM AUP acceptpagina:
- [x] Grijze kader om checkbox verwijderen.
- [x] Knop 'next' standaardbreedte
- [x] Object headers: Titel moet zwart zijn.
- [x] Profile: /2fa-update : i-icoontje is veel te groot (Firefox)
- [x] Tabel: Objectnaam moet geen link zijn.
- [x] Tabbladen: De huidige tabbladen passen niet in de header die we gebruiken. Gebruik de tabjes die bij de gebruikte object-header horen: https://design.surf.nl/#object-header ![Image](https://user-images.githubusercontent.com/80269262/219376454-8e521048-66f7-41ba-8bfb-d2d260fa12a4.png)
- [x] Zoekveld: Stijlen volgens SDS (o.a. kleur icoontje en uitlijning)

**Comment by FlorisFokkinga** [comment]
- 'Tabel: Objectnaam moet geen link zijn.'
Remove the (styling as) hyperlink from the object names, but make the row clickable in such a way it can be opened in a new tab.

- Tabs looks good!

**Comment by FlorisFokkinga** [comment]
At Org and CO, the names at the services tab are still styled as links.

**Comment by oharsta** [comment]
@FlorisFokkinga The rows in the services tab in the CO / ORG deatils is not clickable (there is no action behind), so in order to directly go the service the name column is a link. The styling is directly from the SDS https://design.surf.nl/#table.

**Comment by FlorisFokkinga** [comment]
Our interpretation of the SDS is that hyperlink styling (in tables) is only used when the actual content of the cell is a hyperlink, so usually to an external application or website. So when linking to something within the SRAM GUI, please don't style links in tables.

**Comment by FlorisFokkinga** [comment]
The change looks good.
Link styling is still enabled for the service tab of a CO, e.g., https://test.sram.surf.nl/collaborations/3073/services.
