### ISSUE TITLE
HTTP 413 "content too large" when updating service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#532]
When updating `https://sram.surf.nl/services/20/details` (pressing "Update" in the detauils page), the API return HTTP 413:

```
Feb 23 12:52:10 sbs-pf1 nginx[610]: 2023/02/23 12:52:10 [error] 610#610: *727913 client intended to send too large body: 1241138 bytes, client: 10.0.0.20, server: _, request: "PUT /api/services HTTP/1.1", host: "sram.surf.nl", referrer: "https://sram.surf.nl/services/20/details/SCIM"
Feb 23 12:52:11 sbs-pf1 nginx[611]: 10.0.0.20 2001:610:XXX:XXX::11 - [23/Feb/2023:12:52:11 +0000] "sram.surf.nl" "PUT /api/services HTTP/1.1" 413 183 "https://sram.surf.nl/services/20/details/tokens" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0"
```

Or is nginx the culprit here?

In any case, the client currently doesn't handle this issue very well: it seems the update has succeeded, and the web page shows the updated values, but upon reload, the old values are back.

**Comment by baszoetekouw** [comment]
Also, why is this request so large?  Sure, it's a large Service (646 COs connected) but surely we don't need to send 1.5MB of json?

**Comment by oharsta** [comment]
@baszoetekouw Can you capture the JSON which is PUT to the server and attach / email me this?

**Comment by baszoetekouw** [comment]
That seems to be hard, because the browser doesn't actually send it (and getting it from the js debug console is quite complicated with all the minified js); nginx already returns the 413 error when the browser annoucnes the size in the header.

I'll try to adjust the nginx config to accept larger messages and capture it then.

**Comment by baszoetekouw** [comment]
I've managed to capture it.  The problem seems to be that the client put all information about all connected Organizations and Collaborations back.  We probably shouldn't do that.

**Comment by baszoetekouw** [comment]
@oharsta have you also added a fix for this in the SBS client?  I've increased the nginx limit, but we will definiately hit that again  some time in the future.

**Comment by baszoetekouw** [comment]
for now fixed in nginx config.  Continued in #556
