### ISSUE TITLE
"Token" tab should not be visible (or usable) by service admins

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#534]
Service admins can currently see the "Tokens" tab in their own service, and can even create a new token.  However, this functionality should only be available for users who have access to the service though a connected CO or Org. 

A Service Admin should be able to view this tab and create new tokens only if they (in addition to being Service Admin) have access to the Service like a regular user (ie, be a member of a CO that is connected to the Service).

**Comment by mrvanes** [comment]
Correct
