### ISSUE TITLE
'SCIM endpoint base URL' is a mandatory field on TEST

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#535]
On TEST, enabling SCIM makes the field 'SCIM endpoint base URL' mandatory, though it isn't required for SRAM to act as a SCIM server.

![Image](https://user-images.githubusercontent.com/80269262/221190701-6383f48d-66e6-41bb-bfb2-7efde564976a.png)

**Comment by oharsta** [comment]
@FlorisFokkinga See https://github.com/SURFscz/SBS/issues/521 for the opposite requirement.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw, that doesn't seem right. :)

**Comment by FlorisFokkinga** [comment]
The underlying problem is that the check box is now required for pulls, changing that is also a solution.

**Comment by HarryKodden** [comment]
SRAM as SCIM Server: No need to enable SCIM checkbox. 
SRAM as SCIM Client to Contact remote SCIM Server -> Need to enable Checkbox
This works fine !
However, you need to set up token in the "Tokens" Tab, that token is required to make requests to SRAM SCIM Server
For example :
curl --request GET \
  --url https://acc.sram.surf.nl/api/scim/v2/Users \
  --header 'Authorization: Bearer < The token you have created >'

The token tab is confusing. You can only create a token if "Token Based Introspectiom" is enabled. This is odd
As I am assuming we will make a change for that in a spearate issue, we can close this issue
