### ISSUE TITLE
As a CO admin, I want to undo the suspension of a CO directly from the warning

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#542]
When a CO is (about to be) suspended, a warning is shown in the warning bar:
![image](https://user-images.githubusercontent.com/1461740/223115817-64607d09-f328-4e1d-9281-d8aba8c782d1.png)

Instead of describing how to prevent this ("You can prevent the suspension from the right drop-down menu") simply allow the user to prevent it directly from the warning message: "Click here to prevent suspension."

**Comment by arnoutt** [comment]
Additional note: use SDS alert (with button) element for this
