### ISSUE TITLE
Add 'membership management' function to Org API

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#545]
For Yoda, the following API calls are needed:
1) Remove users from COs
2) Add and remove users to (pre defined) sub groups (or service groups)
3) Remove a CO (note: only COs which are created by Yoda in the first place? Is there any way to know this?)

This should be part of the Organisation API.  

For 1) I propose adding `DELETE /api/collaborations/v1/{co_uuid}/members/{user_uid}` where `{user_uid}` is the uid as returned by the `/api/collaborations/v1/{identifier}` call in `collaboration_memberships[x].user.uid`.

For 2) I propose adding the endpoints:
  - `POST /api/groups/v1/{group_uuid}` to add a member to the specified group.  The request body should be `{"uid": "{user_uid}"}` listing a single user to add to the group. Of course, that should only success if the user in question is already a member of the CO.
  - `DELETE /api/groups/v1/{group_uuid}/members/{user_uid}` to remove the specified member from the group
Note the we don't need to include the CO id here, as the group uuids are unique.
  - Optionally, we could also add a `GET /api/groups/v1/{group_uuid}`, but this gives the same information that is already returned by the collaboration endpoint.

For 3), I propose to add `DELETE /api/collaborations/v1/{co_uuid}`.  There is no need for additional checks (apart from the one to check if the CO to be deleted belongs to the Organization that owns the bearer token). 

Please make sure (for all of these calls) that is it visible in the audit logs that the call was made from the API.  Preferably, I would also like to be able to see which key was used.

**Comment by arnoutt** [comment]
@baszoetekouw Can you answer this question?

**Comment by baszoetekouw** [comment]
Right, I didn;t notice the `uuid4` element; we don't want to use that (what are we using it for anyway?).

Please use the `identifier` attributes for both groups and COs.  For users, we use the `uid`.

**Comment by oharsta** [comment]
@baszoetekouw FYI: rhe `uuid4` attribute is used as the logo id in the redis cache.

**Comment by oharsta** [comment]
https://test.sram.surf.nl/apidocs/

**Comment by mrvanes** [comment]
1. Works, but the Swagger UI is broken (API key input auto resets)
2. Works, but Swagger is broken and says user_id, but I need to supply uid
3. Works, but Swagger UI is broken and user is **also deleted from CO**

**Comment by baszoetekouw** [comment]
@oharsta The swagger stuff can wait until v22, but the delting for the CO needs to be fixed before the release.

**Comment by mrvanes** [comment]
2b is fixed
