### ISSUE TITLE
Show chip in "last activity" column when CO is suspended

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#549]
Use the same styling as an expired invitation, but keep/add the tooltip with the last activity timestamp.

![Image](https://github.com/SURFscz/SBS/assets/80269262/f409eafe-71fc-4f46-9f8a-f9ebeefac74b)

**Comment by FlorisFokkinga** [comment]
This might be improved by the SDS using a chip for the suspension status. Let's test that.

**Comment by baszoetekouw** [comment]
Looking good!


![Image](https://github.com/SURFscz/SBS/assets/1461740/b3f9c154-a96e-4fea-afb2-681b856189ab)
