### ISSUE TITLE
SBS clients sends too much information when updating a Service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#556]
This is a continuation of #532 

When updating https://sram.surf.nl/services/20/details (pressing "Update" in the details page), the SBS clients sends a copy of all information is is currently displaying (including information of all COs in all connected Organsations)  in the PUT request.  

This used to hit the Nginx request size limit, but that has been increased in #532.  We do still need to clean this up in the SBS client also, because otherwise we'll hit the new limit again sometime in the future.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/2c1a293991097e4c6395015381a4b3fc44c1bdf3

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/0c920d31cb335537bcff80ea8c1058d702b2cd55

**Comment by baszoetekouw** [comment]
confirmed on acc
