### ISSUE TITLE
As a service admin, I want to request a new service directly from SBS

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#558]
- Allow all users to create services
  - For users that are not service admin or platform admin, add 'Request a service' to the profile menu, below 'Request/add a collaboration'. (This menu item is removed after the user becomes a service admin, since they now have a button on the service tab on the home page.)
- Limit the create service form to what is listed below. (Since the service has not admin, and not organisations are allowed, the service is only visible for platform admins.)
- Platform admins are notified are new service is created (existing functionality) and allow or delete the service
  - In case of deleting the service, the platform admin should email the user with an explanation
- In case the user selected OIDC or SAML, the platform admin connects the service to eduTEAMS and enters the entity ID
- The platform admin invites the user as service admin (this information should be stored somewhere), text prefilled:
~~~
Your service request was approved, you are invited as service admin in SURF Research Access Management.
You can now:
 * Select from which organisation collaborations can connect to your service
 * Try to login to your service, if you use SAML or OIDC (requires membership of a collaboration)
 * Connect the service via LDAP, SCIM, PAM web login or a user token
 * Invite additional service admins
 * Create service groups, that will be provisioned to connected collaborations

Button [Manage my service]
~~~

| Section    | Attribute                                    |
| ----------------- | --------------------------------------- |
| About the service | Name                                    |
|                   | Short name                              |
|                   | Description                             |
|                   | Logo                                    |
|                   | Providing organisation                  |
|                   | Login URL for users                     |
|                   |                                         |
| Support           | Website                                 |
|                   | User support contact                    |
|                   | Adminstrative contact                   |
|                   | Security contact                        |
|                   |                                         |
| Policies          | Privacy policy URL                      |
|                   | Acceptable use policy URL               |
|                   | Coco                                    |
|                   | Sirtfi                                  |
|                   | R&S                                     |
|                   |                                         |
| Connection        | OpenID connect (radio button, reveals)                          |
|                   | OIDC redirect URLs                      |
|                   | SAML (radio button, reveals)                               |
|                   | SAML metadata URL or upload             |
|                   | Neither (radio button) |
|                   | Other protocols can be selected later (In text) |
|                   |                                         |
| Comments          | Comments about this request             |
|                   | [Submit request]                        |
|                   |                                         |

**Comment by FlorisFokkinga** [comment]
- All SRAM user can request a service
- Platform admins approve the service request
- Minimal required set of attributes in eduTEAMS
- User can make up a short name

**Comment by FlorisFokkinga** [comment]
- Add a form that adds this service for review by a platform admin
- The submitter becomes the service admin
- The platform admin connects the service to eduTEAMS and enters the entity ID
- The platform admin approves the service
- The service admin recieves a confirmation email:
~~~
Your service request was approved, you are now service admin for the service <name> in SURF Research Access Management.
You can now:
 * Try to login to your service, if you use SAML or OIDC
 * Connect the service via LDAP, SCIM, PAM web login or a user token
 * Invite additional service admins
 * Select from which organisation collaborations can connect to your service
 * Create service groups, that will be provisioned to connected collaborations
[Manage my service]
~~~

| Section    | Attribute                                    |
| ----------------- | --------------------------------------- |
| About the service | Name                                    |
|                   | Short name                              |
|                   | Description                             |
|                   | Logo                                    |
|                   | Providing organisation                  |
|                   | Login URL for users                     |
|                   |                                         |
| Support           | Website                                 |
|                   | User support contact                    |
|                   | Adminstrative contact                   |
|                   | Security contact                        |
|                   |                                         |
| Policies          | Privacy policy URL                      |
|                   | Acceptable use policy URL               |
|                   | Coco                                    |
|                   | Sirtfi                                  |
|                   | R&S                                     |
|                   |                                         |
| Connection        | OpenID connect (radio button, reveals)                          |
|                   | OIDC redirect URLs                      |
|                   | SAML (radio button, reveals)                               |
|                   | SAML metadata URL or upload             |
|                   | Neither (radio button) |
|                   | Other protocols can be selected later (In text) |
|                   |                                         |
| Comments          | Comments about this request             |
|                   | [Submit request]                        |
|                   |                                         |

**Comment by FlorisFokkinga** [comment]
## Add/request/register service ##
For any user.

![Image](https://github.com/SURFscz/SBS/assets/80269262/b54385da-587a-4ce0-8755-1876de9adb00)



## Review page ##
For platform admins.


![Image](https://github.com/SURFscz/SBS/assets/80269262/f7e0b8a3-815c-4f7c-8ea1-f760eb136564)




![Image](https://github.com/SURFscz/SBS/assets/80269262/ab9f9a1f-ebfa-4047-86b4-1af5f4615322)

**Comment by FlorisFokkinga** [comment]
Discussed. Let's treat a service request like a CO request. Show requests in a table (like services for admins are).

**Comment by FlorisFokkinga** [comment]
Bread crumbs link to 'services-requests' instead of 'service-requests'.

**Comment by FlorisFokkinga** [comment]
A users that is service admin of one service, and not member or admin of anything else, cannot request another service. The 'home' breadcrumb is immediately redirected back to the service page.

**Comment by baszoetekouw** [comment]
Works now

![Image](https://github.com/SURFscz/SBS/assets/1461740/638c2301-10f8-40c9-8dc5-1a3f193af581)
