### ISSUE TITLE
EmailField interaction & design

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#559]
How do we want to provide feedback to the user if an invalid email is entered? Or are we happy with the current implementation?

**Comment by oharsta** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/530657/227764779-c42cb4ba-b2b2-45b4-b647-0d23a25aa499.png">

**Comment by FlorisFokkinga** [comment]
If 'wong' was the invalid entered value, this seems fine to me.

**Comment by baszoetekouw** [comment]
commits 0a06cc3 and 71d1ffa
