### ISSUE TITLE
Brakke tekst reset-token

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#568]
De volgende tekst heeft een heel hoog phisingmail-gehalte met taalfouten, non-sequiturs (tweede bullet) en brakke zinsconstructies.

"In het geval je:

 *  toegang tot je telefoon verloren bent
 *  de authenticatiecode hebt gereset
 *  andere problemen hebben

Je kan de beheerder van je samenwerking vragen voor een authenticatie-resettoken. Je moet je tweede authenticatie instellen bij de volgende login.

De e-mail wordt verzonden naar:"

**Comment by FlorisFokkinga** [comment]
Rewrite the text.
