### ISSUE TITLE
Kan account niet verwijderen als je geen naam hebt

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#570]
Om mij onduidelijke redenen heb ik na inloggen geen fullname (idp geeft naam wel vrij). Bij verwijderen moet je eerst je fullname opgeven. Lege string wordt niet geaccepteerd.

**Comment by baszoetekouw** [comment]
Als iemand geen naam heeft om een of andere reden dan moet een leeg veld voldoende zijn.

**Comment by baszoetekouw** [comment]
confirmed op test
