### ISSUE TITLE
TOTP enroll springt naar stap 1 waardoor inleiding niet zichtbaar

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#574]
Op de TOTP enroll pagina springt browser na laden direct naar heading van stap 1 waardoor de heading van de pagina en de inleidende tekst worden overgeslagen

**Comment by thijskh** [comment]
Springen lijkt te komen omdat TOTP-veld helemaal onderaan, buiten de viewport focus krijgt

**Comment by baszoetekouw** [comment]
Ik kan dit op test nog steeds reproduceren.

**Comment by baszoetekouw** [comment]
Werkt nog steeds niet goed op test.  Zie screencast:

https://user-images.githubusercontent.com/1461740/231416968-96155fec-175d-45d1-b81e-8a26ee49a550.mov

Hij springt na het laden na de onderkant van de pagina (zodat het invulveld zichtbaar is).  In plaats daarvan moet hij bovenaan gescrolled zijn zodat je het blauwe vlak kan lezen.

Het textvak moet wel focus houden, zodat je wel kan tiepen.

**Comment by baszoetekouw** [comment]
fix confirmed.
