### ISSUE TITLE
TOTP toevoegen moet je binnen verlooptijd code afronden

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#575]
Bij toevoegen TOTP - https://sbs.test.sram.surf.nl//2fa-update - als je al TOTP hebt krijg je eerst de vraag naar de huidige code. Die wordt echter niet gecheckt. Je gaat verder met het stappenplan. Pas als je de laatste stap voltooit wordt de code uit stap 1 gecontroleerd. Grote kans dat die al verlopen is.

**Comment by baszoetekouw** [comment]
Works correctly now:
 - when old totp is entered, sbs makes backend call
 - backend call verifies totp and puts `validated_current_totp=True` in the session
 - when new totp is entered, `validated_current_totp` from session is checked before proceeding

For completeness, I made sure the `validated_current_totp` is removed from the session when it is checked.
