### ISSUE TITLE
TOTP's hebben generieke naam, soms niet

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#577]
TOTP die je via de standaard onboarding aanmaakt heet "SRAM-test (Secret)", dus niet te onderscheiden als je twee accounts hebt.
Maak je echter een TOTP aan via de vervang-optie, dan heeft die wel je username in de naam.

**Comment by oharsta** [comment]
Een TOTP via de standaard onboarding gebruikt de email van de gebruiker. Alleen als die `NULL` is, dan komt er de default `Secret`. In de test database zijn er 8 gebruikers met een email (en name) met de waarde `NULL`. We gaan uitzoeken hoe die gebruikers erin zijn gekomen.

**Comment by thijskh** [comment]
Ik heb net ingelogd op test met Mujina `user7788899`, deze heeft een mailadres, als ik TOTP enroll staat er slechts "SRAM-test (Secret)", in mijn profiel is wel degelijk een mailadres te zien.

**Comment by oharsta** [comment]
This is caused by the `proxy_authz` flow to login on SRAM where the user is created - if unknown - with only the `uid` attribute.

**Comment by oharsta** [comment]
@baszoetekouw I can't solve this issue without major changes to the `proxy_authz` flow including changes in EDUteams. 

The proxy_authz flow:

EDUteams POST to /api/users/proxy_authz (shortened code)
```
    user_id, service_id, issuer_id
    if service_entity_id.lower() == current_app.app_config.oidc.sram_service_entity_id.lower():
        _perform_sram_login()

    # if the user does not exists, the user is created:
   def perform_sram_login(uid):
        user = User(uid=uid, external_id=str(uuid.uuid4()), created_by="system", updated_by="system")
        if SECOND_FA_REQUIRED:
            user.second_fa_uuid = str(uuid.uuid4())
        redirect_base_url = f"{base_url}/2fa"    
        return {
                "status": {
                    "result": "interrupt",
                    "redirect_url": f"{redirect_base_url}/{user.second_fa_uuid}",
                    "error_status": SECOND_FA_REQUIRED
                }
            }, 200
```
SBS GUI `/2fa?continue_url=https://proxy.acc.sram.eduteams.org/continue` calls server endpoint `api/mfa/get2fa_proxy_authz` to get QR-code, but we don not know the email of the user. Therefore the QR-code does not contain the email of the user.

Possible solution is to add the email to the EDUteam POST to `/api/users/proxy_authz`

The email (and other attributes) are retrieved later in the process, after the continue_url redirect when EDUteams calls `/api/users/resume-session` with a code which is used to fetch the user-info.

**Comment by oharsta** [comment]
@baszoetekouw This is also the reason why there are users with NULL names. The `proxy_authz` flow is started, but not properly finished.

**Comment by oharsta** [comment]
Decided that eduTeams will add the email attribute when calling the SRAM `/api/users/proxy_authz ` endpoint. When this is done, then we can provision the unknown user with an email and the MFA QR code will be correct.

**Comment by baszoetekouw** [comment]
Discussed this yesterday with @oharsta ; I'll ask eduteams to add the user's email address in the `proxy_authz` call, so that we can provision users with a valid email address.

**Comment by baszoetekouw** [comment]
tested
