### ISSUE TITLE
Add help text to generic error page

### ISSUE THREAD

**Issue by thijskh** [SURFscz/SBS#578]
Also see:
- #583 
De foutmeldingpagina bevat een plaatje maar helemaal geen tekst, toelichting, feedforwards, contactinfo of zelfs maar de indicatie dat dit een foutmelding is.

![Image](https://user-images.githubusercontent.com/3808792/225340967-0430f946-fdc2-4fe4-8d7f-cbc809bf2e23.png)

**Comment by FlorisFokkinga** [comment]
Write a generic help text.

**Comment by FlorisFokkinga** [comment]
Based on the 404 error text:
```
"We seem to have run into an unknown error. Sorry for that.</br></br>" +
"Start over on the <a href='{{base_url}}'>homepage</a> or contact us at <a href='mailto:sram-support@surf.nl'>sram-support@surf.nl</a>."
```

```
"Het spijt ons, we zijn tegen een onbekende fout aangelopen.</br></br>" +
"Probeer opnieuw vanaf de <a href='{{base_url}}'>thuispagina</a> of neem contact met ons op via <a href='mailto:sram-support@surf.nl'>sram-support@surf.nl</a>."
```

**Comment by FlorisFokkinga** [comment]
Works on https://test.sram.surf.nl/error
