### ISSUE TITLE
Public CO join page broken (MacOS, Safari)

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#580]
The info in under the header is missing. Seems to be only Safari.

![Image](https://user-images.githubusercontent.com/8791564/225619025-c417dece-badb-42f3-bb3a-b1973f26a3c3.png)

**Comment by oharsta** [comment]
In my Safari it looks fine
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/530657/225620941-61e5f332-ba22-4902-94dd-5845d8ad4737.png">

**Comment by baszoetekouw** [comment]
Ik kan het ook niet (of niet meer?) reproduceren.  @arnoutt kun je nu nog een checken op test of acc?

**Comment by arnoutt** [comment]
I discussed this offline with @oharsta, I think he already found the problem and implemented a solution. Is that correct?
