### ISSUE TITLE
schachomeorg ook uit affiliation halen (als eppn niet is gevuld)

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#581]
The value for schachome is currently determined by parsing `voperson_external_id`.  If this claim is not sent by eduteams, we should additionally parse the `voperson_external_affiliation` claim (note: mapped to internal `scoped_affiliation` column).

**Comment by mrvanes** [comment]
At the moment, `voperson_external_affiliation` has precedence over `voperson_external_id` because the attribute loop does not break on success. The preferred precedence is `voperson_external_id` over `voperson_external_affiliation` (so the loop should break on first match).

**Comment by mrvanes** [comment]
Gefixt
