### ISSUE TITLE
As a user I want to get a useful error message when my SSID login fails

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#583]
A failure in the SSID SFO login corrently results in a generic error message (see #578).  Create a specific error meesage for this, explaining that MFA has failed, include the status returned by SSID, en refer the user to the support desk.

**Comment by FlorisFokkinga** [comment]
Write the error message.

**Comment by baszoetekouw** [comment]
Looks good. Fixed a typo in the translation in 1b2d34b



![Image](https://github.com/SURFscz/SBS/assets/1461740/5305511e-da4e-4beb-96bf-ed8660375267)
