### ISSUE TITLE
Rewrite modal texts and remove the alert bar

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#585]
These are the modals I was able to find. I know there are more.
It seems, however, that removing the alert bar and using a concise question as title makes all modals much clearer.

How shall we proceed? Find the other modals first? Or is this enough of a functional description to make changes and then alter the translations afterwards?

New   title | Button text | New body text | Current body | Current body (continued) | Translation
-- | -- | -- | -- | -- | --
Disable {{type}}? | Disable | Disable {{type}} functionality for this service? The {{count}} existing   {{tokens}} will be deleted. | Are you sure you want to disable {{type}} functionality for this service? | The {{count}} existing {{tokens}} will be deleted. | disableTokenConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this token? | This action cannot be undone. | deleteConfirmation
Delete this <object>? | Delete | You'll have to select a new image. | Are you sure you want to delete this image? | This cannot be reverted, and you'll have to select a new image. | imageDeleteConfirmation
Delete this <object>? | Delete | Delete collaboration {{name}}? | Are you sure you want to delete collaboration {{name}}? | This cannot be undone. | deleteCollaborationConfirmation
Delete this <object>? | Delete | Delete service {{name}}? | Are you sure you want to delete service {{name}}? | This cannot be undone. | deleteConfirmation
Delete this <object>? | Delete | Delete collaboration {{name}}? | Are you sure you want to delete this collaboration? | This cannot be undone. | deleteConfirmation
Delete this <object>? | Delete | Delete organisation {{name}}? | Are you sure you want to delete this organisation? | This cannot be undone. | deleteConfirmation
Delete this <object>? | Delete | Delete service {{name}}? | Are you sure you want to delete service {{name}}? | This cannot be undone. | deleteConfirmation
Delete all data? | Delete | This cannot be undone. | Are you absolutely sure? | This will delete all current data | runDbSeedConfirmation
Reactivate this user? | Reactivate | The user will receive an email with an activation link. | Are you sure you want to re-activate user {{name}}? | We will send them an email with an activation link. | activateMemberConfirmation
Leave this <object>? | Leave | - | Are you sure you want to leave this collaboration? | You will have to be re-invited by an admin to rejoin. | deleteYourselfMemberConfirmation
Leave this <object>? | Leave | - | Are you sure you want to leave this service? | You will have to be re-invited by an admin to rejoin. | deleteYourselfMemberConfirmation
Demote to member? | Demote | You won't be able to revert this. | Are you sure you don't want to be an admin anymore? | You won't be able to revert this. | downgradeYourselfMemberConfirmation
Leave this <object>? | Leave | - | Are you sure you want to leave this organisation? | You won't be able to revert this. | deleteYourselfMemberConfirmation
Purge the audit logs? | Purge | Are you absolutely sure you want to delete all entries from the audit   logs? | Are you absolutely sure you want to delete all entries from the audit   logs? |   | runClearAuditLogsConfirmation
Disable access for this   service? | Disable | - | Are you sure you want disable access for this service? |   | disableAccessConfirmation
Approve this request? | Approve | - | Are you sure you want to approve this request? |   | approveConfirmation
Clear the SCIM statistics? | Clear | - | Are you sure you want to clear the SCIM statistics? |   | clearConfirmation
Decline this request? | Decline | - | Are you sure you want to decline this join request? |   | declineConfirmation
Decline this request? | Decline | - | Are you sure you want to decline this request? |   | declineConfirmation
Delete this <object>? | Delete | Delete {{name}}? | Are you sure you want to delete {{name}}? |   | deleteConfirmation
Delete this <object>? | Delete | Delete group {{name}}? | Are you sure you want to delete group {{name}}? |   | deleteConfirmation
Delete these members and invites? | Delete | - | Are you sure you want to delete the checked members and invitations? |   | deleteEntitiesConfirmation
Delete this <object>? | Delete | Delete the collaboration membership of {{name}}? | Are you sure you want to delete the collaboration membership of {{name}}? |   | deleteMemberConfirmation
Delete this <object>? | Delete | Delete the invitation for {{name}}? | Are you sure you want to delete the invitation for {{name}}? |   | deleteInvitationConfirmation
Delete these admins and invites? | Delete | - | Are you sure you want to delete the selected service admins and   invitations? |   | deleteMemberConfirmation
Delete user {{name}}? | Delete | - | Are you sure you want to delete the user {{name}} for all eternity? |   | deleteOtherConfirmation
Delete these admins and managers? | Delete | - | Are you sure you want to delete these organisation admins and managers? |   | deleteMemberConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this API key? |   | deleteApiKeyConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this collaboration request? |   | deleteConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this invitation? |   | deleteSingleInvitationConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this join request? |   | deleteConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this member? |   | deleteSingleMemberConfirmation
Delete this <object>? | Delete | - | Are you sure you want to delete this service connection request? |   | serviceConnectionRequestDeleteConfirmation
Delete your profile? | Delete my profile | All your memberships will be cancelled. This cannot be undone. | Are you sure you want to delete your profile for all eternity? |   | deleteConfirmation
(continued) | (continued) | Please type in your full name for confirmation. | All your memberships will be deleted and there is no way to revert this   afterwards. |   | deleteConfirmationWarning
(continued) | (continued) | - | If you wish to proceed, please type in your full name for confirmation. |   | deleteConfirmationCheck
Deny this request? | Deny | - | Are you sure you want to deny this collaboration request? |   | denyConfirmation
Remove {{name}}? | Delete | Remove {{name}} from this group? | Are you sure you want to remove {{name}} from this group? |   | deleteMemberConfirmation
Delete this <object>? | Delete | Ongebruikt? | Are you sure you want to remove member {{name}} from this group? |   | removeMemberConfirmation
Delete this <object>? | Delete | Ongebruikt? | Are you sure you want to remove service {{name}} from this group? |   | removeServiceConfirmation
Remove these members? | Delete | - | Are you sure you want to remove the selected memberships from this group? |   | deleteMembersConfirmation
Disconnect this service? | Delete | Disconnect this service from the collaboration? | Are you sure you want to remove this service from collaboration   {{collaboration}}? |   | serviceDeleteConfirmation
Remove this service? | Delete | Ongebruikt? | Are you sure you want to remove this service from organisation   {{organisation}} |   | serviceDeleteConfirmation
Delete this <object>? | Delete | - | Are you sure you want to remove this service token? |   | tokenDeleteConfirmation
Resend this request? | Resend | - | Are you sure you want to resend this service connection request? |   | serviceConnectionRequestResendConfirmation
Reset the TOTP? | Reset | Reset the TOTP for user {{name}}? | Are you sure you want to reset the TOTP for user {{name}}? |   | reset2faConfirmation
Undo this suspension? | Undo suspension | Undo the suspension of user {{name}}? | Are you sure you want to undo the suspension the user {{name}}? |   | unsuspendOtherConfirmation
Delete this <object>? | Delete | Ongebruikt? | The following information for this user will be deleted: |   | removeMemberConfirmationDetails
Delete this <object>? | Delete | Ongebruikt? | The following service specific information will be deleted: |   | removeServiceConfirmationDetails
Delete all data? | Delete | This cannot be undone. | Are you absolutely sure you want to delete all data? |   | runCleanSlate
Unclear where this is used |   |   | {{collaboration}} has an AUP which you can read (more about) at   <LINK>here</a>. |   | policyConfirmation

**Comment by FlorisFokkinga** [comment]
Possible improvement.

![Image](https://github.com/SURFscz/SBS/assets/80269262/e1e7d3dc-39a9-454a-bc91-6017bed6e461)

**Comment by FlorisFokkinga** [comment]
![Image](https://github.com/SURFscz/SBS/assets/80269262/6cbf5854-719d-4f3a-9a8b-6255367dbca9)

**Comment by oharsta** [comment]
Decided that Okke will do analysis.

**Comment by FlorisFokkinga** [comment]
Discussed that it is too much work for too little value to refactor the modals so they share a locale and layout.
We'll address the offending modals individually.
