### ISSUE TITLE
Allow organisation admins to export a .csv or JSON of information about users/COs they are responsible for

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#586]
For management reports.

Request from UU and HU (separate).

Discuss:
- Which information (name? email? identifier? role? last activity? Which COs?)
- Which users to include? Only same institution or also 'external' users (as long as they are member of a CO)?
- Which format
- ...

From a member:
First:
User story CO account
A member of UU organisation has another job.
In the report filter for the name/account and check membership and roles in any CO UU.
If the account is still valid, inform the PI and ask for follow-up actions.
For instance, if the account is the only admin of the CO, ask the PI if the account and/or CO is still valid? And if replacement admin role is needed.

    Name of the CO
    Platform identifier CO
    Name and role Admin of the CO
    Name and role Members of the CO
    fields below would be great for our own administration
    Creation date CO
    Expiration date CO
    Date of last activity CO
    Preferred format: CSV /Excel

Second:
User story CO account and workspace
A member of UU organisation has another job.
In a (separate) report filter for account left member. If the account is owner of a workspace, inform Admin CO/PI and ask for follow-up actions.

    Name CO
    Name workspace
    Name owner
    State workspace
    Last date of activity workspace
    End date
    fields below would be great for our own administration
    Creation date
    Type application
    Name catalog item
    Running version catalog item
    Preferred format: CSV /Excel

**Comment by baszoetekouw** [comment]
See also #1186

**Comment by baszoetekouw** [comment]
Need to find out _what_ type of information in required.  Superseded by #1186
