### ISSUE TITLE
Vreemde utf8-tekens (emoji etc) in invitation komen niet door in de mail

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#588]
Invitation:
![Screenshot 2023-03-20 at 15 07 30](https://user-images.githubusercontent.com/1461740/226365022-55ff7665-7893-464c-a806-3b98f926b4d0.png)

Mail:
![Screenshot 2023-03-20 at 15 07 57](https://user-images.githubusercontent.com/1461740/226365176-670328d8-94fa-42ba-89a4-1c4383c94343.png)

**Comment by oharsta** [comment]
@baszoetekouw Is it an environment setting? Or database setting? On test I can't reproduce.
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/530657/227765419-0da0e9fb-af2d-4ea8-a975-ecf3c4005e1d.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/530657/227765438-e3307210-77db-4651-881a-e374f97b5468.png">

**Comment by oharsta** [comment]
Generated with https://www.emojiipsum.top/

**Comment by FlorisFokkinga** [comment]
Can't reproduce.
