### ISSUE TITLE
Service pagina scrollt naar top als ik Org toestemming aanpas

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#590]
Erg onhandig: in het Service/Organisatietoegang scherm scrollt de pagina naar boven elke keer als ik op een knop druk.

Zie screencast

https://user-images.githubusercontent.com/1461740/226370251-ea972bf6-e611-452a-ae6c-e1e13d3a7141.mov

**Comment by oharsta** [comment]
Removed the scroll to top in the refresh

**Comment by FlorisFokkinga** [comment]
Fixed. (Excellent, much better.)
