### ISSUE TITLE
Service/Organisatietoegang op smalle schermen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#591]
Als je scherm te smal is worden de koppelingsknoppen "Niet toestaan"/"Op verzoek"/"Automatisch" heel lelijk afgebroken.  Misschien een generiek oplossing (in het SDS?) bedenken waarbij ze afbreken tot drie verticale knoppen?

**Comment by oharsta** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/530657/227764933-e4a6227a-28b4-435f-9df3-1ab237dd93aa.png">

**Comment by oharsta** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/530657/227764966-af35fea6-909f-409c-8bf3-c96c04e03a0e.png">

**Comment by FlorisFokkinga** [comment]
Works.
