### ISSUE TITLE
As a CO admin, I want to be able to remove service groups after the service has been disconnected from the CO, so I can clean up the groups

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#592]
Nu blijven de groepen bestaan, en de CO admin mag ze niet weghalen.  Dat is op zich wenselijk, want als je per abuis ontkoppelt wil je niet dat direct al je autorisaties weg zijn.  Otoh wil je misschien wel dat een CO-admin zulke groepen met de hand mag verwijderen als hij dat wil.

**Comment by FlorisFokkinga** [comment]
Works.
