### ISSUE TITLE
As an CO admin, I want the controls (buttons, checkboxes) from the members table also available in the group members table, so I can edit group membership more easily

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#593]
- Top buttons when members are selected
- Check boxes at every row
- Hover buttons at the right side of every row

**Comment by FlorisFokkinga** [comment]
Done

![Image](https://user-images.githubusercontent.com/80269262/236787348-e73a5317-56d2-47d1-8f37-e1e2d48ac818.png)
