### ISSUE TITLE
Groepen sorteren op "For Service" werkt niet goed

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#594]
![Screenshot 2023-03-20 at 15 42 50](https://user-images.githubusercontent.com/1461740/226375019-c6f76f35-44c9-47a7-b2c7-113b12725ad8.png)

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/bc6b1f6b8ab6e506e7f701760916f8eeb1d38d7c
