### ISSUE TITLE
Als ik in een Service de permissies per Org omzet, wordt dta niet live geupdate in het CO-scherm

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#595]
Zie screencast.

https://user-images.githubusercontent.com/1461740/226376824-ee8aea4b-07ba-49f1-a74b-d6f5c7e315f3.mov

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/dd891c36d4da0ff9f9da67c4f57d1e39176c9549

**Comment by baszoetekouw** [comment]
works
