### ISSUE TITLE
Verkeerde tekst in accept knop voor Service Admin

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#597]
Staat "show me the orgnisation" ipv "service"

![Screenshot 2023-03-20 at 15 55 38](https://user-images.githubusercontent.com/1461740/226379249-72fd7b09-d658-4c3c-a853-78a2ebcd8d92.png)

**Comment by FlorisFokkinga** [comment]
The translation is `ok: "Accept, show me the {{type}}",`. Is the wrong type used here?

**Comment by FlorisFokkinga** [comment]
.
