### ISSUE TITLE
SameSite property for subscription_id cookie

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#599]
Firefox warns:

> Cookie “subscription_id” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

What is this cookie used for?  It it safe to set it to `SameSite: strict`?

**Comment by oharsta** [comment]
@baszoetekouw Cookie is used in the live websocket update's to avoid update in the tab which caused the change. Does not have to be sent in third-party contexts.

**Comment by baszoetekouw** [comment]
ok
