### ISSUE TITLE
Unable to change expiry date to something beyond 30 April

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#607]
Al ik de verlooptijd van de collaboratie "SURF NGNlab"
https://sram.surf.nl/collaborations/226/admins
probeer aan te passen naar een paar maanden in
de toekomst, dan verspringt de ingevulde datum
naar 15 april. Zo je zien is 30 april de laatste
datum die ik kan kiezen.

Dit is zowel Firefox 111.0.1 als Safari 16.4 op
MacOS Ventura 13.3.

**Comment by oharsta** [comment]
@arnoutt Can you reproduce this on the test environment. I don't have rights on production. On test I can choose a expiration date of the collaboration (as well as the member expiry date) way in the future.
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/530657/228818653-e20d58f9-44f8-4f94-96f5-8108e5ead9c1.png">

**Comment by arnoutt** [comment]
On test it indeed seems to work. So you probably already solved it before then. Thanks!
