### ISSUE TITLE
SURF Ram turns out to be a goat

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#608]
A ram really is not a goat, but a sheep.  Please replace the goat sound by a sheep sound.  @arnoutt could you select an appropriate sheep (e.g., from https://freesound.org/search/?q=sheep).

**Comment by arnoutt** [comment]
Please use the following fragment

[Archive.zip](https://github.com/SURFscz/SBS/files/12213580/Archive.zip)

**Comment by baszoetekouw** [comment]
Ja dat is een beter schaap
