### ISSUE TITLE
Organizational access for service: 'Always allow' radio button doesn't allow organisation that was specifically disallowed

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#618]
Reproduction
- Go to service, tab 'Organizational access'
- select 'Choose permission for each organisation'
- disallow an organisation
- select 'Always allow connections from collaborations for all organisations'
- Go to a CO, tab 'Services'
  - Observed: service not listed
  - Expected: service listed and connectable
- Go to an organiation, tab 'Services'
  - Observed: service cannot be enabled
  - Expected: switch to make the service manadatory

**Comment by oharsta** [comment]
Er zit inderdaad een bug in de logica voor “Always allow connections from collaborations for all organisations”. In de huidige implementatie toggle ik alleen het veld “automatic_connection_allowed” in de database voor die service. Maar ik moet er ook voor zorgen dat alle organisations toegang hebben tot deze service. Maar dat betekent wel dat als je daarna weer switcht naar “Choose permission for each organisation” alle organisations op “Always” staan. Ofwel de gebruiker moet dan weer met de hand kiezen welke organisatie op “Disallow” of “On request” moeten komen. Dat is onvermijdelijk.
Dus ik denk dat we een confirmation dialog moeten tonen als een gebruiker ervoor kiest om “Always allow connections from collaborations for all organisations” aan te zetten.
Hetzelfde geld overigens voor de optie “Manually approve connection requests from collaborations for all organisations”. Als je die optie kiest en weer terug gaat naar “Always allow connections from collaborations for all organisations”, dan hebben alle organisations de optie “On request”. Dus daar moet dan ook een confirmation dialog voor.

**Comment by baszoetekouw** [comment]
works now.
