### ISSUE TITLE
Redesign service headers (continued)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#623]
Continued from #466.
The headers with the metadata-list element, as currently implemented, don't really work. We need a design better suited for our application.

**Comment by FlorisFokkinga** [comment]
Design sketch for the organisation header: https://gitlab.surf.nl/sram/ux/-/issues/12

**Comment by oharsta** [comment]
![Image](https://github.com/SURFscz/SBS/assets/530657/406cfd5c-19c5-41d4-b38b-1d228a43e736)

@Floris, we remove the following from the header (just to check):

- description
- policies
- compliant policies

**Comment by FlorisFokkinga** [comment]
That's correct.
Unfortunately this design shows the tabs and label of a CO, which are not present for a service, of course.

**Comment by FlorisFokkinga** [comment]
The links for 'Launch service' and 'visit public website' have changed places.
'Launch service' should be the login URL, and vice versa.

**Comment by mrvanes** [comment]
- Shortname is missing
- "CO's" has become "collaborations"
- "L/launch service" has become "Open the service" and
- "visit public website" has become "visit the website"

![Image](https://github.com/SURFscz/SBS/assets/1901782/ec618321-fa3b-44eb-9dcd-1450ce22c4ad)

**Comment by baszoetekouw** [comment]
Fixed in c29d98f
