### ISSUE TITLE
Org API: automatically add myself as admin

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#629]
As a user logged in to a service using the org API to create a new CO, I want to be able to add myself as an admin of that CO. Thus, I no longer need to invite myself afterwards via email.

Since the user is logged in to a service through SRAM, we have all the information we need (and permission is granted by the user?)

**Comment by oharsta** [comment]
Add an optional admin_identifier which if present is the uid of the user who will be made admin.

**Comment by mrvanes** [comment]
Tested by Martin
