### ISSUE TITLE
If a SCIM sweep for a single service fails, don't stopp running for other services

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#630]
It seems that currently, if the SCIM sweep for a single service fails (because of a remote server error, of service that is unavailable, etc), the sweep for subsequent SCIM servers is never run.

**Comment by HarryKodden** [comment]
I have tried to verify behaviour.
Setup 2 SCIM Servers
1 is not reachable
2 is reachable
Both are configured for sweep every hour
In SCIM endpoint [2] a group is manually deleted,
Expected result after passing the hour (23:00) that sweep will provision that group again.

Test fails ! Did not see the group reappearing again.

**Comment by baszoetekouw** [comment]
@oharsta Kun jjij hier nog naar kijken?

**Comment by baszoetekouw** [comment]
@HarryKodden kan het ook niet meer reproduceren, alles werkt nu goed.  Dus toch al gefixed in de vorige release

**Comment by HarryKodden** [comment]
This issue is apparantly fixed. Problem no longer observed. Whenever a SCIM Server is unreachable, the SBS Server log list 1 error, which is fine.
