### ISSUE TITLE
Redesign TOTP token recovery screen

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#656]
### Current screen ###
![Image](https://user-images.githubusercontent.com/80269262/233567761-0ac975d2-1221-4b52-91f5-de7b5e29e8b9.png)

**Comment by baszoetekouw** [comment]
Maybe also add option to send recovery code to to org admin or support desk

**Comment by FlorisFokkinga** [comment]
![Image](https://github.com/SURFscz/SBS/assets/80269262/524f99e4-900e-4e7b-b219-527de539eb33)
