### ISSUE TITLE
If at all avoidable, don't break words

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#660]
![Image](https://user-images.githubusercontent.com/8791564/226610591-e9e6b8a2-345d-4c3a-b057-c319807daf7c.png)
For chips use overflow ellipsis.

**Comment by arnoutt** [comment]
For the chip, use css text-overflow: ellipsis to ensure text stays within 1 line

![Image](https://user-images.githubusercontent.com/8791564/233577390-7e4bf56f-b6e6-461d-85cb-6fbd0167ce98.png)

**Comment by FlorisFokkinga** [comment]
These two examples have been tested and are fixed.
