### ISSUE TITLE
As a user, I want to easily be able to find the public documentation from the GUI, so I can learn more about the concepts

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#667]
Let's solve this by using the footer with three elements, available in the SDS. Colours can remain as they are now, black on light grey.

![Image](https://github.com/SURFscz/SBS/assets/80269262/4bf3535a-80a1-4bc7-8b4e-62836088c922)

`Support      Terms of Use      Privacy policy               NL | EN                  SURF`

`Hulp      Gebruiksvoorwaarden      Privacyverklaring               NL | EN                  SURF`

**Comment by oharsta** [comment]
@FlorisFokkinga Can you change the link to the support page: https://github.com/SURFscz/SBS/blob/main/client/src/locale/en.js#L1760

**Comment by baszoetekouw** [comment]
tested
