### ISSUE TITLE
Update the file upload UI to follow the SDS

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#684]
https://design.surf.nl/#file-upload

**Comment by oharsta** [comment]
@FlorisFokkinga Just saw that the SDS uses the browser L&F for the "Choose File" text. This means it is not translatable to Dutch. Is that acceptable?

**Comment by FlorisFokkinga** [comment]
Yes, that is fine. If a user uses a browser in a specific language, we'll have to assume they understand that language.

**Comment by FlorisFokkinga** [comment]
Works.


![Image](https://user-images.githubusercontent.com/80269262/236777032-9cccea04-93d0-42f2-ae81-1e6a5e667ff7.png)
