### ISSUE TITLE
As a new user, I want to very easily provide feedback if I have to register a TOTP although my IdP already provides MFA

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#689]
- Add a link to the feedback form from the setup TOTP page in the login flow.
- Add the friendly IdP name in the text so we can explain to the user what counts as a 'second time' 2FA is required.
- When using the link, place the text in the feedback window, including the IdP domain so we are sure which IdP it is about.
<img width="648" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/355b9afc-d3a3-41f5-989a-3c05ece65ec9">

```
SURF Research Access Management now requires two-factor authentication. This means you have to set up an extra check to verify it's you.

Did you already use a second factor to sign in at TU Delft? Please [contact us] so we can fix that.
```
```
SURF Research Access Management vereist sinds kort twee-factor-authenticatie. Dat betekent dat je een extra controle dat jij het bent moet configureren.

Heb je al een tweede factor gebruikt om je aan te melden bij TU Delft? Neem dan [contact op] zodat we dat kunnen oplossen.
```
<img width="509" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/072dbb55-33a7-402d-b68d-7cb82e69c630">

```
I had to setup two factor authentication with SURF Research Access Management, but I already used two factor authentication to sign in with tudelft.nl.

Thanks for your feedback! Feel free to add anything else.
```
```
Ik moest twee-factor-authenticatie configureren bij SURF Research Access Management, maar ik heb al een tweede factor gebruikt om aan te melden bij tudelft.nl.

Bedankt voor je bericht! Je kunt informatie toevoegen, als je wil.
```

**Comment by baszoetekouw** [comment]
@oharsta There is a annoying problem here: we need the `schacHomeOrg` to lookup the name of the IdP, but when the user logs in for the first time, the `schacHome` is not yet available (because the user was redirected from the proxy_authz endpoint).  
However, we do have the entityid of the IdP available (in the `issuer_id` attribute of the proxy_authz call).  Would it be possible top use the entityid to match (if no schachome is found)?  Quite annoying, I know, because we currently don't store the IdP entityid, and it can only be populated from the proxy_authz call...

**Comment by baszoetekouw** [comment]
Or alternatively, we could populate the `schachome` in the `proxy_authz` call from the `issuer_id`.  That way, we would only need a lookup table {`entityid` -> `scope`} which we can create alongside the existing {`scope` -> `displayname`} lookup tabel that we already create in a cronjob.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/6753a380f7622559749369409b7d72fb9eaf9590

**Comment by oharsta** [comment]
@baszoetekouw The issuer_id is used to lookup the schac_home - see for the tests: https://github.com/SURFscz/SBS/commit/6753a380f7622559749369409b7d72fb9eaf9590#diff-e659281fa69e63a656afbcddd812d1689cadd782a328e84b8e52ecc814df9bdfR24 - but it seems the issuer_id can also be None. Can you confirm this?

**Comment by oharsta** [comment]
The `issuer_id` is not None, but the IDP metadata does not contain all entity_id values. We now use the entity_id as a fallback if we can't get the display name. Which on production is very unlikely.

**Comment by baszoetekouw** [comment]
Indeed, by default we only read in the plain eduGAIN metadata, but in test/acc we also have other IdPs (SURFnet acc, eduID test etc) which are not part of edugain.  
The only IdP for which this occurs on prod is EduID, so we should probably fix that (maybe by simply allowing additional mappings in the config file).

**Comment by baszoetekouw** [comment]
I'll create a new issue for that; is not very high prio, because eduid in prod will use its own MFA solution, so eduID user will never see this screen anyway.
