### ISSUE TITLE
Make CO pages available using uniqueIdentifier (instead of database row id)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#704]
Currently, CO pages are available as https://test.sram.surf.nl/collaborations/3137/
For normal use, that is fine, but we are also exposing these pages as external links in the ldap (so a service can ready the CO url from the ldap and show it to their users).

However, this means that the database rowids are exposed in the ldap and in external systems, which makes it hard to change them.  In addition, this makes monitoring of test hard, because the rowids change whenever the seed is reset.

So would it be possible to add a redirect for COs based on their UniqueIdentifier,, so that (for example), https://test.sram.surf.nl/collaborations/a71a2b01-4642-4e1a-b3ac-0a06b2bf66f2/ would redirect to https://test.sram.surf.nl/collaborations/3137/ ?
We could then use these "public" links in the ldap instead of the internal rowids.

**Comment by oharsta** [comment]
https://test.sram.surf.nl/collaborations/a71a2b01-4642-4e1a-b3ac-0a06b2bf66f2

**Comment by mrvanes** [comment]
Correct
