### ISSUE TITLE
SCIM: sweep delete should remove all occurrences that match 'externalId's

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#705]
Because of #662 remote SCIM servers could have multiple occurrences of certain Groups. At this moment sweep does not remove them.
Suggested to change logic that all remote orphan occurrences are being removed.

**Comment by baszoetekouw** [comment]
@HarryKodden is this only te clean up after an old bug, or is it generic functionality that is also useful in other circumstances?
