### ISSUE TITLE
Geen remote content in mails

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#707]
Graag remote content uit mails verwijderen (of vervangen door attachment):

```
            <img style="max-height: 200px;max-width: 200px;border-radius: 8px;margin-right: 25px"
                 src="https://acc.sram.surf.nl/api/images/organisations/211051aa-c99f-4957-8920-39fee4ade2ec" alt="Percy CO">
```

![Image](https://github.com/SURFscz/SBS/assets/1461740/563a4f94-1876-40a3-8337-3c893607652f)

Zie ook #492

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/a894baf4bf2a19349537036e21319255f3876dd2

**Comment by oharsta** [comment]
https://www.appsloveworld.com/coding/python3x/33/sending-email-with-inline-images-flask-mail

**Comment by baszoetekouw** [comment]
In Gmail werkt het nu goed, maar in TB gaat er nog iets mis met het plaatje:

![Image](https://github.com/SURFscz/SBS/assets/1461740/aaeb1c4f-f7a3-4a88-943c-6d6782eb3b6e)

Ik snap niet zo goed waarom het niet werkt.  De `<img>` tag lijkt hetzelfde als wanneer ik vanuit TB zelf een mail met plaatje stuur:
SBS doet:
```
<img style="max-height: 200px;max-width: 200px;border-radius: 8px;"
          id="<logo>" src="cid:logo" alt="UU" apple-inline="yes" class="Apple-web-attachment Singleton">
```

en TB:
```
<img moz-do-not-send="false" src="cid:part1.0SRJx1vR.aoCCuE9E@gmail.com" 
          alt="tomaat" width="322" height="297" align="left">
```

Enig idee wat het probleem kan zijn?

**Comment by FlorisFokkinga** [comment]
We don't know what's causing this. Let's leave it at this.
