### ISSUE TITLE
Show AUP for free-for-al services when logging in to the service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#710]
the AUP for services that are allowed without Co membership is now never shown.

Only show the AUP when the user is logging in to the Service itself.  Not show the AUP screen in the regular SBS interface.

**Comment by oharsta** [comment]
@baszoetekouw Are you sure that the AUP is not shown. I have only changed a test (not the actual code) that confirms that for Services that are marked `non_member_users_access_allowed` the AUP is also shown. See https://github.com/SURFscz/SBS/blob/main/server/test/api/test_user_saml.py#L84

**Comment by oharsta** [comment]
The Service must of course has an `accepted_user_policy`, because otherwise we don't redirect to `service-aup`

**Comment by baszoetekouw** [comment]
Klopt inderdaad, het werkt hier nu goed.
