### ISSUE TITLE
Remove reference to user-requested service from seed

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#711]
The functionality where users can request connecting a CO to a service was removed from SBS (see https://github.com/SURFscz/SBS/issues/198).  Please also remove the functionality to view these requests in the UI:

![Screenshot 2023-05-15 at 13 02 12](https://github.com/SURFscz/SBS/assets/1461740/50fa7633-cd05-46ad-a576-90252c9389e3)

and maybe also from the seed.

**Comment by mrvanes** [comment]
Correct
