### ISSUE TITLE
Org manager is shown an exclamation mark for an expired org admin/manager invitation, but cannot resend or remove

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SBS#720]
Example of notification mark:

![Image](https://github.com/SURFscz/SBS/assets/8132520/20cfc232-50fd-4c7f-9b94-4177a9d64708)

In this particular example it looks like an invite has expired. As an org manager I cannot remove this. Therefor the notification is of no value to me.

**Comment by FlorisFokkinga** [comment]
The problem here is that an org *manager* cannot, but the org *admin* can.

**Comment by mrvanes** [comment]
Correct
