### ISSUE TITLE
Redesign for the CO page header

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#735]
Split from
- #623
(The about tab was redesigned in #708.)

![image](https://github.com/SURFscz/SBS/assets/80269262/c251bf4f-0db4-4359-aae0-87df1665a0e3)

## CO members ##
- Members: show as 'no members' when none exist
- Groups: show as 'no groups' when none exist
- Visit website: hide when it has no value
- Membership: show as 'Expired' when expired. The existing alert bar is used to notify the user when it is about to expire or has expired.

## CO admins ##
- Members: show as 'no members' when none exist
- Groups: show as 'no groups' when none exist
- Membership request link [icon](https://www.streamlinehq.com/icons/streamline-regular/interface-essential/copy-paste/duplicate-1)
- Expiration date, [icon](https://www.streamlinehq.com/icons/streamline-regular/images-photography/timer/timer)
  - Expires March 29, 2024
  - Expired
  - Hide when no expiration date is set.

**Comment by FlorisFokkinga** [comment]
Find an icon that better represents the expiration date.

**Comment by oharsta** [comment]
fixed in https://github.com/SURFscz/SBS/commit/33dfd811d22d9a069ae1d5d8853445816300a23d
