### ISSUE TITLE
When creating a new CO using the Org API, the logo is not checked for validity

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#745]
Specifically, the `/apidocs` uses this example to create a CO:
![Screenshot 2023-06-01 at 12 50 21](https://github.com/SURFscz/SBS/assets/1461740/fbdae93d-7fff-4581-bf1d-494d8b6d0173)

Note the `...` in the middle of the picture data.  

It seems this logo data is put directly into the SBS database without checking if it is a valid picture.  Please add a check if the provided logo data is valid.  That means:
 - max 500kB
 - valid png (or svg?)

Also, it would be nice if we can rescale/exapand the image to the correct dimensions that the web interface GUI also provides.

**Comment by baszoetekouw** [comment]
Also see #849

**Comment by oharsta** [comment]
In the web GUI we support 2MB for the picture.

**Comment by baszoetekouw** [comment]
🔆 Large pictures like https://stsci-opo.org/STScI-01GA6KKWG229B16K4Q38CH3BXS.png are correctly rescaled and cropped.  
🔆 Also inline images are correctly interpreted.
🔆 Invalid inline images are rejected with `"message": "Invalid Logo: cannot identify image file <_io.BytesIO object at 0x7fa2e1510310>"`
🔆 Uploaden van een groot (3MB) inline image wordt afgekeurd met een 413 (request entity too large)
