### ISSUE TITLE
As a member with a soon expiring membership / of a CO, I want a button on the alert bar on the CO to contact admins, so I can ask them to extend my membership or the CO

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#747]
The button should mailto all the CO's admins.

**Comment by FlorisFokkinga** [comment]
As a member I see the 'collaboration settings button' that leads to https://test.sram.surf.nl/edit-collaboration/3164 and an endless loading animation.
I don't see a button to contact the CO's admins.



![Image](https://github.com/SURFscz/SBS/assets/80269262/3992ab23-ccba-4407-8306-f168ad4f13ea)

**Comment by oharsta** [comment]
The bug of a regular member seeing the "Collaboration settings" is fixed. The button for a regular member to contact the admins is only shown if the membership is soon to expire, not when the actual CO is to be expired. This should be the responsibility of the admins.

**Comment by FlorisFokkinga** [comment]
The bug has been fixed.

I can't see the button for an impersonated member with a soon expiring membership to contact the CO's admins.


![Image](https://github.com/SURFscz/SBS/assets/80269262/b206e8aa-be07-475b-b1cf-fb284879ce0e)

**Comment by oharsta** [comment]
@FlorisFokkinga That is strange as I do see the button.

![Image](https://github.com/SURFscz/SBS/assets/530657/ec0eebb6-3e30-4c77-a505-df9f0ffafc5d)

**Comment by oharsta** [comment]
And when I run the cron job to expire collaboration memberships I see the button as well.

![Image](https://github.com/SURFscz/SBS/assets/530657/75f445e7-c38b-49b6-ac4d-771be9a07d7e)

**Comment by oharsta** [comment]
@FlorisFokkinga The collaboration needs to have at least one admin, otherwise the button is not shown as there are no admin's to mail to.
