### ISSUE TITLE
As a service owner I want to see disabled SURF organisations

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#754]
As a service owner, when connecting a service to organisations I can not find University of Harderwijk unless I check "SURF Service" checkbox. The desired behaviour is finding Harderwijk, but not being able to connect (yet). The greyed out entry should raise a warning on selection (either "on request" or "always").

**Comment by FlorisFokkinga** [comment]
Understandable request, but this would be rather confusing for admins of non-SURF services.
