### ISSUE TITLE
React app uses inline CSS, disallowing strict CSP policy

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#764]
Is it possible to avoid using inline CSS in the react app?  I would like to remove `unsafe-inline` from the CSP, but that breaks the layout at a numebr of places.

According to the Googles, setting `INLINE_RUNTIME_CHUNK=false` during build should fix this, but we already seem to have that in `client/.env`.  Is there anything else we can adjust to fix this?

**Comment by oharsta** [comment]
@baszoetekouw You also need to add `IMAGE_INLINE_SIZE_LIMIT=0` to the `.env` otherwise React inlines small images and that is also forbidden without `unsafe-inline`

**Comment by baszoetekouw** [comment]
We already have both settings
```
INLINE_RUNTIME_CHUNK=false
IMAGE_INLINE_SIZE_LIMIT=0
```
but React still generated inline CSS on a few places.  This becomes apparent when you remove the `unsafe-inline` settings from the two CSP lines in de SBS nginx config:


![Image](https://github.com/SURFscz/SBS/assets/1461740/c1b6b9d9-8ade-49bb-b3dc-786e9d667ffa)

It's hard too see where exactly, unfortunately.

**Comment by baszoetekouw** [comment]
One of the CSS statements in question is the size of the sort button on the tables.  With CSS-unsaf-einline disabled, SBS looks like this:

![Image](https://github.com/SURFscz/SBS/assets/1461740/e4f3ec0f-30ba-48cd-a631-ffd6d794ae75)

**Comment by baszoetekouw** [comment]
@oharsta I've fixed the issue with FontAwesome (see https://github.com/SURFscz/SBS/compare/4306056592b7005bf308e899a76babf4d5bfb87f...5e4cdf59c456a0e75c6aecf01ef1f0128edb86ba); the rest of the issues seem to be in the SDS.  

For some reason, the SDS injects all styles for the SDS components via javascript, instead of putting it in a static file that we can include.  Do you have any idea how to fix that?

**Comment by baszoetekouw** [comment]
This automatic injection of stylesheets seems to be a "feature" of https://www.npmjs.com/package/rollup-plugin-postcss which is used in the SDS.  Any chance you could change that so the SDS simply provides a css fiel that we can include?

**Comment by oharsta** [comment]
SDS does not inline CSS anymore

**Comment by oharsta** [comment]
Fixed by removing lottie-player

**Comment by baszoetekouw** [comment]
We're almost there.  I still get two CSP violations:
- [react-dom.production.min.js:248:65](https://test.sram.surf.nl/static/node_modules/react-dom/cjs/react-dom.production.min.js)
- [emotion-sheet.browser.esm.js:74:22](https://test.sram.surf.nl/static/node_modules/@emotion/sheet/dist/emotion-sheet.browser.esm.js)

**Comment by baszoetekouw** [comment]
wha do we use this library for?

**Comment by oharsta** [comment]
react-select. Used all over the place and complex component to replace.

**Comment by baszoetekouw** [comment]
see https://github.com/JedWatson/react-select/issues/2030
The suggestion there is to implement a nonce, but I'm reluctant about nonces, because it seems fragile and hard to debug.

For now, I've added 5 hash-based exception on the CSP, which seems to fix most issues for now.  Let's see how that hold up and close this issue for now.
