### ISSUE TITLE
When a Service disables ldap, this should be visible in `plsc/sync`

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#765]
Currently, when a Service disabled ldap, this Service is simply no longer shown in the output of `plsc/sync`.  Instead, the service should be shown, but have a `"enabled": false` flag (or something similar).

In addition, the ldap password should be set to None if the ldap is disabled (so when reeanbled, the Service admin has to reset the password).

**Comment by FlorisFokkinga** [comment]
Disabling LDAP for a service changes LDAP from:
```
"ldap_enabled":int 1
"ldap_password":string "$2b$12$QsrNOnWo2cFgZx9chn3iKet0ErNJueY68sd4xIwb7Csj.DVjNZZWm"
```
to
```
"ldap_enabled":int 0
"ldap_password": NULL
```
