### ISSUE TITLE
PUT request for invite accept contains too much info

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#772]
The PUT on /api/invitations/accept when a user accepts an invite is way too verbose and contains too much data.
The call only need a `hash` value, but the client PUTs a 20kB json blob including all user info and info about all their COs.

This seems to be a general problem in SBS: the frontend receives (and sends) way too much information from the backend.  This also leads to possible information leaks.

Attempt to document desired behaviour is documented here: https://confluence.ia.surf.nl/display/SRAM/API+and+authorization+rework

**Comment by FlorisFokkinga** [comment]
We need a better, more generic solution for this.
