### ISSUE TITLE
As a SURFconextverantwoordelijke, I want to be able to see which of my users have an account in SRAM and in which Orgs/COs they are active

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#775]
@arnoutt is dit wenselijk?

**Comment by arnoutt** [comment]
You mean from within SBS My idea there was to allow organisation admins to see (already possible?) and export (need to build that) this information. That seems enough to me. The SCverantw. can always ask the org. admin for this information then.
