### ISSUE TITLE
LDAP passwords shouldn't contain special characters

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#779]
rare tekens in ldap passworden geven problemen voor uva/gitlab

**Comment by FlorisFokkinga** [comment]
@baszoetekouw Does this include all ASCII special characters?

**Comment by baszoetekouw** [comment]
Yes, please change the passwords for ldap to this spec:
 - 32 chars
 - starts with a letter (lowercase or capital)
 - contains random chars from this set: A-Za-z0-9@%=+_-

**Comment by baszoetekouw** [comment]
works
