### ISSUE TITLE
Org-API extention: list open invites per CO

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#795]
It is currently not possible to fetch al list of outstanding invitation.  Please add an Org API call that return a listing of open invites for a CO.

**Comment by oharsta** [comment]
@baszoetekouw The implementation is simple, however there is one snatch. When invitations are created through the API then we generate an external_identifier soo the API client can look them up later. Also invitations with an external_identifier are never deleted. Normal invitations created in the GUI do not get an external_identifier and they are deleted on acceptance. When we return all open invitations for a CO then we also return invitations that do not have an external_identifier. This is not a problem, but the API client can not use the existing API method to get the details of an invitation as the lookup is currently done on external_identifiers.

**Comment by baszoetekouw** [comment]
Couldn't we simply also generate an `external_identifier` for invitations generated from the GUI?

**Comment by baszoetekouw** [comment]
Tested, and works.  I've created #864 for the identifier issue.
