### ISSUE TITLE
As a service admin, I want to be also able to set a website URL as support contact, so I can point users to a ticketing system or forum for help

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#799]
So the service contact should be either a URL or email address.
The labels can remain unchanged.
Placeholder texts must be updated to indicatie an URL is also possible:
```
The email address or the website of the support department for this service
Het e-mailadres of de website van de helpdesk voor deze dienst

```

We'll rewrite the members and CO admin facing text when implementing #708.

**Comment by FlorisFokkinga** [comment]
URL can be entered, but displaying it is on hold for
- #708

**Comment by baszoetekouw** [comment]
The cards currently show the "Administrative email address" instead of the "Support for end user" address under "Support"

**Comment by FlorisFokkinga** [comment]
If a service has website set as support contact, it is displayed as a mailto-link on the service card.
![image](https://github.com/SURFscz/SBS/assets/80269262/b983c7d6-34b7-479a-8e29-13a65e50ad70)

**Comment by baszoetekouw** [comment]
Ik stel voor dat we deze bug na release v25 even met een minor release fixen.
