### ISSUE TITLE
As an admin of a CO using sensitive data I want see a history of user role changes so I know what users have had access

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#824]
- Permit the CO admin to view the CO's audit logs
- Permit the ORG manager and ORG admin to view that organisation's COs audit logs
- Filter the 'Updated Collaboration <CO name> at <timestamp> by Unknown.' update last_activity_date messages. Do we want to show these?
- To make the page more readable, for the CO admin, don't show events where only the 'last activity date' was changed, i.e., caused by an authentication.
- For the CO admin, show the third button in the header as 'History'

**Comment by FlorisFokkinga** [comment]
As a CO admin, I see fewer rows then as platform admin.


![Image](https://github.com/SURFscz/SBS/assets/80269262/629875a9-f39c-4a4f-9d50-836406511723)



![Image](https://github.com/SURFscz/SBS/assets/80269262/39bc1df4-5287-40a1-8866-2731b904a02f)


Specifically, rows about new and removed members are important for this story, since it tells about who has had access to the services with the CO's authorization. Rows only about updates of 'last activity date' should be filtered out.

**Comment by oharsta** [comment]
@FlorisFokkinga You are right. I forgot one exclamation character.

**Comment by FlorisFokkinga** [comment]
This new collaboration membership is still missing in the table for the CO admin:

![image](https://github.com/SURFscz/SBS/assets/80269262/81e634a0-c656-4dcb-a198-6482e186d147)

The platform admin's view:

![image](https://github.com/SURFscz/SBS/assets/80269262/40745403-fb48-4cbe-8faa-0e471a25b2ff)
