### ISSUE TITLE
Service connection request link results in redirect loop for unauthorized user

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#835]
For example: https://test.sram.surf.nl/service-connection-requests/AXvSmBb6E1BYbOSV04_4JsYT9mNi3gPnOroCS574WaMg

**Comment by FlorisFokkinga** [comment]
It seems service connection requests user a hash in the email, like an invitation.

We've decided that instead only the service admin of that service or a platform admin should be able to approve or deny a service connection request.
In case there is no service admin, send the email with the request to the platform admins.

**Comment by oharsta** [comment]
Also deleted email templates which were not used anymore. https://github.com/SURFscz/SBS/commit/aded1d6084f9e308d3b205ee2c028d91c0588479

**Comment by FlorisFokkinga** [comment]
Works. Permissions tested in the GUI only.
