### ISSUE TITLE
Group creation or deletion via Org API is not transmitted through websocket

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#862]
When a group is created or deleted via the Org API, the changes don't seem to be transmitted via the web sockets (so open webpages are not updated).

Same for group membership updates.

**Comment by oharsta** [comment]
@baszoetekouw The web sockets update mechanisme uses the session store to store a unique uuid which is send as a cookie in each request to the server. The value is returned from the server in the websocket payload to avoid unnecessary reloads. The Flasgger site does not generate a unique uuid, but does send the cookie value, when testing flasgger in a browser where the SBS is open in a different tab. Therefore the update will not happen as the uuid's are equal. If you use a different browser than it will work.

**Comment by baszoetekouw** [comment]
When creating a group, it indeed shows up in a different browser as you describe.  When deleting a group, however, it doesn't.

**Comment by baszoetekouw** [comment]
tested
