### ISSUE TITLE
When updating attributes for users from OIDC claims, don't _remove_ attributes

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#866]
When user attributes are updated from OIDC claims, currently attributes are set to NULL if the corresponding OIDC claim is missing.  This is undesired, as this means that upstream bugs could currupt our database.

So, the desired behaviour is:
 - if an OIDC claim is present and set to `null` (or an empty list, if applicable), clear it from the database, _except_ for the `uid`, `name`, and `email` attributes, which should be never set to `NULL`.
 - if an OIDC claim is not present or is set to the empty string, do _NOT_ update the database, but log a critical error to the log (and mail) instead (and let the user proceed with their existing database attributes).
 - otherwise, if an OIDC claim is present and different from the database attribute, update the database

(see also  #773)

**Comment by oharsta** [comment]
@baszoetekouw Question about bullet number two: we only log / mail the error is the OIDC claim was previously set on the User (e.g. it has a value which we don't want to set to None because of it's sudden absence in the claims)?

**Comment by baszoetekouw** [comment]
@oharsta yeah, that sounds good!
