### ISSUE TITLE
Redesign UI organisational access for service admins

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#867]
This needed another iteration.

At the service page, add a section 'Connection settings' to the 'Details & Settings' tab.

![Image](https://user-images.githubusercontent.com/80269262/259404755-2fc30f7e-39e0-4901-b6bc-1d9ce8fd1f46.png)

The third option (everyone) at question 1 should only be visible for Platform admins.

![Image](https://user-images.githubusercontent.com/80269262/259404802-6d8d10cb-6985-470a-8912-64eca9785bf7.png)

The list with institutions should only be visible if 'Only some' and/or 'It depends' are selected. Their selectors 'Institutional access' and 'CO connection' should be greyed out if 'All institutions' or 'Yes' or 'No' are selected, respectively.

![Image](https://user-images.githubusercontent.com/80269262/259404837-97c37f78-f951-4a7a-8383-5d2ba7d725c7.png)

Rename the tab ‘Collaboration access’ to 'Connected collaborations'
```[tasklist]
### Tasks
- [x] Translations
- [x] Coverage
- [x] Review server-logic for connection allowed
- [x] SegmentedControl GUI styling
```

**Comment by FlorisFokkinga** [comment]
We've discussed this story falls apart in three:
1. The block-cards instead of the radio buttons and checkbox
2. The table with organisations with two segmented selectors instead of one
3. Moving the tab to a section under 'Details & settings'

We agree the block-cards are an improvement.
We all doubt if splitting the segmented selector in two is really an improvement.
The table might be a bit hard to implement nicely, because of with constraints as a settings section.

Please implement the hblock-cards, than we'll take a look at the tab on TEST.

**Comment by oharsta** [comment]
Fixed in last commit

**Comment by mrvanes** [comment]
- First card members misses "CO-" prefix
- "Can a collaboration directly connect?" raises expectation of selecting collaborations in the table, but I see organisations?
- "It depends" reads as "It depends on collaboration" (because of header), but subtitle says "Manage settings per organisation", which is what the table does.

**Comment by FlorisFokkinga** [comment]
- #923 should have mitigated this.

Let's ask feedback from users
