### ISSUE TITLE
Tweaks for service cards

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#881]
Some tweaks for the new Service cards layout:
 - allow searching cards (especially in the list of unconnected services)
 - sort the cords in a menaingful way
 - make the launch button a regular link so you can copy the url or ctrl-click to open in a new tab.
 - as CO admin, you can't launch the service
 - I'm not convinces about the placement and colors of the "pending" and "active" tags; because they are in the position where also active buttons are located (if present), it almost seems that they also are an active component.  Also, why is are the Pending and Active tags both orange?  Looks like a warning to me.
![Screenshot 2023-08-16 at 10 52 06](https://github.com/SURFscz/SBS/assets/1461740/dac2f428-9266-4230-a5ee-5d93b1bc4fcc)

**Comment by oharsta** [comment]
@FlorisFokkinga Can you pick the last three bullets? I'll add the search and sorting. I'm not sure about the button becoming a link. This is from the SDS and when you click the Launch then a new tab is opened, where you can copy / paste the URL.

**Comment by oharsta** [comment]
Added launch link for admins

![Image](https://github.com/SURFscz/SBS/assets/530657/b5211d9e-bac9-44c2-838a-76552ba273ce)

**Comment by FlorisFokkinga** [comment]
Let's leave the button an SDS compliant button, as it is now.

Contrary to the design, chips are only show on services with a pending request and mandatory services. Mandatory services will be removed, so only those for pending requests will remain.
I'll make them the same colour as the application bar, so it's clear they are not a warning.

**Comment by FlorisFokkinga** [comment]
Please remove the 'Enabled by organisation' text. We'll place that in a badge for as long as mandatory services exist.

![Image](https://github.com/SURFscz/SBS/assets/80269262/86ae10b5-c689-42ee-8b29-308b58e12fbb)

**Comment by baszoetekouw** [comment]
works as specced
