### ISSUE TITLE
Disable UI element to enable new Org Services

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#884]
We want to remove the Org Services concept on the long run, but that takes some migration.
Therefore, we will start by disabling the functionality in the UI, so that this functionality cant be enabled anymore for new Orgs/Services.

Please either hide the Org Services tab for non-platformadmins, or show it be only with disabled controls.  The latter is probably more transparent for the users, but possible also more work?

Overall epic in #421

**Comment by oharsta** [comment]
Disabling the controls ends up with a very strange tab where you just the all the services available. We would need to add some context as to why this page is read-only. For now just hide the tab when not a platform-admin. Looks like the cleanest solution.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/e3044bfb09ffc20a38d3864d118883efb98a068c

**Comment by baszoetekouw** [comment]
Looks good.
