### ISSUE TITLE
Move the onboarding message to the request/create CO screen for non-org admins

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#900]
The message is now on the welcome screen, where the only thing a user can do is request or create a CO. After the users is member or admin of anything, this message is never seen again.

![CO request message](https://github.com/SURFscz/SBS/assets/80269262/6d8e421d-beac-4766-bc0a-1d9906c3b772)

**Comment by baszoetekouw** [comment]
werkt.
![Screenshot 2023-09-18 at 15 26 46](https://github.com/SURFscz/SBS/assets/1461740/3877fd7d-591d-4f88-9358-a6ee23fa404b)
