### ISSUE TITLE
Change special buttons in service form to links

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#901]
![Image](https://user-images.githubusercontent.com/80269262/263204993-80b2b971-e602-4ff0-85f3-1752ec1322f7.png)

![Image](https://user-images.githubusercontent.com/80269262/263207336-bd710fee-7a93-4203-b1ff-0ce9891fb64b.png)

**Comment by baszoetekouw** [comment]
as designed.
