### ISSUE TITLE
Move CO labels in header to line of organisation name

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#903]
# Problem

![Image](https://user-images.githubusercontent.com/80269262/262985481-1a50db17-42ab-48cd-83b9-8c7230fb632b.png)

# Solution
Place the labels in line after the organisation name

**Comment by baszoetekouw** [comment]
it now looks like this: 

![Image](https://github.com/SURFscz/SBS/assets/1461740/d41a675a-5212-40b5-b53a-4399d4baa18f)

It's not after the org name as specified, but I think this is a better solution than @FlorisFokkinga suggested.
