### ISSUE TITLE
Change table header layout, remove tab icons and counters

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#905]
The icons and especially the counters make the pages look busy, while providing little functionality or actionable data.

 - Remove the icons and the counters from the tabs
 - Add headers to all tabels
 - Move the button to add an element to the table to the right, so it aligns with the buttons on the object headers
 - Shift the search field and other input fields to the left

<img width="1424" alt="table_title-button_right" src="https://github.com/SURFscz/SBS/assets/80269262/7d96658e-a83e-4550-b360-d3211c393e2a">
Mock up for the table header. Note the tab icons are still shown here.

**Comment by baszoetekouw** [comment]
@arnoutt is this ok?

**Comment by FlorisFokkinga** [comment]
# With counters and icons
![Image](https://user-images.githubusercontent.com/80269262/250111974-84964c0c-25fc-4610-a457-75d29d916b8c.png)

# Without counters and icons
![Image](https://user-images.githubusercontent.com/80269262/250112009-04523b4c-509f-4101-b4ab-c9e0d869174d.png)

# Where to place counters
The counters should be in the table title, as was originally designed, but is only used on a few places in the application.

The button to add an element to the table should be moved to the right, to align with the buttons on the object headers. The search field and other input fields should shift to the left.

<img width="1424" alt="table_title-button_right" src="https://github.com/SURFscz/SBS/assets/80269262/7d96658e-a83e-4550-b360-d3211c393e2a">

## Extra counters

Home |  
-- | --
Organisations | -
Collaborations | -
Platform admins | -
Services | -
Users | -

Organisation |  
-- | --
Collaborations | -
Requests (CO, services) | Keep notification on open requests
Organisation admins | Header
Services (mandatory) | -
API tokens (org) | -

Collaboration |  
-- | --
Admins | About tab for members, header for admins
Members | Header
Groups | Header
Services (connected) | About tab for members
Join requests | Keep notification on open requests
Service tokens (introspection) | -

Service |  
-- | --
Admins | -
Groups (service) | Header
Organisational access | (Should be moved to settings)
Collaboration access | Header
Connection requests | Keep notification on open requests

**Comment by oharsta** [comment]
@baszoetekouw Do you also want to move the button to the left when you're in a general overview page like the this one?

![Image](https://github.com/SURFscz/SBS/assets/530657/80770590-8541-4c5a-8929-d4671917e097)

**Comment by baszoetekouw** [comment]
@FlorisFokkinga @arnoutt could you take a look?

**Comment by arnoutt** [comment]
Agreed we need something better but for now, this is fine IMO.

**Comment by oharsta** [comment]
Is being developed in https://github.com/SURFscz/SBS/tree/feature/redesign-tabs-entities

**Comment by FlorisFokkinga** [comment]
Perhaps reduce the search field width to create some room.

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/f745441aa8a681456d73a6d4dedf6ed9d3f3c9bc

**Comment by FlorisFokkinga** [comment]
Everything seems fine. The only bug I can find is that when there is little text on a tab, it is not centered horizontally.
![image](https://github.com/SURFscz/SBS/assets/80269262/0eb2b278-5be9-4617-8a88-67907d57e2d4)
*Example where 123 and Users are off center*

**Comment by baszoetekouw** [comment]
THis last alignment issues is addressed in #993
