### ISSUE TITLE
As a platformadmin, I would like to be able to copy the email addresses of multiple Services or Orgs in one go, so I can easily contact Services or Orgs in case of issues

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#910]
Fix this in tools.sram.surf.nl
Specifically, add all contact info field to the dump (also admin/security contact)

**Comment by FlorisFokkinga** [comment]
Fix this in tools.sram.surf.nl

**Comment by logan-life** [comment]
desired final state:

**Organizations**
- [x] `email` from `user` object referenced by `organisation_membership` object (org admin, org manager)

**Applications**
- [x] `contact_email` from `service` object (written as sp-contact)
- [ ] `security_email` from `service` object (todo, write as sp-security)
- [ ] `support_email` from `service` object (todo, write as sp-support)
- [ ] `email` from `user` object referenced by `service_membership` object (service admin, service manager)

**Comment by baszoetekouw** [comment]
deployed and confimred working.  See https://tools.sram.surf.nl/
