### ISSUE TITLE
As a Org Admin, I want to be able to specify the groups for a user when I invite them via the Org API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#911]
A PUT to `/api/invitations/v1/collaboration_invites` doesn't allow specification of the groups the user needs to become a member of.  When inviting a user via the GUI, this can already be specified.

I propose allowing the following input:
```json
{
  "short_name": "cumulusgrp",
  "collaboration_identifier": "033cbc91-45ed-4020-bf86-3cc323e1f1cf",
  "message": "Please join the Cumulus research group collaboration page.",
  "intended_role": "member",
  "groups": [
    "12035254-E1F1-4190-9E60-EDAEE8DEE72A",
    "E499F5F8-D9EF-434B-AF32-C349EA62729E"
  ]
  "invitation_expiry_date": 1743014227174,
  "membership_expiry_date": 1743014227174,
  "invites": [
    "rdoe@uniharderwijk.nl"
  ]
}
```
So compared to the current call, this has an extra element `groups`, which is a list of uuids of groups.  As extra bonus, please also allow group shortnames instead of uuid.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw, shouldn't the feature set for the API simply be the same as in the GUI?

**Comment by baszoetekouw** [comment]
@FlorisFokkinga yes, I think this adds the missing functionality to the API.

**Comment by baszoetekouw** [comment]
werkt.
