### ISSUE TITLE
Organisation domain names may contain upper case letters (but then don't have the expected effect)

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#913]
### Observed behaviour
<img width="261" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/7eefda56-2489-4bcc-87d1-96143e5ede95">
A users logged in with this as the Organisation domain cannot request or create a CO.

### Expected behaviour
The input filed normalises the domain name to lower case letters, and then match the IdP domain names, which are also in lower case.

**Comment by FlorisFokkinga** [comment]
The bug is fixed, but it's now possible to enter a duplicate domain name, by entering with upper case letter(s) the second time.

<img width="249" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/5bafaeb3-746f-4f2d-a966-4e83fbb4209e">


<img width="242" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/accc0a56-463a-4fe9-a714-2fa35477e714">

**Comment by baszoetekouw** [comment]
works correctly.
