### ISSUE TITLE
Merge all request tabs for the requester

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#914]
Currently all three request types have their own tab.

![Image](https://user-images.githubusercontent.com/80269262/264979131-be662a07-94c7-4214-bde0-423d17c73404.png)

Please merge those for the requester with the name `My requests` / `Mijn verzoeken` to the right side.
In case a platform admin requests a service , it is acceptable if that request is shown both in the 'My requests' tab and the 'Service requests' tab.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/13cc4d0d41fb8dd7197506fac4d6444472e349ea

**Comment by FlorisFokkinga** [comment]
Works!

<img width="927" alt="image" src="https://github.com/SURFscz/SBS/assets/80269262/78ddbe3c-aeb2-496b-9d27-1ef33e7c8924">
