### ISSUE TITLE
Home button/logo leads to emtpy page for user without role on TEST

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#920]
## Reproduction
- Login with user without any membership or admin role
- Open the 'request service' form
- Click the SURF button on the top left.

## Expected
https://test.sram.surf.nl/welcome

## Observed
https://test.sram.surf.nl/home/organisations
Which is an empty page.

**Comment by FlorisFokkinga** [comment]
This also seems to happen after logging in.

**Comment by HarryKodden** [comment]
Teested, works as expected.
