### ISSUE TITLE
The service token tab is displayed on the service page to a service or platform admin who is member of a connected CO

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#956]
With user token introspection enabled.
This tab should only be visible on the CO page.

**Comment by oharsta** [comment]
@FlorisFokkinga This is by design, see https://github.com/SURFscz/SBS/issues/534. Happy to convert this, but it is not a bug😀.

**Comment by baszoetekouw** [comment]
tested
