### ISSUE TITLE
Units for organisations

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#967]
## Concept
Add organisational units. These units help manage COs for organisations that want to assign specific org managers to specific groups of COs. The feature shouldn't increase complexity for organisations that don't use them. It is enabled by an org admin adding units. Before that none of it is visible to other users.

CO's are assigned to 0, 1 or more units. Org mangers that are assigned to units, can only view and edit COs that belong to one (or more) of their units. To manage which (if any) units a org manager is assigned, an edit org admin screen must be added and the invite org manager screen expanded.

- [x] Create Unit class and many-to-many relationships with OrganisationInvitation, CollaborationRequest, Collaboration and OrganisationMembership and one-to-many relationship with Organisation
- [x] Translations
- [x] Add Units component to create / edit Organisation
- [x] Add Units read-only component to create / edit Collaboration
- [x] Add Units read-only component to create / edit CollaborationRequest
- [x] Add Units read-only component to invite OrganisationMembership
- [x] API changes: all Unit relationships need to be saved on create / update in models
- [x] Add column with units to CO's overview. To make room remove the 'invites' column from all tables with COs
- [x] Check for delete units if they are in use (server side endpoint)
- [x] Display the unit(s) in the CO header
- [x] Only expose CO's to ORG managers that have either no Units or all Units belong to the ORG membership
- [x] Ensure CO managers can not fetch, update or delete CO's they don't have access to
- [x] CO's to be managed component for re-use in edit manager-role and org. invitation
- [x] OrganisationMembership row is clickable (if user is admin and row is manager and organisation has units) and show details with Units component

### Edit organisation
Manage unit labels
![image](https://github.com/SURFscz/SBS/assets/80269262/2cfd6f85-91c5-4d29-a72e-58fa09af4ceb)

### New CO
- Create CO by org admin or org manager: can choose unit
- Request/create CO by user: can suggest unit
![Image](https://github.com/SURFscz/SBS/assets/80269262/94f3fb31-d843-463d-9914-91ab941b322f)

### CO tab for organisation
Add column with units. To make room remove the 'invites' column from all tables with COs.
![image (2)](https://github.com/SURFscz/SBS/assets/80269262/e6c0354b-4452-4008-88c5-ce978e03c0be)

### CO detail page
Display the unit
![image (3)](https://github.com/SURFscz/SBS/assets/80269262/b4c9e236-7519-470b-a51f-2289c9b691d5)

### Invite new org manager
Select 0, 1 or multiple units
![image (4)](https://github.com/SURFscz/SBS/assets/80269262/2e739d48-bdaf-4907-92bb-059d6f801bbf)

### Edit org manager details
![image (5)](https://github.com/SURFscz/SBS/assets/80269262/7bf6b7d6-443b-4ec1-817d-07bcb368d251)

**Comment by baszoetekouw** [comment]
looking good.  Further antfucking in  #1052
