### ISSUE TITLE
escalatiemogelijkheid voor TOTP reset

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#991]
see https://servicedesk.surf.nl/jira/browse/SD-59944

**Comment by FlorisFokkinga** [comment]
If noone responds, please mail SRAM support, so we get an idea how often this occurs and why.

**Comment by FlorisFokkinga** [comment]
![undraw_referral_re_0aji](https://github.com/SURFscz/SBS/assets/80269262/d4e468ff-c2fc-4f85-b265-7ecd60ade4ec)

**Comment by oharsta** [comment]
@FlorisFokkinga The current logic for getting the users who can reset the token:

- Organisation admins of the organisations where the user is a member of
- Collaboration admins of the collaborations where the user is a member of
- Organisation admins of the organisations of the collaborations where the user is a member of
- Organisation admins of the organisation where the user belongs to (based on schac_home)

Once one of the queries (from top to bottom) results in at least one user, the result is returned. Finally if there are no eligible users found, the SRAM info-email from the configuration is returned. Are we going to change this logic? It might be explained in the service-desk ticket, but I do not have access to this.

**Comment by oharsta** [comment]
@FlorisFokkinga Currently the number of users who will receive the reset token is limited to one. Are we going to allow for more then one user to be selected?

**Comment by baszoetekouw** [comment]
Looks good for "regular" users:

![Image](https://github.com/SURFscz/SBS/assets/1461740/28d30b33-3690-42fa-9d96-e386c1b772dc)

In the case that no escalation contacts are available and the system fall back to sram-support, the text could use improvements.  I'll track that in #1181
